/*
ForecastAPI

Testing TrafficForecastingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package forecastapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ForecastAPI/go-sdk"
)

func Test_forecastapi_TrafficForecastingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TrafficForecastingAPIService CreateTrafficForecast", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TrafficForecastingAPI.CreateTrafficForecast(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
