/*
ForecastAPI

Testing BatchForecastingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package forecastapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ForecastAPI/go-sdk"
)

func Test_forecastapi_BatchForecastingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BatchForecastingAPIService CreateBatchForecast", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BatchForecastingAPI.CreateBatchForecast(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchForecastingAPIService GetBatchForecast", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var batchId string

		resp, httpRes, err := apiClient.BatchForecastingAPI.GetBatchForecast(context.Background(), batchId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchForecastingAPIService PresignBatchForecast", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BatchForecastingAPI.PresignBatchForecast(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
