/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AccumulatedForecastAssumptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccumulatedForecastAssumptions{}

// AccumulatedForecastAssumptions The assumptions behind the total and its band, stated explicitly
type AccumulatedForecastAssumptions struct {
	Correlation *float32 `json:"correlation,omitempty"`
	CorrelationSource *string `json:"correlation_source,omitempty"`
	// True only when the correlation in force is our measured default — a caller-supplied value is never labelled measured
	Measured *bool `json:"measured,omitempty"`
	// The statistical model behind the total's band
	Basis *string `json:"basis,omitempty"`
	Decay *float32 `json:"decay,omitempty"`
	DiscountRate *float32 `json:"discount_rate,omitempty"`
	// How the annual discount rate was converted to the series frequency
	PeriodsPerYear *float32 `json:"periods_per_year,omitempty"`
	Timing *string `json:"timing,omitempty"`
}

// NewAccumulatedForecastAssumptions instantiates a new AccumulatedForecastAssumptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccumulatedForecastAssumptions() *AccumulatedForecastAssumptions {
	this := AccumulatedForecastAssumptions{}
	return &this
}

// NewAccumulatedForecastAssumptionsWithDefaults instantiates a new AccumulatedForecastAssumptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccumulatedForecastAssumptionsWithDefaults() *AccumulatedForecastAssumptions {
	this := AccumulatedForecastAssumptions{}
	return &this
}

// GetCorrelation returns the Correlation field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetCorrelation() float32 {
	if o == nil || IsNil(o.Correlation) {
		var ret float32
		return ret
	}
	return *o.Correlation
}

// GetCorrelationOk returns a tuple with the Correlation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetCorrelationOk() (*float32, bool) {
	if o == nil || IsNil(o.Correlation) {
		return nil, false
	}
	return o.Correlation, true
}

// HasCorrelation returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasCorrelation() bool {
	if o != nil && !IsNil(o.Correlation) {
		return true
	}

	return false
}

// SetCorrelation gets a reference to the given float32 and assigns it to the Correlation field.
func (o *AccumulatedForecastAssumptions) SetCorrelation(v float32) {
	o.Correlation = &v
}

// GetCorrelationSource returns the CorrelationSource field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetCorrelationSource() string {
	if o == nil || IsNil(o.CorrelationSource) {
		var ret string
		return ret
	}
	return *o.CorrelationSource
}

// GetCorrelationSourceOk returns a tuple with the CorrelationSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetCorrelationSourceOk() (*string, bool) {
	if o == nil || IsNil(o.CorrelationSource) {
		return nil, false
	}
	return o.CorrelationSource, true
}

// HasCorrelationSource returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasCorrelationSource() bool {
	if o != nil && !IsNil(o.CorrelationSource) {
		return true
	}

	return false
}

// SetCorrelationSource gets a reference to the given string and assigns it to the CorrelationSource field.
func (o *AccumulatedForecastAssumptions) SetCorrelationSource(v string) {
	o.CorrelationSource = &v
}

// GetMeasured returns the Measured field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetMeasured() bool {
	if o == nil || IsNil(o.Measured) {
		var ret bool
		return ret
	}
	return *o.Measured
}

// GetMeasuredOk returns a tuple with the Measured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetMeasuredOk() (*bool, bool) {
	if o == nil || IsNil(o.Measured) {
		return nil, false
	}
	return o.Measured, true
}

// HasMeasured returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasMeasured() bool {
	if o != nil && !IsNil(o.Measured) {
		return true
	}

	return false
}

// SetMeasured gets a reference to the given bool and assigns it to the Measured field.
func (o *AccumulatedForecastAssumptions) SetMeasured(v bool) {
	o.Measured = &v
}

// GetBasis returns the Basis field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetBasis() string {
	if o == nil || IsNil(o.Basis) {
		var ret string
		return ret
	}
	return *o.Basis
}

// GetBasisOk returns a tuple with the Basis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetBasisOk() (*string, bool) {
	if o == nil || IsNil(o.Basis) {
		return nil, false
	}
	return o.Basis, true
}

// HasBasis returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasBasis() bool {
	if o != nil && !IsNil(o.Basis) {
		return true
	}

	return false
}

// SetBasis gets a reference to the given string and assigns it to the Basis field.
func (o *AccumulatedForecastAssumptions) SetBasis(v string) {
	o.Basis = &v
}

// GetDecay returns the Decay field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetDecay() float32 {
	if o == nil || IsNil(o.Decay) {
		var ret float32
		return ret
	}
	return *o.Decay
}

// GetDecayOk returns a tuple with the Decay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetDecayOk() (*float32, bool) {
	if o == nil || IsNil(o.Decay) {
		return nil, false
	}
	return o.Decay, true
}

// HasDecay returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasDecay() bool {
	if o != nil && !IsNil(o.Decay) {
		return true
	}

	return false
}

// SetDecay gets a reference to the given float32 and assigns it to the Decay field.
func (o *AccumulatedForecastAssumptions) SetDecay(v float32) {
	o.Decay = &v
}

// GetDiscountRate returns the DiscountRate field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetDiscountRate() float32 {
	if o == nil || IsNil(o.DiscountRate) {
		var ret float32
		return ret
	}
	return *o.DiscountRate
}

// GetDiscountRateOk returns a tuple with the DiscountRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetDiscountRateOk() (*float32, bool) {
	if o == nil || IsNil(o.DiscountRate) {
		return nil, false
	}
	return o.DiscountRate, true
}

// HasDiscountRate returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasDiscountRate() bool {
	if o != nil && !IsNil(o.DiscountRate) {
		return true
	}

	return false
}

// SetDiscountRate gets a reference to the given float32 and assigns it to the DiscountRate field.
func (o *AccumulatedForecastAssumptions) SetDiscountRate(v float32) {
	o.DiscountRate = &v
}

// GetPeriodsPerYear returns the PeriodsPerYear field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetPeriodsPerYear() float32 {
	if o == nil || IsNil(o.PeriodsPerYear) {
		var ret float32
		return ret
	}
	return *o.PeriodsPerYear
}

// GetPeriodsPerYearOk returns a tuple with the PeriodsPerYear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetPeriodsPerYearOk() (*float32, bool) {
	if o == nil || IsNil(o.PeriodsPerYear) {
		return nil, false
	}
	return o.PeriodsPerYear, true
}

// HasPeriodsPerYear returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasPeriodsPerYear() bool {
	if o != nil && !IsNil(o.PeriodsPerYear) {
		return true
	}

	return false
}

// SetPeriodsPerYear gets a reference to the given float32 and assigns it to the PeriodsPerYear field.
func (o *AccumulatedForecastAssumptions) SetPeriodsPerYear(v float32) {
	o.PeriodsPerYear = &v
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *AccumulatedForecastAssumptions) GetTiming() string {
	if o == nil || IsNil(o.Timing) {
		var ret string
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastAssumptions) GetTimingOk() (*string, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *AccumulatedForecastAssumptions) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given string and assigns it to the Timing field.
func (o *AccumulatedForecastAssumptions) SetTiming(v string) {
	o.Timing = &v
}

func (o AccumulatedForecastAssumptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccumulatedForecastAssumptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Correlation) {
		toSerialize["correlation"] = o.Correlation
	}
	if !IsNil(o.CorrelationSource) {
		toSerialize["correlation_source"] = o.CorrelationSource
	}
	if !IsNil(o.Measured) {
		toSerialize["measured"] = o.Measured
	}
	if !IsNil(o.Basis) {
		toSerialize["basis"] = o.Basis
	}
	if !IsNil(o.Decay) {
		toSerialize["decay"] = o.Decay
	}
	if !IsNil(o.DiscountRate) {
		toSerialize["discount_rate"] = o.DiscountRate
	}
	if !IsNil(o.PeriodsPerYear) {
		toSerialize["periods_per_year"] = o.PeriodsPerYear
	}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	return toSerialize, nil
}

type NullableAccumulatedForecastAssumptions struct {
	value *AccumulatedForecastAssumptions
	isSet bool
}

func (v NullableAccumulatedForecastAssumptions) Get() *AccumulatedForecastAssumptions {
	return v.value
}

func (v *NullableAccumulatedForecastAssumptions) Set(val *AccumulatedForecastAssumptions) {
	v.value = val
	v.isSet = true
}

func (v NullableAccumulatedForecastAssumptions) IsSet() bool {
	return v.isSet
}

func (v *NullableAccumulatedForecastAssumptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccumulatedForecastAssumptions(val *AccumulatedForecastAssumptions) *NullableAccumulatedForecastAssumptions {
	return &NullableAccumulatedForecastAssumptions{value: val, isSet: true}
}

func (v NullableAccumulatedForecastAssumptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccumulatedForecastAssumptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


