/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AccumulatedForecastByPeriodInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccumulatedForecastByPeriodInner{}

// AccumulatedForecastByPeriodInner struct for AccumulatedForecastByPeriodInner
type AccumulatedForecastByPeriodInner struct {
	Date *string `json:"date,omitempty"`
	// survival × discount weight applied to this period (period 1 is 1.0)
	Weight *float32 `json:"weight,omitempty"`
	// Running weighted total through this period
	Cumulative *float32 `json:"cumulative,omitempty"`
	// Running lower bound; present only when every period so far has a usable band
	CumulativeLower *float32 `json:"cumulative_lower,omitempty"`
	CumulativeUpper *float32 `json:"cumulative_upper,omitempty"`
}

// NewAccumulatedForecastByPeriodInner instantiates a new AccumulatedForecastByPeriodInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccumulatedForecastByPeriodInner() *AccumulatedForecastByPeriodInner {
	this := AccumulatedForecastByPeriodInner{}
	return &this
}

// NewAccumulatedForecastByPeriodInnerWithDefaults instantiates a new AccumulatedForecastByPeriodInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccumulatedForecastByPeriodInnerWithDefaults() *AccumulatedForecastByPeriodInner {
	this := AccumulatedForecastByPeriodInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *AccumulatedForecastByPeriodInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastByPeriodInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *AccumulatedForecastByPeriodInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *AccumulatedForecastByPeriodInner) SetDate(v string) {
	o.Date = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *AccumulatedForecastByPeriodInner) GetWeight() float32 {
	if o == nil || IsNil(o.Weight) {
		var ret float32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastByPeriodInner) GetWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *AccumulatedForecastByPeriodInner) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float32 and assigns it to the Weight field.
func (o *AccumulatedForecastByPeriodInner) SetWeight(v float32) {
	o.Weight = &v
}

// GetCumulative returns the Cumulative field value if set, zero value otherwise.
func (o *AccumulatedForecastByPeriodInner) GetCumulative() float32 {
	if o == nil || IsNil(o.Cumulative) {
		var ret float32
		return ret
	}
	return *o.Cumulative
}

// GetCumulativeOk returns a tuple with the Cumulative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastByPeriodInner) GetCumulativeOk() (*float32, bool) {
	if o == nil || IsNil(o.Cumulative) {
		return nil, false
	}
	return o.Cumulative, true
}

// HasCumulative returns a boolean if a field has been set.
func (o *AccumulatedForecastByPeriodInner) HasCumulative() bool {
	if o != nil && !IsNil(o.Cumulative) {
		return true
	}

	return false
}

// SetCumulative gets a reference to the given float32 and assigns it to the Cumulative field.
func (o *AccumulatedForecastByPeriodInner) SetCumulative(v float32) {
	o.Cumulative = &v
}

// GetCumulativeLower returns the CumulativeLower field value if set, zero value otherwise.
func (o *AccumulatedForecastByPeriodInner) GetCumulativeLower() float32 {
	if o == nil || IsNil(o.CumulativeLower) {
		var ret float32
		return ret
	}
	return *o.CumulativeLower
}

// GetCumulativeLowerOk returns a tuple with the CumulativeLower field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastByPeriodInner) GetCumulativeLowerOk() (*float32, bool) {
	if o == nil || IsNil(o.CumulativeLower) {
		return nil, false
	}
	return o.CumulativeLower, true
}

// HasCumulativeLower returns a boolean if a field has been set.
func (o *AccumulatedForecastByPeriodInner) HasCumulativeLower() bool {
	if o != nil && !IsNil(o.CumulativeLower) {
		return true
	}

	return false
}

// SetCumulativeLower gets a reference to the given float32 and assigns it to the CumulativeLower field.
func (o *AccumulatedForecastByPeriodInner) SetCumulativeLower(v float32) {
	o.CumulativeLower = &v
}

// GetCumulativeUpper returns the CumulativeUpper field value if set, zero value otherwise.
func (o *AccumulatedForecastByPeriodInner) GetCumulativeUpper() float32 {
	if o == nil || IsNil(o.CumulativeUpper) {
		var ret float32
		return ret
	}
	return *o.CumulativeUpper
}

// GetCumulativeUpperOk returns a tuple with the CumulativeUpper field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccumulatedForecastByPeriodInner) GetCumulativeUpperOk() (*float32, bool) {
	if o == nil || IsNil(o.CumulativeUpper) {
		return nil, false
	}
	return o.CumulativeUpper, true
}

// HasCumulativeUpper returns a boolean if a field has been set.
func (o *AccumulatedForecastByPeriodInner) HasCumulativeUpper() bool {
	if o != nil && !IsNil(o.CumulativeUpper) {
		return true
	}

	return false
}

// SetCumulativeUpper gets a reference to the given float32 and assigns it to the CumulativeUpper field.
func (o *AccumulatedForecastByPeriodInner) SetCumulativeUpper(v float32) {
	o.CumulativeUpper = &v
}

func (o AccumulatedForecastByPeriodInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccumulatedForecastByPeriodInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Cumulative) {
		toSerialize["cumulative"] = o.Cumulative
	}
	if !IsNil(o.CumulativeLower) {
		toSerialize["cumulative_lower"] = o.CumulativeLower
	}
	if !IsNil(o.CumulativeUpper) {
		toSerialize["cumulative_upper"] = o.CumulativeUpper
	}
	return toSerialize, nil
}

type NullableAccumulatedForecastByPeriodInner struct {
	value *AccumulatedForecastByPeriodInner
	isSet bool
}

func (v NullableAccumulatedForecastByPeriodInner) Get() *AccumulatedForecastByPeriodInner {
	return v.value
}

func (v *NullableAccumulatedForecastByPeriodInner) Set(val *AccumulatedForecastByPeriodInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccumulatedForecastByPeriodInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccumulatedForecastByPeriodInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccumulatedForecastByPeriodInner(val *AccumulatedForecastByPeriodInner) *NullableAccumulatedForecastByPeriodInner {
	return &NullableAccumulatedForecastByPeriodInner{value: val, isSet: true}
}

func (v NullableAccumulatedForecastByPeriodInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccumulatedForecastByPeriodInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


