/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.1.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AnalysisResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisResponseMeta{}

// AnalysisResponseMeta struct for AnalysisResponseMeta
type AnalysisResponseMeta struct {
	Timing *AnalysisResponseMetaTiming `json:"timing,omitempty"`
}

// NewAnalysisResponseMeta instantiates a new AnalysisResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisResponseMeta() *AnalysisResponseMeta {
	this := AnalysisResponseMeta{}
	return &this
}

// NewAnalysisResponseMetaWithDefaults instantiates a new AnalysisResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisResponseMetaWithDefaults() *AnalysisResponseMeta {
	this := AnalysisResponseMeta{}
	return &this
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *AnalysisResponseMeta) GetTiming() AnalysisResponseMetaTiming {
	if o == nil || IsNil(o.Timing) {
		var ret AnalysisResponseMetaTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponseMeta) GetTimingOk() (*AnalysisResponseMetaTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *AnalysisResponseMeta) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given AnalysisResponseMetaTiming and assigns it to the Timing field.
func (o *AnalysisResponseMeta) SetTiming(v AnalysisResponseMetaTiming) {
	o.Timing = &v
}

func (o AnalysisResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	return toSerialize, nil
}

type NullableAnalysisResponseMeta struct {
	value *AnalysisResponseMeta
	isSet bool
}

func (v NullableAnalysisResponseMeta) Get() *AnalysisResponseMeta {
	return v.value
}

func (v *NullableAnalysisResponseMeta) Set(val *AnalysisResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisResponseMeta(val *AnalysisResponseMeta) *NullableAnalysisResponseMeta {
	return &NullableAnalysisResponseMeta{value: val, isSet: true}
}

func (v NullableAnalysisResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


