/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrafficForecastingRequestTrafficSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficForecastingRequestTrafficSettings{}

// TrafficForecastingRequestTrafficSettings Infrastructure and traffic configuration
type TrafficForecastingRequestTrafficSettings struct {
	// Current infrastructure capacity (requests, users, etc.)
	CurrentCapacity float32 `json:"current_capacity"`
	// Normal/expected traffic level for comparison
	BaselineTraffic float32 `json:"baseline_traffic"`
	// Buffer percentage for scaling decisions (default 0.2 = 20%)
	ScalingBuffer NullableFloat32 `json:"scaling_buffer,omitempty"`
	// Utilization threshold to trigger scale up (default 0.8 = 80%)
	ScaleUpThreshold NullableFloat32 `json:"scale_up_threshold,omitempty"`
	// Utilization threshold to trigger scale down (default 0.3 = 30%)
	ScaleDownThreshold NullableFloat32 `json:"scale_down_threshold,omitempty"`
	// Traffic spike alert threshold as multiplier of baseline (default 1.5 = 150%)
	AlertThreshold NullableFloat32 `json:"alert_threshold,omitempty"`
	// Standard deviations for anomaly detection (default 3.0)
	AnomalyThreshold NullableFloat32 `json:"anomaly_threshold,omitempty"`
	// Variable cost per traffic unit (default 0.01)
	CostPerUnit NullableFloat32 `json:"cost_per_unit,omitempty"`
	// Fixed cost per capacity unit (default 0.1)
	FixedCostPerCapacity NullableFloat32 `json:"fixed_cost_per_capacity,omitempty"`
	// Base time in minutes for scaling operations (default 5)
	BaseScalingTime NullableInt32 `json:"base_scaling_time,omitempty"`
	// Whether auto-scaling is currently enabled (default false)
	EnableAutoScaling NullableBool `json:"enable_auto_scaling,omitempty"`
}

type _TrafficForecastingRequestTrafficSettings TrafficForecastingRequestTrafficSettings

// NewTrafficForecastingRequestTrafficSettings instantiates a new TrafficForecastingRequestTrafficSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficForecastingRequestTrafficSettings(currentCapacity float32, baselineTraffic float32) *TrafficForecastingRequestTrafficSettings {
	this := TrafficForecastingRequestTrafficSettings{}
	this.CurrentCapacity = currentCapacity
	this.BaselineTraffic = baselineTraffic
	return &this
}

// NewTrafficForecastingRequestTrafficSettingsWithDefaults instantiates a new TrafficForecastingRequestTrafficSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficForecastingRequestTrafficSettingsWithDefaults() *TrafficForecastingRequestTrafficSettings {
	this := TrafficForecastingRequestTrafficSettings{}
	return &this
}

// GetCurrentCapacity returns the CurrentCapacity field value
func (o *TrafficForecastingRequestTrafficSettings) GetCurrentCapacity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentCapacity
}

// GetCurrentCapacityOk returns a tuple with the CurrentCapacity field value
// and a boolean to check if the value has been set.
func (o *TrafficForecastingRequestTrafficSettings) GetCurrentCapacityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentCapacity, true
}

// SetCurrentCapacity sets field value
func (o *TrafficForecastingRequestTrafficSettings) SetCurrentCapacity(v float32) {
	o.CurrentCapacity = v
}

// GetBaselineTraffic returns the BaselineTraffic field value
func (o *TrafficForecastingRequestTrafficSettings) GetBaselineTraffic() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BaselineTraffic
}

// GetBaselineTrafficOk returns a tuple with the BaselineTraffic field value
// and a boolean to check if the value has been set.
func (o *TrafficForecastingRequestTrafficSettings) GetBaselineTrafficOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaselineTraffic, true
}

// SetBaselineTraffic sets field value
func (o *TrafficForecastingRequestTrafficSettings) SetBaselineTraffic(v float32) {
	o.BaselineTraffic = v
}

// GetScalingBuffer returns the ScalingBuffer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetScalingBuffer() float32 {
	if o == nil || IsNil(o.ScalingBuffer.Get()) {
		var ret float32
		return ret
	}
	return *o.ScalingBuffer.Get()
}

// GetScalingBufferOk returns a tuple with the ScalingBuffer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetScalingBufferOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScalingBuffer.Get(), o.ScalingBuffer.IsSet()
}

// HasScalingBuffer returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasScalingBuffer() bool {
	if o != nil && o.ScalingBuffer.IsSet() {
		return true
	}

	return false
}

// SetScalingBuffer gets a reference to the given NullableFloat32 and assigns it to the ScalingBuffer field.
func (o *TrafficForecastingRequestTrafficSettings) SetScalingBuffer(v float32) {
	o.ScalingBuffer.Set(&v)
}
// SetScalingBufferNil sets the value for ScalingBuffer to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetScalingBufferNil() {
	o.ScalingBuffer.Set(nil)
}

// UnsetScalingBuffer ensures that no value is present for ScalingBuffer, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetScalingBuffer() {
	o.ScalingBuffer.Unset()
}

// GetScaleUpThreshold returns the ScaleUpThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetScaleUpThreshold() float32 {
	if o == nil || IsNil(o.ScaleUpThreshold.Get()) {
		var ret float32
		return ret
	}
	return *o.ScaleUpThreshold.Get()
}

// GetScaleUpThresholdOk returns a tuple with the ScaleUpThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetScaleUpThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScaleUpThreshold.Get(), o.ScaleUpThreshold.IsSet()
}

// HasScaleUpThreshold returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasScaleUpThreshold() bool {
	if o != nil && o.ScaleUpThreshold.IsSet() {
		return true
	}

	return false
}

// SetScaleUpThreshold gets a reference to the given NullableFloat32 and assigns it to the ScaleUpThreshold field.
func (o *TrafficForecastingRequestTrafficSettings) SetScaleUpThreshold(v float32) {
	o.ScaleUpThreshold.Set(&v)
}
// SetScaleUpThresholdNil sets the value for ScaleUpThreshold to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetScaleUpThresholdNil() {
	o.ScaleUpThreshold.Set(nil)
}

// UnsetScaleUpThreshold ensures that no value is present for ScaleUpThreshold, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetScaleUpThreshold() {
	o.ScaleUpThreshold.Unset()
}

// GetScaleDownThreshold returns the ScaleDownThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetScaleDownThreshold() float32 {
	if o == nil || IsNil(o.ScaleDownThreshold.Get()) {
		var ret float32
		return ret
	}
	return *o.ScaleDownThreshold.Get()
}

// GetScaleDownThresholdOk returns a tuple with the ScaleDownThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetScaleDownThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScaleDownThreshold.Get(), o.ScaleDownThreshold.IsSet()
}

// HasScaleDownThreshold returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasScaleDownThreshold() bool {
	if o != nil && o.ScaleDownThreshold.IsSet() {
		return true
	}

	return false
}

// SetScaleDownThreshold gets a reference to the given NullableFloat32 and assigns it to the ScaleDownThreshold field.
func (o *TrafficForecastingRequestTrafficSettings) SetScaleDownThreshold(v float32) {
	o.ScaleDownThreshold.Set(&v)
}
// SetScaleDownThresholdNil sets the value for ScaleDownThreshold to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetScaleDownThresholdNil() {
	o.ScaleDownThreshold.Set(nil)
}

// UnsetScaleDownThreshold ensures that no value is present for ScaleDownThreshold, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetScaleDownThreshold() {
	o.ScaleDownThreshold.Unset()
}

// GetAlertThreshold returns the AlertThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetAlertThreshold() float32 {
	if o == nil || IsNil(o.AlertThreshold.Get()) {
		var ret float32
		return ret
	}
	return *o.AlertThreshold.Get()
}

// GetAlertThresholdOk returns a tuple with the AlertThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetAlertThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlertThreshold.Get(), o.AlertThreshold.IsSet()
}

// HasAlertThreshold returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasAlertThreshold() bool {
	if o != nil && o.AlertThreshold.IsSet() {
		return true
	}

	return false
}

// SetAlertThreshold gets a reference to the given NullableFloat32 and assigns it to the AlertThreshold field.
func (o *TrafficForecastingRequestTrafficSettings) SetAlertThreshold(v float32) {
	o.AlertThreshold.Set(&v)
}
// SetAlertThresholdNil sets the value for AlertThreshold to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetAlertThresholdNil() {
	o.AlertThreshold.Set(nil)
}

// UnsetAlertThreshold ensures that no value is present for AlertThreshold, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetAlertThreshold() {
	o.AlertThreshold.Unset()
}

// GetAnomalyThreshold returns the AnomalyThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetAnomalyThreshold() float32 {
	if o == nil || IsNil(o.AnomalyThreshold.Get()) {
		var ret float32
		return ret
	}
	return *o.AnomalyThreshold.Get()
}

// GetAnomalyThresholdOk returns a tuple with the AnomalyThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetAnomalyThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnomalyThreshold.Get(), o.AnomalyThreshold.IsSet()
}

// HasAnomalyThreshold returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasAnomalyThreshold() bool {
	if o != nil && o.AnomalyThreshold.IsSet() {
		return true
	}

	return false
}

// SetAnomalyThreshold gets a reference to the given NullableFloat32 and assigns it to the AnomalyThreshold field.
func (o *TrafficForecastingRequestTrafficSettings) SetAnomalyThreshold(v float32) {
	o.AnomalyThreshold.Set(&v)
}
// SetAnomalyThresholdNil sets the value for AnomalyThreshold to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetAnomalyThresholdNil() {
	o.AnomalyThreshold.Set(nil)
}

// UnsetAnomalyThreshold ensures that no value is present for AnomalyThreshold, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetAnomalyThreshold() {
	o.AnomalyThreshold.Unset()
}

// GetCostPerUnit returns the CostPerUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetCostPerUnit() float32 {
	if o == nil || IsNil(o.CostPerUnit.Get()) {
		var ret float32
		return ret
	}
	return *o.CostPerUnit.Get()
}

// GetCostPerUnitOk returns a tuple with the CostPerUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetCostPerUnitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CostPerUnit.Get(), o.CostPerUnit.IsSet()
}

// HasCostPerUnit returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasCostPerUnit() bool {
	if o != nil && o.CostPerUnit.IsSet() {
		return true
	}

	return false
}

// SetCostPerUnit gets a reference to the given NullableFloat32 and assigns it to the CostPerUnit field.
func (o *TrafficForecastingRequestTrafficSettings) SetCostPerUnit(v float32) {
	o.CostPerUnit.Set(&v)
}
// SetCostPerUnitNil sets the value for CostPerUnit to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetCostPerUnitNil() {
	o.CostPerUnit.Set(nil)
}

// UnsetCostPerUnit ensures that no value is present for CostPerUnit, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetCostPerUnit() {
	o.CostPerUnit.Unset()
}

// GetFixedCostPerCapacity returns the FixedCostPerCapacity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetFixedCostPerCapacity() float32 {
	if o == nil || IsNil(o.FixedCostPerCapacity.Get()) {
		var ret float32
		return ret
	}
	return *o.FixedCostPerCapacity.Get()
}

// GetFixedCostPerCapacityOk returns a tuple with the FixedCostPerCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetFixedCostPerCapacityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixedCostPerCapacity.Get(), o.FixedCostPerCapacity.IsSet()
}

// HasFixedCostPerCapacity returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasFixedCostPerCapacity() bool {
	if o != nil && o.FixedCostPerCapacity.IsSet() {
		return true
	}

	return false
}

// SetFixedCostPerCapacity gets a reference to the given NullableFloat32 and assigns it to the FixedCostPerCapacity field.
func (o *TrafficForecastingRequestTrafficSettings) SetFixedCostPerCapacity(v float32) {
	o.FixedCostPerCapacity.Set(&v)
}
// SetFixedCostPerCapacityNil sets the value for FixedCostPerCapacity to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetFixedCostPerCapacityNil() {
	o.FixedCostPerCapacity.Set(nil)
}

// UnsetFixedCostPerCapacity ensures that no value is present for FixedCostPerCapacity, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetFixedCostPerCapacity() {
	o.FixedCostPerCapacity.Unset()
}

// GetBaseScalingTime returns the BaseScalingTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetBaseScalingTime() int32 {
	if o == nil || IsNil(o.BaseScalingTime.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseScalingTime.Get()
}

// GetBaseScalingTimeOk returns a tuple with the BaseScalingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetBaseScalingTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseScalingTime.Get(), o.BaseScalingTime.IsSet()
}

// HasBaseScalingTime returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasBaseScalingTime() bool {
	if o != nil && o.BaseScalingTime.IsSet() {
		return true
	}

	return false
}

// SetBaseScalingTime gets a reference to the given NullableInt32 and assigns it to the BaseScalingTime field.
func (o *TrafficForecastingRequestTrafficSettings) SetBaseScalingTime(v int32) {
	o.BaseScalingTime.Set(&v)
}
// SetBaseScalingTimeNil sets the value for BaseScalingTime to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetBaseScalingTimeNil() {
	o.BaseScalingTime.Set(nil)
}

// UnsetBaseScalingTime ensures that no value is present for BaseScalingTime, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetBaseScalingTime() {
	o.BaseScalingTime.Unset()
}

// GetEnableAutoScaling returns the EnableAutoScaling field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficForecastingRequestTrafficSettings) GetEnableAutoScaling() bool {
	if o == nil || IsNil(o.EnableAutoScaling.Get()) {
		var ret bool
		return ret
	}
	return *o.EnableAutoScaling.Get()
}

// GetEnableAutoScalingOk returns a tuple with the EnableAutoScaling field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficForecastingRequestTrafficSettings) GetEnableAutoScalingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnableAutoScaling.Get(), o.EnableAutoScaling.IsSet()
}

// HasEnableAutoScaling returns a boolean if a field has been set.
func (o *TrafficForecastingRequestTrafficSettings) HasEnableAutoScaling() bool {
	if o != nil && o.EnableAutoScaling.IsSet() {
		return true
	}

	return false
}

// SetEnableAutoScaling gets a reference to the given NullableBool and assigns it to the EnableAutoScaling field.
func (o *TrafficForecastingRequestTrafficSettings) SetEnableAutoScaling(v bool) {
	o.EnableAutoScaling.Set(&v)
}
// SetEnableAutoScalingNil sets the value for EnableAutoScaling to be an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) SetEnableAutoScalingNil() {
	o.EnableAutoScaling.Set(nil)
}

// UnsetEnableAutoScaling ensures that no value is present for EnableAutoScaling, not even an explicit nil
func (o *TrafficForecastingRequestTrafficSettings) UnsetEnableAutoScaling() {
	o.EnableAutoScaling.Unset()
}

func (o TrafficForecastingRequestTrafficSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficForecastingRequestTrafficSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current_capacity"] = o.CurrentCapacity
	toSerialize["baseline_traffic"] = o.BaselineTraffic
	if o.ScalingBuffer.IsSet() {
		toSerialize["scaling_buffer"] = o.ScalingBuffer.Get()
	}
	if o.ScaleUpThreshold.IsSet() {
		toSerialize["scale_up_threshold"] = o.ScaleUpThreshold.Get()
	}
	if o.ScaleDownThreshold.IsSet() {
		toSerialize["scale_down_threshold"] = o.ScaleDownThreshold.Get()
	}
	if o.AlertThreshold.IsSet() {
		toSerialize["alert_threshold"] = o.AlertThreshold.Get()
	}
	if o.AnomalyThreshold.IsSet() {
		toSerialize["anomaly_threshold"] = o.AnomalyThreshold.Get()
	}
	if o.CostPerUnit.IsSet() {
		toSerialize["cost_per_unit"] = o.CostPerUnit.Get()
	}
	if o.FixedCostPerCapacity.IsSet() {
		toSerialize["fixed_cost_per_capacity"] = o.FixedCostPerCapacity.Get()
	}
	if o.BaseScalingTime.IsSet() {
		toSerialize["base_scaling_time"] = o.BaseScalingTime.Get()
	}
	if o.EnableAutoScaling.IsSet() {
		toSerialize["enable_auto_scaling"] = o.EnableAutoScaling.Get()
	}
	return toSerialize, nil
}

func (o *TrafficForecastingRequestTrafficSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current_capacity",
		"baseline_traffic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrafficForecastingRequestTrafficSettings := _TrafficForecastingRequestTrafficSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrafficForecastingRequestTrafficSettings)

	if err != nil {
		return err
	}

	*o = TrafficForecastingRequestTrafficSettings(varTrafficForecastingRequestTrafficSettings)

	return err
}

type NullableTrafficForecastingRequestTrafficSettings struct {
	value *TrafficForecastingRequestTrafficSettings
	isSet bool
}

func (v NullableTrafficForecastingRequestTrafficSettings) Get() *TrafficForecastingRequestTrafficSettings {
	return v.value
}

func (v *NullableTrafficForecastingRequestTrafficSettings) Set(val *TrafficForecastingRequestTrafficSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficForecastingRequestTrafficSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficForecastingRequestTrafficSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficForecastingRequestTrafficSettings(val *TrafficForecastingRequestTrafficSettings) *NullableTrafficForecastingRequestTrafficSettings {
	return &NullableTrafficForecastingRequestTrafficSettings{value: val, isSet: true}
}

func (v NullableTrafficForecastingRequestTrafficSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficForecastingRequestTrafficSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


