/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DetectAnomalies422Response - struct for DetectAnomalies422Response
type DetectAnomalies422Response struct {
	DetectAnomalies422ResponseOneOf *DetectAnomalies422ResponseOneOf
	ValidationErrorResponse *ValidationErrorResponse
}

// DetectAnomalies422ResponseOneOfAsDetectAnomalies422Response is a convenience function that returns DetectAnomalies422ResponseOneOf wrapped in DetectAnomalies422Response
func DetectAnomalies422ResponseOneOfAsDetectAnomalies422Response(v *DetectAnomalies422ResponseOneOf) DetectAnomalies422Response {
	return DetectAnomalies422Response{
		DetectAnomalies422ResponseOneOf: v,
	}
}

// ValidationErrorResponseAsDetectAnomalies422Response is a convenience function that returns ValidationErrorResponse wrapped in DetectAnomalies422Response
func ValidationErrorResponseAsDetectAnomalies422Response(v *ValidationErrorResponse) DetectAnomalies422Response {
	return DetectAnomalies422Response{
		ValidationErrorResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DetectAnomalies422Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DetectAnomalies422ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.DetectAnomalies422ResponseOneOf)
	if err == nil {
		jsonDetectAnomalies422ResponseOneOf, _ := json.Marshal(dst.DetectAnomalies422ResponseOneOf)
		if string(jsonDetectAnomalies422ResponseOneOf) == "{}" { // empty struct
			dst.DetectAnomalies422ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.DetectAnomalies422ResponseOneOf); err != nil {
				dst.DetectAnomalies422ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.DetectAnomalies422ResponseOneOf = nil
	}

	// try to unmarshal data into ValidationErrorResponse
	err = newStrictDecoder(data).Decode(&dst.ValidationErrorResponse)
	if err == nil {
		jsonValidationErrorResponse, _ := json.Marshal(dst.ValidationErrorResponse)
		if string(jsonValidationErrorResponse) == "{}" { // empty struct
			dst.ValidationErrorResponse = nil
		} else {
			if err = validator.Validate(dst.ValidationErrorResponse); err != nil {
				dst.ValidationErrorResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ValidationErrorResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DetectAnomalies422ResponseOneOf = nil
		dst.ValidationErrorResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DetectAnomalies422Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DetectAnomalies422Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DetectAnomalies422Response) MarshalJSON() ([]byte, error) {
	if src.DetectAnomalies422ResponseOneOf != nil {
		return json.Marshal(&src.DetectAnomalies422ResponseOneOf)
	}

	if src.ValidationErrorResponse != nil {
		return json.Marshal(&src.ValidationErrorResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DetectAnomalies422Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DetectAnomalies422ResponseOneOf != nil {
		return obj.DetectAnomalies422ResponseOneOf
	}

	if obj.ValidationErrorResponse != nil {
		return obj.ValidationErrorResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DetectAnomalies422Response) GetActualInstanceValue() (interface{}) {
	if obj.DetectAnomalies422ResponseOneOf != nil {
		return *obj.DetectAnomalies422ResponseOneOf
	}

	if obj.ValidationErrorResponse != nil {
		return *obj.ValidationErrorResponse
	}

	// all schemas are nil
	return nil
}

type NullableDetectAnomalies422Response struct {
	value *DetectAnomalies422Response
	isSet bool
}

func (v NullableDetectAnomalies422Response) Get() *DetectAnomalies422Response {
	return v.value
}

func (v *NullableDetectAnomalies422Response) Set(val *DetectAnomalies422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectAnomalies422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectAnomalies422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectAnomalies422Response(val *DetectAnomalies422Response) *NullableDetectAnomalies422Response {
	return &NullableDetectAnomalies422Response{value: val, isSet: true}
}

func (v NullableDetectAnomalies422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectAnomalies422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


