/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the CreateForecast400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateForecast400Response{}

// CreateForecast400Response struct for CreateForecast400Response
type CreateForecast400Response struct {
	Error *string `json:"error,omitempty"`
	Reason *string `json:"reason,omitempty"`
	TimeTakenMs *float32 `json:"time_taken_ms,omitempty"`
}

// NewCreateForecast400Response instantiates a new CreateForecast400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateForecast400Response() *CreateForecast400Response {
	this := CreateForecast400Response{}
	return &this
}

// NewCreateForecast400ResponseWithDefaults instantiates a new CreateForecast400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateForecast400ResponseWithDefaults() *CreateForecast400Response {
	this := CreateForecast400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateForecast400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateForecast400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateForecast400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateForecast400Response) SetError(v string) {
	o.Error = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CreateForecast400Response) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateForecast400Response) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CreateForecast400Response) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CreateForecast400Response) SetReason(v string) {
	o.Reason = &v
}

// GetTimeTakenMs returns the TimeTakenMs field value if set, zero value otherwise.
func (o *CreateForecast400Response) GetTimeTakenMs() float32 {
	if o == nil || IsNil(o.TimeTakenMs) {
		var ret float32
		return ret
	}
	return *o.TimeTakenMs
}

// GetTimeTakenMsOk returns a tuple with the TimeTakenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateForecast400Response) GetTimeTakenMsOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeTakenMs) {
		return nil, false
	}
	return o.TimeTakenMs, true
}

// HasTimeTakenMs returns a boolean if a field has been set.
func (o *CreateForecast400Response) HasTimeTakenMs() bool {
	if o != nil && !IsNil(o.TimeTakenMs) {
		return true
	}

	return false
}

// SetTimeTakenMs gets a reference to the given float32 and assigns it to the TimeTakenMs field.
func (o *CreateForecast400Response) SetTimeTakenMs(v float32) {
	o.TimeTakenMs = &v
}

func (o CreateForecast400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateForecast400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.TimeTakenMs) {
		toSerialize["time_taken_ms"] = o.TimeTakenMs
	}
	return toSerialize, nil
}

type NullableCreateForecast400Response struct {
	value *CreateForecast400Response
	isSet bool
}

func (v NullableCreateForecast400Response) Get() *CreateForecast400Response {
	return v.value
}

func (v *NullableCreateForecast400Response) Set(val *CreateForecast400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateForecast400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateForecast400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateForecast400Response(val *CreateForecast400Response) *NullableCreateForecast400Response {
	return &NullableCreateForecast400Response{value: val, isSet: true}
}

func (v NullableCreateForecast400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateForecast400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


