/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.1.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ForecastResponseMetaTiming type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastResponseMetaTiming{}

// ForecastResponseMetaTiming struct for ForecastResponseMetaTiming
type ForecastResponseMetaTiming struct {
	// Time taken for validation in milliseconds
	Validation *float32 `json:"validation,omitempty"`
	// Time taken for method selection in milliseconds
	Selection *float32 `json:"selection,omitempty"`
	// Time taken for forecasting in milliseconds
	Forecasting *float32 `json:"forecasting,omitempty"`
	// Total processing time in milliseconds
	Total *float32 `json:"total,omitempty"`
}

// NewForecastResponseMetaTiming instantiates a new ForecastResponseMetaTiming object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastResponseMetaTiming() *ForecastResponseMetaTiming {
	this := ForecastResponseMetaTiming{}
	return &this
}

// NewForecastResponseMetaTimingWithDefaults instantiates a new ForecastResponseMetaTiming object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastResponseMetaTimingWithDefaults() *ForecastResponseMetaTiming {
	this := ForecastResponseMetaTiming{}
	return &this
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *ForecastResponseMetaTiming) GetValidation() float32 {
	if o == nil || IsNil(o.Validation) {
		var ret float32
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMetaTiming) GetValidationOk() (*float32, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *ForecastResponseMetaTiming) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given float32 and assigns it to the Validation field.
func (o *ForecastResponseMetaTiming) SetValidation(v float32) {
	o.Validation = &v
}

// GetSelection returns the Selection field value if set, zero value otherwise.
func (o *ForecastResponseMetaTiming) GetSelection() float32 {
	if o == nil || IsNil(o.Selection) {
		var ret float32
		return ret
	}
	return *o.Selection
}

// GetSelectionOk returns a tuple with the Selection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMetaTiming) GetSelectionOk() (*float32, bool) {
	if o == nil || IsNil(o.Selection) {
		return nil, false
	}
	return o.Selection, true
}

// HasSelection returns a boolean if a field has been set.
func (o *ForecastResponseMetaTiming) HasSelection() bool {
	if o != nil && !IsNil(o.Selection) {
		return true
	}

	return false
}

// SetSelection gets a reference to the given float32 and assigns it to the Selection field.
func (o *ForecastResponseMetaTiming) SetSelection(v float32) {
	o.Selection = &v
}

// GetForecasting returns the Forecasting field value if set, zero value otherwise.
func (o *ForecastResponseMetaTiming) GetForecasting() float32 {
	if o == nil || IsNil(o.Forecasting) {
		var ret float32
		return ret
	}
	return *o.Forecasting
}

// GetForecastingOk returns a tuple with the Forecasting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMetaTiming) GetForecastingOk() (*float32, bool) {
	if o == nil || IsNil(o.Forecasting) {
		return nil, false
	}
	return o.Forecasting, true
}

// HasForecasting returns a boolean if a field has been set.
func (o *ForecastResponseMetaTiming) HasForecasting() bool {
	if o != nil && !IsNil(o.Forecasting) {
		return true
	}

	return false
}

// SetForecasting gets a reference to the given float32 and assigns it to the Forecasting field.
func (o *ForecastResponseMetaTiming) SetForecasting(v float32) {
	o.Forecasting = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ForecastResponseMetaTiming) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMetaTiming) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ForecastResponseMetaTiming) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *ForecastResponseMetaTiming) SetTotal(v float32) {
	o.Total = &v
}

func (o ForecastResponseMetaTiming) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastResponseMetaTiming) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Selection) {
		toSerialize["selection"] = o.Selection
	}
	if !IsNil(o.Forecasting) {
		toSerialize["forecasting"] = o.Forecasting
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableForecastResponseMetaTiming struct {
	value *ForecastResponseMetaTiming
	isSet bool
}

func (v NullableForecastResponseMetaTiming) Get() *ForecastResponseMetaTiming {
	return v.value
}

func (v *NullableForecastResponseMetaTiming) Set(val *ForecastResponseMetaTiming) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastResponseMetaTiming) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastResponseMetaTiming) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastResponseMetaTiming(val *ForecastResponseMetaTiming) *NullableForecastResponseMetaTiming {
	return &NullableForecastResponseMetaTiming{value: val, isSet: true}
}

func (v NullableForecastResponseMetaTiming) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastResponseMetaTiming) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


