/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupedForecastRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedForecastRequest{}

// GroupedForecastRequest Configuration is request-level only: every node of a hierarchy must share `periods`, `frequency`, `model` and `confidence`, so per-series overrides are rejected rather than silently ignored. The planning parameters (`quantiles`, `value_bounds`, `adjustments`, `accumulate`) are not supported on grouped forecasts and are rejected explicitly. All series must end on the same date so forecast periods align; histories may start whenever they like — a segment that launched later simply contributes zero before its first data point. A request may expand to at most 250 nodes (leaves plus every derived aggregate and the total) across at most 4 hierarchy levels. 
type GroupedForecastRequest struct {
	// Names the measure being forecast (e.g. \"mrr\"). The hierarchy's total is stored under this identifier exactly like a plain /v2/forecast for it — the total of the hierarchy IS the measure. 
	Identifier string `json:"identifier"`
	// Optional tenant scope, independent of segment — tenancy keeps meaning \"whose data is this\", segment means \"which slice\". 
	TenantContext NullableString `json:"tenant_context,omitempty"`
	// The dimensions of the hierarchy, outermost first. Each series' segment must name exactly these dimensions.
	Hierarchy []string `json:"hierarchy"`
	// - bottom_up (default): only the leaves are forecast; every aggregate is the   exact sum of its children. Fast and cheap; best when leaf histories are   substantial enough to forecast well on their own. - min_trace: every node — aggregates included — is forecast, then MinTrace   optimally redistributes the disagreement between levels into a coherent set.   Costs one forecast per node, but lets the usually-smoother aggregate series   inform the result, which tends to help when leaves are short or noisy.  top_down is not supported and is rejected by name. 
	Reconciliation *string `json:"reconciliation,omitempty"`
	// bottom_up only — the assumed correlation between sibling errors when building aggregate confidence bands. 0 = independent siblings, 1 = perfectly correlated (equivalent to summing the bounds). Echoed back in the response and never labelled as measured. 
	Correlation *float32 `json:"correlation,omitempty"`
	// Data frequency, shared by every series in the hierarchy
	Frequency string `json:"frequency"`
	// Number of periods to forecast, shared by every node
	Periods int32 `json:"periods"`
	// Type of data (e.g., sales, demand, revenue). Sales-family types get non-negative reconciliation treatment.
	DataType *string `json:"data_type,omitempty"`
	// Forecasting engine used for every node. `auto` is not accepted here: it routes per series, and a hierarchy is reconciled under one model. 
	Model *string `json:"model,omitempty"`
	// Confidence level for prediction intervals, shared by every node
	Confidence *float32 `json:"confidence,omitempty"`
	// Alias for `confidence`; if both are sent, `confidence` wins
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// The leaves of the hierarchy — one entry per combination of dimension values, each combination exactly once. Up to 200 series on a paid plan, 10 on the free tier. Aggregate levels are derived by the API and must not be sent. 
	Series []GroupedForecastSeries `json:"series"`
}

type _GroupedForecastRequest GroupedForecastRequest

// NewGroupedForecastRequest instantiates a new GroupedForecastRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedForecastRequest(identifier string, hierarchy []string, frequency string, periods int32, series []GroupedForecastSeries) *GroupedForecastRequest {
	this := GroupedForecastRequest{}
	this.Identifier = identifier
	this.Hierarchy = hierarchy
	var reconciliation string = "bottom_up"
	this.Reconciliation = &reconciliation
	var correlation float32 = 0.5
	this.Correlation = &correlation
	this.Frequency = frequency
	this.Periods = periods
	var dataType string = "sales"
	this.DataType = &dataType
	var model string = "standard"
	this.Model = &model
	var confidence float32 = 0.8
	this.Confidence = &confidence
	this.Series = series
	return &this
}

// NewGroupedForecastRequestWithDefaults instantiates a new GroupedForecastRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedForecastRequestWithDefaults() *GroupedForecastRequest {
	this := GroupedForecastRequest{}
	var reconciliation string = "bottom_up"
	this.Reconciliation = &reconciliation
	var correlation float32 = 0.5
	this.Correlation = &correlation
	var dataType string = "sales"
	this.DataType = &dataType
	var model string = "standard"
	this.Model = &model
	var confidence float32 = 0.8
	this.Confidence = &confidence
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *GroupedForecastRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *GroupedForecastRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTenantContext returns the TenantContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupedForecastRequest) GetTenantContext() string {
	if o == nil || IsNil(o.TenantContext.Get()) {
		var ret string
		return ret
	}
	return *o.TenantContext.Get()
}

// GetTenantContextOk returns a tuple with the TenantContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupedForecastRequest) GetTenantContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantContext.Get(), o.TenantContext.IsSet()
}

// HasTenantContext returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasTenantContext() bool {
	if o != nil && o.TenantContext.IsSet() {
		return true
	}

	return false
}

// SetTenantContext gets a reference to the given NullableString and assigns it to the TenantContext field.
func (o *GroupedForecastRequest) SetTenantContext(v string) {
	o.TenantContext.Set(&v)
}
// SetTenantContextNil sets the value for TenantContext to be an explicit nil
func (o *GroupedForecastRequest) SetTenantContextNil() {
	o.TenantContext.Set(nil)
}

// UnsetTenantContext ensures that no value is present for TenantContext, not even an explicit nil
func (o *GroupedForecastRequest) UnsetTenantContext() {
	o.TenantContext.Unset()
}

// GetHierarchy returns the Hierarchy field value
func (o *GroupedForecastRequest) GetHierarchy() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Hierarchy
}

// GetHierarchyOk returns a tuple with the Hierarchy field value
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetHierarchyOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hierarchy, true
}

// SetHierarchy sets field value
func (o *GroupedForecastRequest) SetHierarchy(v []string) {
	o.Hierarchy = v
}

// GetReconciliation returns the Reconciliation field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetReconciliation() string {
	if o == nil || IsNil(o.Reconciliation) {
		var ret string
		return ret
	}
	return *o.Reconciliation
}

// GetReconciliationOk returns a tuple with the Reconciliation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetReconciliationOk() (*string, bool) {
	if o == nil || IsNil(o.Reconciliation) {
		return nil, false
	}
	return o.Reconciliation, true
}

// HasReconciliation returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasReconciliation() bool {
	if o != nil && !IsNil(o.Reconciliation) {
		return true
	}

	return false
}

// SetReconciliation gets a reference to the given string and assigns it to the Reconciliation field.
func (o *GroupedForecastRequest) SetReconciliation(v string) {
	o.Reconciliation = &v
}

// GetCorrelation returns the Correlation field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetCorrelation() float32 {
	if o == nil || IsNil(o.Correlation) {
		var ret float32
		return ret
	}
	return *o.Correlation
}

// GetCorrelationOk returns a tuple with the Correlation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetCorrelationOk() (*float32, bool) {
	if o == nil || IsNil(o.Correlation) {
		return nil, false
	}
	return o.Correlation, true
}

// HasCorrelation returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasCorrelation() bool {
	if o != nil && !IsNil(o.Correlation) {
		return true
	}

	return false
}

// SetCorrelation gets a reference to the given float32 and assigns it to the Correlation field.
func (o *GroupedForecastRequest) SetCorrelation(v float32) {
	o.Correlation = &v
}

// GetFrequency returns the Frequency field value
func (o *GroupedForecastRequest) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *GroupedForecastRequest) SetFrequency(v string) {
	o.Frequency = v
}

// GetPeriods returns the Periods field value
func (o *GroupedForecastRequest) GetPeriods() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetPeriodsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Periods, true
}

// SetPeriods sets field value
func (o *GroupedForecastRequest) SetPeriods(v int32) {
	o.Periods = v
}

// GetDataType returns the DataType field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetDataType() string {
	if o == nil || IsNil(o.DataType) {
		var ret string
		return ret
	}
	return *o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetDataTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DataType) {
		return nil, false
	}
	return o.DataType, true
}

// HasDataType returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasDataType() bool {
	if o != nil && !IsNil(o.DataType) {
		return true
	}

	return false
}

// SetDataType gets a reference to the given string and assigns it to the DataType field.
func (o *GroupedForecastRequest) SetDataType(v string) {
	o.DataType = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *GroupedForecastRequest) SetModel(v string) {
	o.Model = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *GroupedForecastRequest) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *GroupedForecastRequest) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *GroupedForecastRequest) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *GroupedForecastRequest) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetSeries returns the Series field value
func (o *GroupedForecastRequest) GetSeries() []GroupedForecastSeries {
	if o == nil {
		var ret []GroupedForecastSeries
		return ret
	}

	return o.Series
}

// GetSeriesOk returns a tuple with the Series field value
// and a boolean to check if the value has been set.
func (o *GroupedForecastRequest) GetSeriesOk() ([]GroupedForecastSeries, bool) {
	if o == nil {
		return nil, false
	}
	return o.Series, true
}

// SetSeries sets field value
func (o *GroupedForecastRequest) SetSeries(v []GroupedForecastSeries) {
	o.Series = v
}

func (o GroupedForecastRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedForecastRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	if o.TenantContext.IsSet() {
		toSerialize["tenant_context"] = o.TenantContext.Get()
	}
	toSerialize["hierarchy"] = o.Hierarchy
	if !IsNil(o.Reconciliation) {
		toSerialize["reconciliation"] = o.Reconciliation
	}
	if !IsNil(o.Correlation) {
		toSerialize["correlation"] = o.Correlation
	}
	toSerialize["frequency"] = o.Frequency
	toSerialize["periods"] = o.Periods
	if !IsNil(o.DataType) {
		toSerialize["data_type"] = o.DataType
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	toSerialize["series"] = o.Series
	return toSerialize, nil
}

func (o *GroupedForecastRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"hierarchy",
		"frequency",
		"periods",
		"series",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupedForecastRequest := _GroupedForecastRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupedForecastRequest)

	if err != nil {
		return err
	}

	*o = GroupedForecastRequest(varGroupedForecastRequest)

	return err
}

type NullableGroupedForecastRequest struct {
	value *GroupedForecastRequest
	isSet bool
}

func (v NullableGroupedForecastRequest) Get() *GroupedForecastRequest {
	return v.value
}

func (v *NullableGroupedForecastRequest) Set(val *GroupedForecastRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedForecastRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedForecastRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedForecastRequest(val *GroupedForecastRequest) *NullableGroupedForecastRequest {
	return &NullableGroupedForecastRequest{value: val, isSet: true}
}

func (v NullableGroupedForecastRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedForecastRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


