/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.1.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchForecastSeries type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchForecastSeries{}

// BatchForecastSeries struct for BatchForecastSeries
type BatchForecastSeries struct {
	// SKU, Product ID, or other identifier for this series
	Identifier string `json:"identifier"`
	// Optional segmentation dimension — the same identifier may appear under several tenant_context values in one batch
	TenantContext NullableString `json:"tenant_context,omitempty"`
	// Historical data for this series (at most 1,000 points per series on the free tier)
	Data []BatchForecastSeriesDataInner `json:"data"`
	// Override of the request-level horizon for this series
	Periods *int32 `json:"periods,omitempty"`
	// Override of the request-level frequency
	Frequency *string `json:"frequency,omitempty"`
	// Override of the request-level data type
	DataType *string `json:"data_type,omitempty"`
	// Override of the request-level confidence
	Confidence *float32 `json:"confidence,omitempty"`
	// Alias for `confidence`
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Quantiles []float32 `json:"quantiles,omitempty"`
	ValueBounds *ValueBounds `json:"value_bounds,omitempty"`
	// What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Adjustments []AdjustmentsInner `json:"adjustments,omitempty"`
	Accumulate *AccumulateOptions `json:"accumulate,omitempty"`
}

type _BatchForecastSeries BatchForecastSeries

// NewBatchForecastSeries instantiates a new BatchForecastSeries object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchForecastSeries(identifier string, data []BatchForecastSeriesDataInner) *BatchForecastSeries {
	this := BatchForecastSeries{}
	this.Identifier = identifier
	this.Data = data
	return &this
}

// NewBatchForecastSeriesWithDefaults instantiates a new BatchForecastSeries object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchForecastSeriesWithDefaults() *BatchForecastSeries {
	this := BatchForecastSeries{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *BatchForecastSeries) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *BatchForecastSeries) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTenantContext returns the TenantContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastSeries) GetTenantContext() string {
	if o == nil || IsNil(o.TenantContext.Get()) {
		var ret string
		return ret
	}
	return *o.TenantContext.Get()
}

// GetTenantContextOk returns a tuple with the TenantContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastSeries) GetTenantContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantContext.Get(), o.TenantContext.IsSet()
}

// HasTenantContext returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasTenantContext() bool {
	if o != nil && o.TenantContext.IsSet() {
		return true
	}

	return false
}

// SetTenantContext gets a reference to the given NullableString and assigns it to the TenantContext field.
func (o *BatchForecastSeries) SetTenantContext(v string) {
	o.TenantContext.Set(&v)
}
// SetTenantContextNil sets the value for TenantContext to be an explicit nil
func (o *BatchForecastSeries) SetTenantContextNil() {
	o.TenantContext.Set(nil)
}

// UnsetTenantContext ensures that no value is present for TenantContext, not even an explicit nil
func (o *BatchForecastSeries) UnsetTenantContext() {
	o.TenantContext.Unset()
}

// GetData returns the Data field value
func (o *BatchForecastSeries) GetData() []BatchForecastSeriesDataInner {
	if o == nil {
		var ret []BatchForecastSeriesDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetDataOk() ([]BatchForecastSeriesDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BatchForecastSeries) SetData(v []BatchForecastSeriesDataInner) {
	o.Data = v
}

// GetPeriods returns the Periods field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetPeriods() int32 {
	if o == nil || IsNil(o.Periods) {
		var ret int32
		return ret
	}
	return *o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetPeriodsOk() (*int32, bool) {
	if o == nil || IsNil(o.Periods) {
		return nil, false
	}
	return o.Periods, true
}

// HasPeriods returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasPeriods() bool {
	if o != nil && !IsNil(o.Periods) {
		return true
	}

	return false
}

// SetPeriods gets a reference to the given int32 and assigns it to the Periods field.
func (o *BatchForecastSeries) SetPeriods(v int32) {
	o.Periods = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *BatchForecastSeries) SetFrequency(v string) {
	o.Frequency = &v
}

// GetDataType returns the DataType field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetDataType() string {
	if o == nil || IsNil(o.DataType) {
		var ret string
		return ret
	}
	return *o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetDataTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DataType) {
		return nil, false
	}
	return o.DataType, true
}

// HasDataType returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasDataType() bool {
	if o != nil && !IsNil(o.DataType) {
		return true
	}

	return false
}

// SetDataType gets a reference to the given string and assigns it to the DataType field.
func (o *BatchForecastSeries) SetDataType(v string) {
	o.DataType = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *BatchForecastSeries) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *BatchForecastSeries) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetQuantiles returns the Quantiles field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetQuantiles() []float32 {
	if o == nil || IsNil(o.Quantiles) {
		var ret []float32
		return ret
	}
	return o.Quantiles
}

// GetQuantilesOk returns a tuple with the Quantiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetQuantilesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Quantiles) {
		return nil, false
	}
	return o.Quantiles, true
}

// HasQuantiles returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasQuantiles() bool {
	if o != nil && !IsNil(o.Quantiles) {
		return true
	}

	return false
}

// SetQuantiles gets a reference to the given []float32 and assigns it to the Quantiles field.
func (o *BatchForecastSeries) SetQuantiles(v []float32) {
	o.Quantiles = v
}

// GetValueBounds returns the ValueBounds field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetValueBounds() ValueBounds {
	if o == nil || IsNil(o.ValueBounds) {
		var ret ValueBounds
		return ret
	}
	return *o.ValueBounds
}

// GetValueBoundsOk returns a tuple with the ValueBounds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetValueBoundsOk() (*ValueBounds, bool) {
	if o == nil || IsNil(o.ValueBounds) {
		return nil, false
	}
	return o.ValueBounds, true
}

// HasValueBounds returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasValueBounds() bool {
	if o != nil && !IsNil(o.ValueBounds) {
		return true
	}

	return false
}

// SetValueBounds gets a reference to the given ValueBounds and assigns it to the ValueBounds field.
func (o *BatchForecastSeries) SetValueBounds(v ValueBounds) {
	o.ValueBounds = &v
}

// GetAdjustments returns the Adjustments field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetAdjustments() []AdjustmentsInner {
	if o == nil || IsNil(o.Adjustments) {
		var ret []AdjustmentsInner
		return ret
	}
	return o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetAdjustmentsOk() ([]AdjustmentsInner, bool) {
	if o == nil || IsNil(o.Adjustments) {
		return nil, false
	}
	return o.Adjustments, true
}

// HasAdjustments returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasAdjustments() bool {
	if o != nil && !IsNil(o.Adjustments) {
		return true
	}

	return false
}

// SetAdjustments gets a reference to the given []AdjustmentsInner and assigns it to the Adjustments field.
func (o *BatchForecastSeries) SetAdjustments(v []AdjustmentsInner) {
	o.Adjustments = v
}

// GetAccumulate returns the Accumulate field value if set, zero value otherwise.
func (o *BatchForecastSeries) GetAccumulate() AccumulateOptions {
	if o == nil || IsNil(o.Accumulate) {
		var ret AccumulateOptions
		return ret
	}
	return *o.Accumulate
}

// GetAccumulateOk returns a tuple with the Accumulate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastSeries) GetAccumulateOk() (*AccumulateOptions, bool) {
	if o == nil || IsNil(o.Accumulate) {
		return nil, false
	}
	return o.Accumulate, true
}

// HasAccumulate returns a boolean if a field has been set.
func (o *BatchForecastSeries) HasAccumulate() bool {
	if o != nil && !IsNil(o.Accumulate) {
		return true
	}

	return false
}

// SetAccumulate gets a reference to the given AccumulateOptions and assigns it to the Accumulate field.
func (o *BatchForecastSeries) SetAccumulate(v AccumulateOptions) {
	o.Accumulate = &v
}

func (o BatchForecastSeries) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchForecastSeries) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	if o.TenantContext.IsSet() {
		toSerialize["tenant_context"] = o.TenantContext.Get()
	}
	toSerialize["data"] = o.Data
	if !IsNil(o.Periods) {
		toSerialize["periods"] = o.Periods
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.DataType) {
		toSerialize["data_type"] = o.DataType
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	if !IsNil(o.Quantiles) {
		toSerialize["quantiles"] = o.Quantiles
	}
	if !IsNil(o.ValueBounds) {
		toSerialize["value_bounds"] = o.ValueBounds
	}
	if !IsNil(o.Adjustments) {
		toSerialize["adjustments"] = o.Adjustments
	}
	if !IsNil(o.Accumulate) {
		toSerialize["accumulate"] = o.Accumulate
	}
	return toSerialize, nil
}

func (o *BatchForecastSeries) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchForecastSeries := _BatchForecastSeries{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchForecastSeries)

	if err != nil {
		return err
	}

	*o = BatchForecastSeries(varBatchForecastSeries)

	return err
}

type NullableBatchForecastSeries struct {
	value *BatchForecastSeries
	isSet bool
}

func (v NullableBatchForecastSeries) Get() *BatchForecastSeries {
	return v.value
}

func (v *NullableBatchForecastSeries) Set(val *BatchForecastSeries) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchForecastSeries) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchForecastSeries) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchForecastSeries(val *BatchForecastSeries) *NullableBatchForecastSeries {
	return &NullableBatchForecastSeries{value: val, isSet: true}
}

func (v NullableBatchForecastSeries) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchForecastSeries) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


