/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ValidationFailedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationFailedResponse{}

// ValidationFailedResponse The validation-error shape shared by the grouped, batch and product-insights endpoints
type ValidationFailedResponse struct {
	Error *string `json:"error,omitempty"`
	Errors *map[string][]string `json:"errors,omitempty"`
	TimeTakenMs *float32 `json:"time_taken_ms,omitempty"`
}

// NewValidationFailedResponse instantiates a new ValidationFailedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationFailedResponse() *ValidationFailedResponse {
	this := ValidationFailedResponse{}
	return &this
}

// NewValidationFailedResponseWithDefaults instantiates a new ValidationFailedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationFailedResponseWithDefaults() *ValidationFailedResponse {
	this := ValidationFailedResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ValidationFailedResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationFailedResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ValidationFailedResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ValidationFailedResponse) SetError(v string) {
	o.Error = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ValidationFailedResponse) GetErrors() map[string][]string {
	if o == nil || IsNil(o.Errors) {
		var ret map[string][]string
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationFailedResponse) GetErrorsOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ValidationFailedResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string][]string and assigns it to the Errors field.
func (o *ValidationFailedResponse) SetErrors(v map[string][]string) {
	o.Errors = &v
}

// GetTimeTakenMs returns the TimeTakenMs field value if set, zero value otherwise.
func (o *ValidationFailedResponse) GetTimeTakenMs() float32 {
	if o == nil || IsNil(o.TimeTakenMs) {
		var ret float32
		return ret
	}
	return *o.TimeTakenMs
}

// GetTimeTakenMsOk returns a tuple with the TimeTakenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationFailedResponse) GetTimeTakenMsOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeTakenMs) {
		return nil, false
	}
	return o.TimeTakenMs, true
}

// HasTimeTakenMs returns a boolean if a field has been set.
func (o *ValidationFailedResponse) HasTimeTakenMs() bool {
	if o != nil && !IsNil(o.TimeTakenMs) {
		return true
	}

	return false
}

// SetTimeTakenMs gets a reference to the given float32 and assigns it to the TimeTakenMs field.
func (o *ValidationFailedResponse) SetTimeTakenMs(v float32) {
	o.TimeTakenMs = &v
}

func (o ValidationFailedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationFailedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.TimeTakenMs) {
		toSerialize["time_taken_ms"] = o.TimeTakenMs
	}
	return toSerialize, nil
}

type NullableValidationFailedResponse struct {
	value *ValidationFailedResponse
	isSet bool
}

func (v NullableValidationFailedResponse) Get() *ValidationFailedResponse {
	return v.value
}

func (v *NullableValidationFailedResponse) Set(val *ValidationFailedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationFailedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationFailedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationFailedResponse(val *ValidationFailedResponse) *NullableValidationFailedResponse {
	return &NullableValidationFailedResponse{value: val, isSet: true}
}

func (v NullableValidationFailedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationFailedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


