/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the GroupedForecastAccepted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedForecastAccepted{}

// GroupedForecastAccepted struct for GroupedForecastAccepted
type GroupedForecastAccepted struct {
	// Id to poll via GET /v2/forecast/grouped/{grouped_forecast_id}
	GroupedForecastId *string `json:"grouped_forecast_id,omitempty"`
	Status *string `json:"status,omitempty"`
	// Leaf series submitted
	SeriesCount *int32 `json:"series_count,omitempty"`
	// What will actually be forecast and reconciled — the leaves plus every derived aggregate and the total
	NodeCount *int32 `json:"node_count,omitempty"`
	Reconciliation *string `json:"reconciliation,omitempty"`
	TimeTakenMs *float32 `json:"time_taken_ms,omitempty"`
}

// NewGroupedForecastAccepted instantiates a new GroupedForecastAccepted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedForecastAccepted() *GroupedForecastAccepted {
	this := GroupedForecastAccepted{}
	return &this
}

// NewGroupedForecastAcceptedWithDefaults instantiates a new GroupedForecastAccepted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedForecastAcceptedWithDefaults() *GroupedForecastAccepted {
	this := GroupedForecastAccepted{}
	return &this
}

// GetGroupedForecastId returns the GroupedForecastId field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetGroupedForecastId() string {
	if o == nil || IsNil(o.GroupedForecastId) {
		var ret string
		return ret
	}
	return *o.GroupedForecastId
}

// GetGroupedForecastIdOk returns a tuple with the GroupedForecastId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetGroupedForecastIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupedForecastId) {
		return nil, false
	}
	return o.GroupedForecastId, true
}

// HasGroupedForecastId returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasGroupedForecastId() bool {
	if o != nil && !IsNil(o.GroupedForecastId) {
		return true
	}

	return false
}

// SetGroupedForecastId gets a reference to the given string and assigns it to the GroupedForecastId field.
func (o *GroupedForecastAccepted) SetGroupedForecastId(v string) {
	o.GroupedForecastId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GroupedForecastAccepted) SetStatus(v string) {
	o.Status = &v
}

// GetSeriesCount returns the SeriesCount field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetSeriesCount() int32 {
	if o == nil || IsNil(o.SeriesCount) {
		var ret int32
		return ret
	}
	return *o.SeriesCount
}

// GetSeriesCountOk returns a tuple with the SeriesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetSeriesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SeriesCount) {
		return nil, false
	}
	return o.SeriesCount, true
}

// HasSeriesCount returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasSeriesCount() bool {
	if o != nil && !IsNil(o.SeriesCount) {
		return true
	}

	return false
}

// SetSeriesCount gets a reference to the given int32 and assigns it to the SeriesCount field.
func (o *GroupedForecastAccepted) SetSeriesCount(v int32) {
	o.SeriesCount = &v
}

// GetNodeCount returns the NodeCount field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetNodeCount() int32 {
	if o == nil || IsNil(o.NodeCount) {
		var ret int32
		return ret
	}
	return *o.NodeCount
}

// GetNodeCountOk returns a tuple with the NodeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetNodeCountOk() (*int32, bool) {
	if o == nil || IsNil(o.NodeCount) {
		return nil, false
	}
	return o.NodeCount, true
}

// HasNodeCount returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasNodeCount() bool {
	if o != nil && !IsNil(o.NodeCount) {
		return true
	}

	return false
}

// SetNodeCount gets a reference to the given int32 and assigns it to the NodeCount field.
func (o *GroupedForecastAccepted) SetNodeCount(v int32) {
	o.NodeCount = &v
}

// GetReconciliation returns the Reconciliation field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetReconciliation() string {
	if o == nil || IsNil(o.Reconciliation) {
		var ret string
		return ret
	}
	return *o.Reconciliation
}

// GetReconciliationOk returns a tuple with the Reconciliation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetReconciliationOk() (*string, bool) {
	if o == nil || IsNil(o.Reconciliation) {
		return nil, false
	}
	return o.Reconciliation, true
}

// HasReconciliation returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasReconciliation() bool {
	if o != nil && !IsNil(o.Reconciliation) {
		return true
	}

	return false
}

// SetReconciliation gets a reference to the given string and assigns it to the Reconciliation field.
func (o *GroupedForecastAccepted) SetReconciliation(v string) {
	o.Reconciliation = &v
}

// GetTimeTakenMs returns the TimeTakenMs field value if set, zero value otherwise.
func (o *GroupedForecastAccepted) GetTimeTakenMs() float32 {
	if o == nil || IsNil(o.TimeTakenMs) {
		var ret float32
		return ret
	}
	return *o.TimeTakenMs
}

// GetTimeTakenMsOk returns a tuple with the TimeTakenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastAccepted) GetTimeTakenMsOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeTakenMs) {
		return nil, false
	}
	return o.TimeTakenMs, true
}

// HasTimeTakenMs returns a boolean if a field has been set.
func (o *GroupedForecastAccepted) HasTimeTakenMs() bool {
	if o != nil && !IsNil(o.TimeTakenMs) {
		return true
	}

	return false
}

// SetTimeTakenMs gets a reference to the given float32 and assigns it to the TimeTakenMs field.
func (o *GroupedForecastAccepted) SetTimeTakenMs(v float32) {
	o.TimeTakenMs = &v
}

func (o GroupedForecastAccepted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedForecastAccepted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupedForecastId) {
		toSerialize["grouped_forecast_id"] = o.GroupedForecastId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SeriesCount) {
		toSerialize["series_count"] = o.SeriesCount
	}
	if !IsNil(o.NodeCount) {
		toSerialize["node_count"] = o.NodeCount
	}
	if !IsNil(o.Reconciliation) {
		toSerialize["reconciliation"] = o.Reconciliation
	}
	if !IsNil(o.TimeTakenMs) {
		toSerialize["time_taken_ms"] = o.TimeTakenMs
	}
	return toSerialize, nil
}

type NullableGroupedForecastAccepted struct {
	value *GroupedForecastAccepted
	isSet bool
}

func (v NullableGroupedForecastAccepted) Get() *GroupedForecastAccepted {
	return v.value
}

func (v *NullableGroupedForecastAccepted) Set(val *GroupedForecastAccepted) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedForecastAccepted) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedForecastAccepted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedForecastAccepted(val *GroupedForecastAccepted) *NullableGroupedForecastAccepted {
	return &NullableGroupedForecastAccepted{value: val, isSet: true}
}

func (v NullableGroupedForecastAccepted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedForecastAccepted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


