/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.1.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the BatchForecastRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchForecastRequest{}

// BatchForecastRequest Either `series` (inline) or `file_key` (file-based, from /v2/batch/forecast/presign) is required. Every other field is a request-level default that each series inherits unless it declares its own override — except `model`, which is request-level only. `confidence_level` is accepted as an alias for `confidence`; if both are sent, `confidence` wins. 
type BatchForecastRequest struct {
	// The series to forecast — up to 100,000 per call on a paid plan, 10 on the free tier
	Series []BatchForecastSeries `json:"series,omitempty"`
	// Instead of inline `series` — the key returned by /v2/batch/forecast/presign, after uploading a JSON file of the same shape as this request body (an object with a `series` array). Series from a file are validated as they are streamed: an invalid series fails that series, not the whole batch. 
	FileKey *string `json:"file_key,omitempty"`
	// Default forecast horizon for series that don't set their own
	Periods *int32 `json:"periods,omitempty"`
	// Default data frequency
	Frequency *string `json:"frequency,omitempty"`
	// Default data type
	DataType *string `json:"data_type,omitempty"`
	// Forecasting engine for the whole batch (request-level only)
	Model *string `json:"model,omitempty"`
	// Default confidence level for prediction intervals
	Confidence *float32 `json:"confidence,omitempty"`
	// Alias for `confidence`
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Quantiles []float32 `json:"quantiles,omitempty"`
	ValueBounds *ValueBounds `json:"value_bounds,omitempty"`
	// What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Adjustments []AdjustmentsInner `json:"adjustments,omitempty"`
	Accumulate *AccumulateOptions `json:"accumulate,omitempty"`
}

// NewBatchForecastRequest instantiates a new BatchForecastRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchForecastRequest() *BatchForecastRequest {
	this := BatchForecastRequest{}
	var periods int32 = 6
	this.Periods = &periods
	var model string = "standard"
	this.Model = &model
	var confidence float32 = 0.8
	this.Confidence = &confidence
	return &this
}

// NewBatchForecastRequestWithDefaults instantiates a new BatchForecastRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchForecastRequestWithDefaults() *BatchForecastRequest {
	this := BatchForecastRequest{}
	var periods int32 = 6
	this.Periods = &periods
	var model string = "standard"
	this.Model = &model
	var confidence float32 = 0.8
	this.Confidence = &confidence
	return &this
}

// GetSeries returns the Series field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetSeries() []BatchForecastSeries {
	if o == nil || IsNil(o.Series) {
		var ret []BatchForecastSeries
		return ret
	}
	return o.Series
}

// GetSeriesOk returns a tuple with the Series field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetSeriesOk() ([]BatchForecastSeries, bool) {
	if o == nil || IsNil(o.Series) {
		return nil, false
	}
	return o.Series, true
}

// HasSeries returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasSeries() bool {
	if o != nil && !IsNil(o.Series) {
		return true
	}

	return false
}

// SetSeries gets a reference to the given []BatchForecastSeries and assigns it to the Series field.
func (o *BatchForecastRequest) SetSeries(v []BatchForecastSeries) {
	o.Series = v
}

// GetFileKey returns the FileKey field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetFileKey() string {
	if o == nil || IsNil(o.FileKey) {
		var ret string
		return ret
	}
	return *o.FileKey
}

// GetFileKeyOk returns a tuple with the FileKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetFileKeyOk() (*string, bool) {
	if o == nil || IsNil(o.FileKey) {
		return nil, false
	}
	return o.FileKey, true
}

// HasFileKey returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasFileKey() bool {
	if o != nil && !IsNil(o.FileKey) {
		return true
	}

	return false
}

// SetFileKey gets a reference to the given string and assigns it to the FileKey field.
func (o *BatchForecastRequest) SetFileKey(v string) {
	o.FileKey = &v
}

// GetPeriods returns the Periods field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetPeriods() int32 {
	if o == nil || IsNil(o.Periods) {
		var ret int32
		return ret
	}
	return *o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetPeriodsOk() (*int32, bool) {
	if o == nil || IsNil(o.Periods) {
		return nil, false
	}
	return o.Periods, true
}

// HasPeriods returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasPeriods() bool {
	if o != nil && !IsNil(o.Periods) {
		return true
	}

	return false
}

// SetPeriods gets a reference to the given int32 and assigns it to the Periods field.
func (o *BatchForecastRequest) SetPeriods(v int32) {
	o.Periods = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *BatchForecastRequest) SetFrequency(v string) {
	o.Frequency = &v
}

// GetDataType returns the DataType field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetDataType() string {
	if o == nil || IsNil(o.DataType) {
		var ret string
		return ret
	}
	return *o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetDataTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DataType) {
		return nil, false
	}
	return o.DataType, true
}

// HasDataType returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasDataType() bool {
	if o != nil && !IsNil(o.DataType) {
		return true
	}

	return false
}

// SetDataType gets a reference to the given string and assigns it to the DataType field.
func (o *BatchForecastRequest) SetDataType(v string) {
	o.DataType = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *BatchForecastRequest) SetModel(v string) {
	o.Model = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *BatchForecastRequest) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *BatchForecastRequest) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetQuantiles returns the Quantiles field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetQuantiles() []float32 {
	if o == nil || IsNil(o.Quantiles) {
		var ret []float32
		return ret
	}
	return o.Quantiles
}

// GetQuantilesOk returns a tuple with the Quantiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetQuantilesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Quantiles) {
		return nil, false
	}
	return o.Quantiles, true
}

// HasQuantiles returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasQuantiles() bool {
	if o != nil && !IsNil(o.Quantiles) {
		return true
	}

	return false
}

// SetQuantiles gets a reference to the given []float32 and assigns it to the Quantiles field.
func (o *BatchForecastRequest) SetQuantiles(v []float32) {
	o.Quantiles = v
}

// GetValueBounds returns the ValueBounds field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetValueBounds() ValueBounds {
	if o == nil || IsNil(o.ValueBounds) {
		var ret ValueBounds
		return ret
	}
	return *o.ValueBounds
}

// GetValueBoundsOk returns a tuple with the ValueBounds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetValueBoundsOk() (*ValueBounds, bool) {
	if o == nil || IsNil(o.ValueBounds) {
		return nil, false
	}
	return o.ValueBounds, true
}

// HasValueBounds returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasValueBounds() bool {
	if o != nil && !IsNil(o.ValueBounds) {
		return true
	}

	return false
}

// SetValueBounds gets a reference to the given ValueBounds and assigns it to the ValueBounds field.
func (o *BatchForecastRequest) SetValueBounds(v ValueBounds) {
	o.ValueBounds = &v
}

// GetAdjustments returns the Adjustments field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetAdjustments() []AdjustmentsInner {
	if o == nil || IsNil(o.Adjustments) {
		var ret []AdjustmentsInner
		return ret
	}
	return o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetAdjustmentsOk() ([]AdjustmentsInner, bool) {
	if o == nil || IsNil(o.Adjustments) {
		return nil, false
	}
	return o.Adjustments, true
}

// HasAdjustments returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasAdjustments() bool {
	if o != nil && !IsNil(o.Adjustments) {
		return true
	}

	return false
}

// SetAdjustments gets a reference to the given []AdjustmentsInner and assigns it to the Adjustments field.
func (o *BatchForecastRequest) SetAdjustments(v []AdjustmentsInner) {
	o.Adjustments = v
}

// GetAccumulate returns the Accumulate field value if set, zero value otherwise.
func (o *BatchForecastRequest) GetAccumulate() AccumulateOptions {
	if o == nil || IsNil(o.Accumulate) {
		var ret AccumulateOptions
		return ret
	}
	return *o.Accumulate
}

// GetAccumulateOk returns a tuple with the Accumulate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastRequest) GetAccumulateOk() (*AccumulateOptions, bool) {
	if o == nil || IsNil(o.Accumulate) {
		return nil, false
	}
	return o.Accumulate, true
}

// HasAccumulate returns a boolean if a field has been set.
func (o *BatchForecastRequest) HasAccumulate() bool {
	if o != nil && !IsNil(o.Accumulate) {
		return true
	}

	return false
}

// SetAccumulate gets a reference to the given AccumulateOptions and assigns it to the Accumulate field.
func (o *BatchForecastRequest) SetAccumulate(v AccumulateOptions) {
	o.Accumulate = &v
}

func (o BatchForecastRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchForecastRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Series) {
		toSerialize["series"] = o.Series
	}
	if !IsNil(o.FileKey) {
		toSerialize["file_key"] = o.FileKey
	}
	if !IsNil(o.Periods) {
		toSerialize["periods"] = o.Periods
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.DataType) {
		toSerialize["data_type"] = o.DataType
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	if !IsNil(o.Quantiles) {
		toSerialize["quantiles"] = o.Quantiles
	}
	if !IsNil(o.ValueBounds) {
		toSerialize["value_bounds"] = o.ValueBounds
	}
	if !IsNil(o.Adjustments) {
		toSerialize["adjustments"] = o.Adjustments
	}
	if !IsNil(o.Accumulate) {
		toSerialize["accumulate"] = o.Accumulate
	}
	return toSerialize, nil
}

type NullableBatchForecastRequest struct {
	value *BatchForecastRequest
	isSet bool
}

func (v NullableBatchForecastRequest) Get() *BatchForecastRequest {
	return v.value
}

func (v *NullableBatchForecastRequest) Set(val *BatchForecastRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchForecastRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchForecastRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchForecastRequest(val *BatchForecastRequest) *NullableBatchForecastRequest {
	return &NullableBatchForecastRequest{value: val, isSet: true}
}

func (v NullableBatchForecastRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchForecastRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


