/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForecastRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastRequest{}

// ForecastRequest struct for ForecastRequest
type ForecastRequest struct {
	// SKU, Product ID, or other identifier for the data series
	Identifier string `json:"identifier"`
	// Optional segmentation dimension. A series is identified by the pair identifier + tenant_context, so \"mrr\" on \"plan-pro\" and \"mrr\" on \"plan-free\" are two independent series, each with its own history and accuracy tracking. Despite the name it isn't only for multi-tenancy — use it for any slice: plan, region, store, channel, cohort, device type. 
	TenantContext NullableString `json:"tenant_context,omitempty"`
	// Data frequency: - H: Hourly - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
	Frequency string `json:"frequency"`
	// Optional start date for the forecast
	StartDate NullableString `json:"start_date,omitempty"`
	// Type of data (e.g., sales, demand, inventory, web_traffic)
	DataType string `json:"data_type"`
	// Number of periods to forecast
	Periods int32 `json:"periods"`
	// Which forecasting engine to use. The advanced variants and ensemble provide higher accuracy at a higher usage cost than standard. 
	Model *string `json:"model,omitempty"`
	// Confidence level for the prediction interval. Note that 0.80 is the widest band the foundation models (advanced-quantized, advanced-patched, ensemble) produce natively — for genuinely distinct levels beyond that, request a quantile fan via `quantiles` instead of repeating the call at several confidence levels. 
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Quantiles []float32 `json:"quantiles,omitempty"`
	ValueBounds *ValueBounds `json:"value_bounds,omitempty"`
	// What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Adjustments []AdjustmentsInner `json:"adjustments,omitempty"`
	Accumulate *AccumulateOptions `json:"accumulate,omitempty"`
	// Which back-testing error metric decides the winning model when candidates are compared: - auto: combined for demand/sales/inventory, sMAPE otherwise (default) - combined: 0.6·MASE + 0.4·sMAPE — balances accuracy and trend capture - mase: Mean Absolute Scaled Error — accuracy relative to a naive forecast - smape: Symmetric Mean Absolute Percentage Error 
	SelectionMetric NullableString `json:"selection_metric,omitempty"`
	// Historical time series data
	Data []ForecastRequestDataInner `json:"data"`
}

type _ForecastRequest ForecastRequest

// NewForecastRequest instantiates a new ForecastRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastRequest(identifier string, frequency string, dataType string, periods int32, data []ForecastRequestDataInner) *ForecastRequest {
	this := ForecastRequest{}
	this.Identifier = identifier
	this.Frequency = frequency
	this.DataType = dataType
	this.Periods = periods
	var model string = "standard"
	this.Model = &model
	var confidenceLevel float32 = 0.8
	this.ConfidenceLevel = &confidenceLevel
	this.Data = data
	return &this
}

// NewForecastRequestWithDefaults instantiates a new ForecastRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastRequestWithDefaults() *ForecastRequest {
	this := ForecastRequest{}
	var model string = "standard"
	this.Model = &model
	var confidenceLevel float32 = 0.8
	this.ConfidenceLevel = &confidenceLevel
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *ForecastRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ForecastRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTenantContext returns the TenantContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ForecastRequest) GetTenantContext() string {
	if o == nil || IsNil(o.TenantContext.Get()) {
		var ret string
		return ret
	}
	return *o.TenantContext.Get()
}

// GetTenantContextOk returns a tuple with the TenantContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ForecastRequest) GetTenantContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantContext.Get(), o.TenantContext.IsSet()
}

// HasTenantContext returns a boolean if a field has been set.
func (o *ForecastRequest) HasTenantContext() bool {
	if o != nil && o.TenantContext.IsSet() {
		return true
	}

	return false
}

// SetTenantContext gets a reference to the given NullableString and assigns it to the TenantContext field.
func (o *ForecastRequest) SetTenantContext(v string) {
	o.TenantContext.Set(&v)
}
// SetTenantContextNil sets the value for TenantContext to be an explicit nil
func (o *ForecastRequest) SetTenantContextNil() {
	o.TenantContext.Set(nil)
}

// UnsetTenantContext ensures that no value is present for TenantContext, not even an explicit nil
func (o *ForecastRequest) UnsetTenantContext() {
	o.TenantContext.Unset()
}

// GetFrequency returns the Frequency field value
func (o *ForecastRequest) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *ForecastRequest) SetFrequency(v string) {
	o.Frequency = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ForecastRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ForecastRequest) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *ForecastRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *ForecastRequest) SetStartDate(v string) {
	o.StartDate.Set(&v)
}
// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *ForecastRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *ForecastRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetDataType returns the DataType field value
func (o *ForecastRequest) GetDataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataType, true
}

// SetDataType sets field value
func (o *ForecastRequest) SetDataType(v string) {
	o.DataType = v
}

// GetPeriods returns the Periods field value
func (o *ForecastRequest) GetPeriods() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetPeriodsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Periods, true
}

// SetPeriods sets field value
func (o *ForecastRequest) SetPeriods(v int32) {
	o.Periods = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *ForecastRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *ForecastRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *ForecastRequest) SetModel(v string) {
	o.Model = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *ForecastRequest) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *ForecastRequest) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *ForecastRequest) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetQuantiles returns the Quantiles field value if set, zero value otherwise.
func (o *ForecastRequest) GetQuantiles() []float32 {
	if o == nil || IsNil(o.Quantiles) {
		var ret []float32
		return ret
	}
	return o.Quantiles
}

// GetQuantilesOk returns a tuple with the Quantiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetQuantilesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Quantiles) {
		return nil, false
	}
	return o.Quantiles, true
}

// HasQuantiles returns a boolean if a field has been set.
func (o *ForecastRequest) HasQuantiles() bool {
	if o != nil && !IsNil(o.Quantiles) {
		return true
	}

	return false
}

// SetQuantiles gets a reference to the given []float32 and assigns it to the Quantiles field.
func (o *ForecastRequest) SetQuantiles(v []float32) {
	o.Quantiles = v
}

// GetValueBounds returns the ValueBounds field value if set, zero value otherwise.
func (o *ForecastRequest) GetValueBounds() ValueBounds {
	if o == nil || IsNil(o.ValueBounds) {
		var ret ValueBounds
		return ret
	}
	return *o.ValueBounds
}

// GetValueBoundsOk returns a tuple with the ValueBounds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetValueBoundsOk() (*ValueBounds, bool) {
	if o == nil || IsNil(o.ValueBounds) {
		return nil, false
	}
	return o.ValueBounds, true
}

// HasValueBounds returns a boolean if a field has been set.
func (o *ForecastRequest) HasValueBounds() bool {
	if o != nil && !IsNil(o.ValueBounds) {
		return true
	}

	return false
}

// SetValueBounds gets a reference to the given ValueBounds and assigns it to the ValueBounds field.
func (o *ForecastRequest) SetValueBounds(v ValueBounds) {
	o.ValueBounds = &v
}

// GetAdjustments returns the Adjustments field value if set, zero value otherwise.
func (o *ForecastRequest) GetAdjustments() []AdjustmentsInner {
	if o == nil || IsNil(o.Adjustments) {
		var ret []AdjustmentsInner
		return ret
	}
	return o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetAdjustmentsOk() ([]AdjustmentsInner, bool) {
	if o == nil || IsNil(o.Adjustments) {
		return nil, false
	}
	return o.Adjustments, true
}

// HasAdjustments returns a boolean if a field has been set.
func (o *ForecastRequest) HasAdjustments() bool {
	if o != nil && !IsNil(o.Adjustments) {
		return true
	}

	return false
}

// SetAdjustments gets a reference to the given []AdjustmentsInner and assigns it to the Adjustments field.
func (o *ForecastRequest) SetAdjustments(v []AdjustmentsInner) {
	o.Adjustments = v
}

// GetAccumulate returns the Accumulate field value if set, zero value otherwise.
func (o *ForecastRequest) GetAccumulate() AccumulateOptions {
	if o == nil || IsNil(o.Accumulate) {
		var ret AccumulateOptions
		return ret
	}
	return *o.Accumulate
}

// GetAccumulateOk returns a tuple with the Accumulate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetAccumulateOk() (*AccumulateOptions, bool) {
	if o == nil || IsNil(o.Accumulate) {
		return nil, false
	}
	return o.Accumulate, true
}

// HasAccumulate returns a boolean if a field has been set.
func (o *ForecastRequest) HasAccumulate() bool {
	if o != nil && !IsNil(o.Accumulate) {
		return true
	}

	return false
}

// SetAccumulate gets a reference to the given AccumulateOptions and assigns it to the Accumulate field.
func (o *ForecastRequest) SetAccumulate(v AccumulateOptions) {
	o.Accumulate = &v
}

// GetSelectionMetric returns the SelectionMetric field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ForecastRequest) GetSelectionMetric() string {
	if o == nil || IsNil(o.SelectionMetric.Get()) {
		var ret string
		return ret
	}
	return *o.SelectionMetric.Get()
}

// GetSelectionMetricOk returns a tuple with the SelectionMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ForecastRequest) GetSelectionMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectionMetric.Get(), o.SelectionMetric.IsSet()
}

// HasSelectionMetric returns a boolean if a field has been set.
func (o *ForecastRequest) HasSelectionMetric() bool {
	if o != nil && o.SelectionMetric.IsSet() {
		return true
	}

	return false
}

// SetSelectionMetric gets a reference to the given NullableString and assigns it to the SelectionMetric field.
func (o *ForecastRequest) SetSelectionMetric(v string) {
	o.SelectionMetric.Set(&v)
}
// SetSelectionMetricNil sets the value for SelectionMetric to be an explicit nil
func (o *ForecastRequest) SetSelectionMetricNil() {
	o.SelectionMetric.Set(nil)
}

// UnsetSelectionMetric ensures that no value is present for SelectionMetric, not even an explicit nil
func (o *ForecastRequest) UnsetSelectionMetric() {
	o.SelectionMetric.Unset()
}

// GetData returns the Data field value
func (o *ForecastRequest) GetData() []ForecastRequestDataInner {
	if o == nil {
		var ret []ForecastRequestDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ForecastRequest) GetDataOk() ([]ForecastRequestDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ForecastRequest) SetData(v []ForecastRequestDataInner) {
	o.Data = v
}

func (o ForecastRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	if o.TenantContext.IsSet() {
		toSerialize["tenant_context"] = o.TenantContext.Get()
	}
	toSerialize["frequency"] = o.Frequency
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	toSerialize["data_type"] = o.DataType
	toSerialize["periods"] = o.Periods
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	if !IsNil(o.Quantiles) {
		toSerialize["quantiles"] = o.Quantiles
	}
	if !IsNil(o.ValueBounds) {
		toSerialize["value_bounds"] = o.ValueBounds
	}
	if !IsNil(o.Adjustments) {
		toSerialize["adjustments"] = o.Adjustments
	}
	if !IsNil(o.Accumulate) {
		toSerialize["accumulate"] = o.Accumulate
	}
	if o.SelectionMetric.IsSet() {
		toSerialize["selection_metric"] = o.SelectionMetric.Get()
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ForecastRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"frequency",
		"data_type",
		"periods",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForecastRequest := _ForecastRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForecastRequest)

	if err != nil {
		return err
	}

	*o = ForecastRequest(varForecastRequest)

	return err
}

type NullableForecastRequest struct {
	value *ForecastRequest
	isSet bool
}

func (v NullableForecastRequest) Get() *ForecastRequest {
	return v.value
}

func (v *NullableForecastRequest) Set(val *ForecastRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastRequest(val *ForecastRequest) *NullableForecastRequest {
	return &NullableForecastRequest{value: val, isSet: true}
}

func (v NullableForecastRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


