/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AutoSelectionScoresValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoSelectionScoresValue{}

// AutoSelectionScoresValue struct for AutoSelectionScoresValue
type AutoSelectionScoresValue struct {
	// Realized MASE on this identifier (lower is better; < 1 beats a naive forecast)
	Mase NullableFloat32 `json:"mase,omitempty"`
	// Matured forecast/actual pairs behind the score
	MatchedPeriods *int32 `json:"matched_periods,omitempty"`
	// Separate forecast runs the evidence spans
	ForecastRuns *int32 `json:"forecast_runs,omitempty"`
}

// NewAutoSelectionScoresValue instantiates a new AutoSelectionScoresValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoSelectionScoresValue() *AutoSelectionScoresValue {
	this := AutoSelectionScoresValue{}
	return &this
}

// NewAutoSelectionScoresValueWithDefaults instantiates a new AutoSelectionScoresValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoSelectionScoresValueWithDefaults() *AutoSelectionScoresValue {
	this := AutoSelectionScoresValue{}
	return &this
}

// GetMase returns the Mase field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoSelectionScoresValue) GetMase() float32 {
	if o == nil || IsNil(o.Mase.Get()) {
		var ret float32
		return ret
	}
	return *o.Mase.Get()
}

// GetMaseOk returns a tuple with the Mase field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoSelectionScoresValue) GetMaseOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mase.Get(), o.Mase.IsSet()
}

// HasMase returns a boolean if a field has been set.
func (o *AutoSelectionScoresValue) HasMase() bool {
	if o != nil && o.Mase.IsSet() {
		return true
	}

	return false
}

// SetMase gets a reference to the given NullableFloat32 and assigns it to the Mase field.
func (o *AutoSelectionScoresValue) SetMase(v float32) {
	o.Mase.Set(&v)
}
// SetMaseNil sets the value for Mase to be an explicit nil
func (o *AutoSelectionScoresValue) SetMaseNil() {
	o.Mase.Set(nil)
}

// UnsetMase ensures that no value is present for Mase, not even an explicit nil
func (o *AutoSelectionScoresValue) UnsetMase() {
	o.Mase.Unset()
}

// GetMatchedPeriods returns the MatchedPeriods field value if set, zero value otherwise.
func (o *AutoSelectionScoresValue) GetMatchedPeriods() int32 {
	if o == nil || IsNil(o.MatchedPeriods) {
		var ret int32
		return ret
	}
	return *o.MatchedPeriods
}

// GetMatchedPeriodsOk returns a tuple with the MatchedPeriods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoSelectionScoresValue) GetMatchedPeriodsOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchedPeriods) {
		return nil, false
	}
	return o.MatchedPeriods, true
}

// HasMatchedPeriods returns a boolean if a field has been set.
func (o *AutoSelectionScoresValue) HasMatchedPeriods() bool {
	if o != nil && !IsNil(o.MatchedPeriods) {
		return true
	}

	return false
}

// SetMatchedPeriods gets a reference to the given int32 and assigns it to the MatchedPeriods field.
func (o *AutoSelectionScoresValue) SetMatchedPeriods(v int32) {
	o.MatchedPeriods = &v
}

// GetForecastRuns returns the ForecastRuns field value if set, zero value otherwise.
func (o *AutoSelectionScoresValue) GetForecastRuns() int32 {
	if o == nil || IsNil(o.ForecastRuns) {
		var ret int32
		return ret
	}
	return *o.ForecastRuns
}

// GetForecastRunsOk returns a tuple with the ForecastRuns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoSelectionScoresValue) GetForecastRunsOk() (*int32, bool) {
	if o == nil || IsNil(o.ForecastRuns) {
		return nil, false
	}
	return o.ForecastRuns, true
}

// HasForecastRuns returns a boolean if a field has been set.
func (o *AutoSelectionScoresValue) HasForecastRuns() bool {
	if o != nil && !IsNil(o.ForecastRuns) {
		return true
	}

	return false
}

// SetForecastRuns gets a reference to the given int32 and assigns it to the ForecastRuns field.
func (o *AutoSelectionScoresValue) SetForecastRuns(v int32) {
	o.ForecastRuns = &v
}

func (o AutoSelectionScoresValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoSelectionScoresValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Mase.IsSet() {
		toSerialize["mase"] = o.Mase.Get()
	}
	if !IsNil(o.MatchedPeriods) {
		toSerialize["matched_periods"] = o.MatchedPeriods
	}
	if !IsNil(o.ForecastRuns) {
		toSerialize["forecast_runs"] = o.ForecastRuns
	}
	return toSerialize, nil
}

type NullableAutoSelectionScoresValue struct {
	value *AutoSelectionScoresValue
	isSet bool
}

func (v NullableAutoSelectionScoresValue) Get() *AutoSelectionScoresValue {
	return v.value
}

func (v *NullableAutoSelectionScoresValue) Set(val *AutoSelectionScoresValue) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoSelectionScoresValue) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoSelectionScoresValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoSelectionScoresValue(val *AutoSelectionScoresValue) *NullableAutoSelectionScoresValue {
	return &NullableAutoSelectionScoresValue{value: val, isSet: true}
}

func (v NullableAutoSelectionScoresValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoSelectionScoresValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


