/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ValidationErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponse{}

// ValidationErrorResponse struct for ValidationErrorResponse
type ValidationErrorResponse struct {
	Message *string `json:"message,omitempty"`
	Errors *map[string][]string `json:"errors,omitempty"`
}

// NewValidationErrorResponse instantiates a new ValidationErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponse() *ValidationErrorResponse {
	this := ValidationErrorResponse{}
	return &this
}

// NewValidationErrorResponseWithDefaults instantiates a new ValidationErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseWithDefaults() *ValidationErrorResponse {
	this := ValidationErrorResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ValidationErrorResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ValidationErrorResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ValidationErrorResponse) SetMessage(v string) {
	o.Message = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ValidationErrorResponse) GetErrors() map[string][]string {
	if o == nil || IsNil(o.Errors) {
		var ret map[string][]string
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponse) GetErrorsOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ValidationErrorResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string][]string and assigns it to the Errors field.
func (o *ValidationErrorResponse) SetErrors(v map[string][]string) {
	o.Errors = &v
}

func (o ValidationErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableValidationErrorResponse struct {
	value *ValidationErrorResponse
	isSet bool
}

func (v NullableValidationErrorResponse) Get() *ValidationErrorResponse {
	return v.value
}

func (v *NullableValidationErrorResponse) Set(val *ValidationErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponse(val *ValidationErrorResponse) *NullableValidationErrorResponse {
	return &NullableValidationErrorResponse{value: val, isSet: true}
}

func (v NullableValidationErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


