/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductInsightsBatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsBatchRequest{}

// ProductInsightsBatchRequest struct for ProductInsightsBatchRequest
type ProductInsightsBatchRequest struct {
	// One entry per product, each the same shape as a single /v2/product-insights request
	Series []ProductInsightsRequest `json:"series"`
	// Existing batch identifier to append this upload to, for submitting one logical batch in chunks
	Batch *string `json:"batch,omitempty"`
	// Total number of parts the batch will consist of, when submitting in chunks
	Parts *int32 `json:"parts,omitempty"`
}

type _ProductInsightsBatchRequest ProductInsightsBatchRequest

// NewProductInsightsBatchRequest instantiates a new ProductInsightsBatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsBatchRequest(series []ProductInsightsRequest) *ProductInsightsBatchRequest {
	this := ProductInsightsBatchRequest{}
	this.Series = series
	return &this
}

// NewProductInsightsBatchRequestWithDefaults instantiates a new ProductInsightsBatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsBatchRequestWithDefaults() *ProductInsightsBatchRequest {
	this := ProductInsightsBatchRequest{}
	return &this
}

// GetSeries returns the Series field value
func (o *ProductInsightsBatchRequest) GetSeries() []ProductInsightsRequest {
	if o == nil {
		var ret []ProductInsightsRequest
		return ret
	}

	return o.Series
}

// GetSeriesOk returns a tuple with the Series field value
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchRequest) GetSeriesOk() ([]ProductInsightsRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Series, true
}

// SetSeries sets field value
func (o *ProductInsightsBatchRequest) SetSeries(v []ProductInsightsRequest) {
	o.Series = v
}

// GetBatch returns the Batch field value if set, zero value otherwise.
func (o *ProductInsightsBatchRequest) GetBatch() string {
	if o == nil || IsNil(o.Batch) {
		var ret string
		return ret
	}
	return *o.Batch
}

// GetBatchOk returns a tuple with the Batch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchRequest) GetBatchOk() (*string, bool) {
	if o == nil || IsNil(o.Batch) {
		return nil, false
	}
	return o.Batch, true
}

// HasBatch returns a boolean if a field has been set.
func (o *ProductInsightsBatchRequest) HasBatch() bool {
	if o != nil && !IsNil(o.Batch) {
		return true
	}

	return false
}

// SetBatch gets a reference to the given string and assigns it to the Batch field.
func (o *ProductInsightsBatchRequest) SetBatch(v string) {
	o.Batch = &v
}

// GetParts returns the Parts field value if set, zero value otherwise.
func (o *ProductInsightsBatchRequest) GetParts() int32 {
	if o == nil || IsNil(o.Parts) {
		var ret int32
		return ret
	}
	return *o.Parts
}

// GetPartsOk returns a tuple with the Parts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchRequest) GetPartsOk() (*int32, bool) {
	if o == nil || IsNil(o.Parts) {
		return nil, false
	}
	return o.Parts, true
}

// HasParts returns a boolean if a field has been set.
func (o *ProductInsightsBatchRequest) HasParts() bool {
	if o != nil && !IsNil(o.Parts) {
		return true
	}

	return false
}

// SetParts gets a reference to the given int32 and assigns it to the Parts field.
func (o *ProductInsightsBatchRequest) SetParts(v int32) {
	o.Parts = &v
}

func (o ProductInsightsBatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsBatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["series"] = o.Series
	if !IsNil(o.Batch) {
		toSerialize["batch"] = o.Batch
	}
	if !IsNil(o.Parts) {
		toSerialize["parts"] = o.Parts
	}
	return toSerialize, nil
}

func (o *ProductInsightsBatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"series",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductInsightsBatchRequest := _ProductInsightsBatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductInsightsBatchRequest)

	if err != nil {
		return err
	}

	*o = ProductInsightsBatchRequest(varProductInsightsBatchRequest)

	return err
}

type NullableProductInsightsBatchRequest struct {
	value *ProductInsightsBatchRequest
	isSet bool
}

func (v NullableProductInsightsBatchRequest) Get() *ProductInsightsBatchRequest {
	return v.value
}

func (v *NullableProductInsightsBatchRequest) Set(val *ProductInsightsBatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsBatchRequest(val *ProductInsightsBatchRequest) *NullableProductInsightsBatchRequest {
	return &NullableProductInsightsBatchRequest{value: val, isSet: true}
}

func (v NullableProductInsightsBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


