/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"time"
)

// checks if the BatchForecastStatusResponsePartsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchForecastStatusResponsePartsInner{}

// BatchForecastStatusResponsePartsInner struct for BatchForecastStatusResponsePartsInner
type BatchForecastStatusResponsePartsInner struct {
	Status *string `json:"status,omitempty"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
}

// NewBatchForecastStatusResponsePartsInner instantiates a new BatchForecastStatusResponsePartsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchForecastStatusResponsePartsInner() *BatchForecastStatusResponsePartsInner {
	this := BatchForecastStatusResponsePartsInner{}
	return &this
}

// NewBatchForecastStatusResponsePartsInnerWithDefaults instantiates a new BatchForecastStatusResponsePartsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchForecastStatusResponsePartsInnerWithDefaults() *BatchForecastStatusResponsePartsInner {
	this := BatchForecastStatusResponsePartsInner{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BatchForecastStatusResponsePartsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponsePartsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BatchForecastStatusResponsePartsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BatchForecastStatusResponsePartsInner) SetStatus(v string) {
	o.Status = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastStatusResponsePartsInner) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastStatusResponsePartsInner) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponsePartsInner) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *BatchForecastStatusResponsePartsInner) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *BatchForecastStatusResponsePartsInner) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *BatchForecastStatusResponsePartsInner) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastStatusResponsePartsInner) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastStatusResponsePartsInner) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponsePartsInner) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *BatchForecastStatusResponsePartsInner) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *BatchForecastStatusResponsePartsInner) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *BatchForecastStatusResponsePartsInner) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

func (o BatchForecastStatusResponsePartsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchForecastStatusResponsePartsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	return toSerialize, nil
}

type NullableBatchForecastStatusResponsePartsInner struct {
	value *BatchForecastStatusResponsePartsInner
	isSet bool
}

func (v NullableBatchForecastStatusResponsePartsInner) Get() *BatchForecastStatusResponsePartsInner {
	return v.value
}

func (v *NullableBatchForecastStatusResponsePartsInner) Set(val *BatchForecastStatusResponsePartsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchForecastStatusResponsePartsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchForecastStatusResponsePartsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchForecastStatusResponsePartsInner(val *BatchForecastStatusResponsePartsInner) *NullableBatchForecastStatusResponsePartsInner {
	return &NullableBatchForecastStatusResponsePartsInner{value: val, isSet: true}
}

func (v NullableBatchForecastStatusResponsePartsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchForecastStatusResponsePartsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


