/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AnalysisResponseMetaTiming type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisResponseMetaTiming{}

// AnalysisResponseMetaTiming struct for AnalysisResponseMetaTiming
type AnalysisResponseMetaTiming struct {
	// Time taken for validation in milliseconds
	Validation *float32 `json:"validation,omitempty"`
	// Time taken for analysis in milliseconds
	Analysing *float32 `json:"analysing,omitempty"`
	// Total processing time in milliseconds
	Total *float32 `json:"total,omitempty"`
}

// NewAnalysisResponseMetaTiming instantiates a new AnalysisResponseMetaTiming object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisResponseMetaTiming() *AnalysisResponseMetaTiming {
	this := AnalysisResponseMetaTiming{}
	return &this
}

// NewAnalysisResponseMetaTimingWithDefaults instantiates a new AnalysisResponseMetaTiming object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisResponseMetaTimingWithDefaults() *AnalysisResponseMetaTiming {
	this := AnalysisResponseMetaTiming{}
	return &this
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *AnalysisResponseMetaTiming) GetValidation() float32 {
	if o == nil || IsNil(o.Validation) {
		var ret float32
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponseMetaTiming) GetValidationOk() (*float32, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *AnalysisResponseMetaTiming) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given float32 and assigns it to the Validation field.
func (o *AnalysisResponseMetaTiming) SetValidation(v float32) {
	o.Validation = &v
}

// GetAnalysing returns the Analysing field value if set, zero value otherwise.
func (o *AnalysisResponseMetaTiming) GetAnalysing() float32 {
	if o == nil || IsNil(o.Analysing) {
		var ret float32
		return ret
	}
	return *o.Analysing
}

// GetAnalysingOk returns a tuple with the Analysing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponseMetaTiming) GetAnalysingOk() (*float32, bool) {
	if o == nil || IsNil(o.Analysing) {
		return nil, false
	}
	return o.Analysing, true
}

// HasAnalysing returns a boolean if a field has been set.
func (o *AnalysisResponseMetaTiming) HasAnalysing() bool {
	if o != nil && !IsNil(o.Analysing) {
		return true
	}

	return false
}

// SetAnalysing gets a reference to the given float32 and assigns it to the Analysing field.
func (o *AnalysisResponseMetaTiming) SetAnalysing(v float32) {
	o.Analysing = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AnalysisResponseMetaTiming) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponseMetaTiming) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AnalysisResponseMetaTiming) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *AnalysisResponseMetaTiming) SetTotal(v float32) {
	o.Total = &v
}

func (o AnalysisResponseMetaTiming) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisResponseMetaTiming) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Analysing) {
		toSerialize["analysing"] = o.Analysing
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAnalysisResponseMetaTiming struct {
	value *AnalysisResponseMetaTiming
	isSet bool
}

func (v NullableAnalysisResponseMetaTiming) Get() *AnalysisResponseMetaTiming {
	return v.value
}

func (v *NullableAnalysisResponseMetaTiming) Set(val *AnalysisResponseMetaTiming) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisResponseMetaTiming) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisResponseMetaTiming) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisResponseMetaTiming(val *AnalysisResponseMetaTiming) *NullableAnalysisResponseMetaTiming {
	return &NullableAnalysisResponseMetaTiming{value: val, isSet: true}
}

func (v NullableAnalysisResponseMetaTiming) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisResponseMetaTiming) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


