/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductInsightsRequestPurchasesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsRequestPurchasesInner{}

// ProductInsightsRequestPurchasesInner struct for ProductInsightsRequestPurchasesInner
type ProductInsightsRequestPurchasesInner struct {
	Date string `json:"date"`
	QuantityPurchased float32 `json:"quantity_purchased"`
	CostPrice float32 `json:"cost_price"`
	CostPriceConverted *float32 `json:"cost_price_converted,omitempty"`
	Currency NullableString `json:"currency,omitempty"`
	SupplierId NullableString `json:"supplier_id,omitempty"`
	// Used for lead-time reliability analysis
	PurchaseOrderDate NullableString `json:"purchase_order_date,omitempty"`
	ExpectedDeliveryDate NullableString `json:"expected_delivery_date,omitempty"`
	ActualDeliveryDate NullableString `json:"actual_delivery_date,omitempty"`
}

type _ProductInsightsRequestPurchasesInner ProductInsightsRequestPurchasesInner

// NewProductInsightsRequestPurchasesInner instantiates a new ProductInsightsRequestPurchasesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsRequestPurchasesInner(date string, quantityPurchased float32, costPrice float32) *ProductInsightsRequestPurchasesInner {
	this := ProductInsightsRequestPurchasesInner{}
	this.Date = date
	this.QuantityPurchased = quantityPurchased
	this.CostPrice = costPrice
	return &this
}

// NewProductInsightsRequestPurchasesInnerWithDefaults instantiates a new ProductInsightsRequestPurchasesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsRequestPurchasesInnerWithDefaults() *ProductInsightsRequestPurchasesInner {
	this := ProductInsightsRequestPurchasesInner{}
	return &this
}

// GetDate returns the Date field value
func (o *ProductInsightsRequestPurchasesInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequestPurchasesInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *ProductInsightsRequestPurchasesInner) SetDate(v string) {
	o.Date = v
}

// GetQuantityPurchased returns the QuantityPurchased field value
func (o *ProductInsightsRequestPurchasesInner) GetQuantityPurchased() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.QuantityPurchased
}

// GetQuantityPurchasedOk returns a tuple with the QuantityPurchased field value
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequestPurchasesInner) GetQuantityPurchasedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuantityPurchased, true
}

// SetQuantityPurchased sets field value
func (o *ProductInsightsRequestPurchasesInner) SetQuantityPurchased(v float32) {
	o.QuantityPurchased = v
}

// GetCostPrice returns the CostPrice field value
func (o *ProductInsightsRequestPurchasesInner) GetCostPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CostPrice
}

// GetCostPriceOk returns a tuple with the CostPrice field value
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequestPurchasesInner) GetCostPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CostPrice, true
}

// SetCostPrice sets field value
func (o *ProductInsightsRequestPurchasesInner) SetCostPrice(v float32) {
	o.CostPrice = v
}

// GetCostPriceConverted returns the CostPriceConverted field value if set, zero value otherwise.
func (o *ProductInsightsRequestPurchasesInner) GetCostPriceConverted() float32 {
	if o == nil || IsNil(o.CostPriceConverted) {
		var ret float32
		return ret
	}
	return *o.CostPriceConverted
}

// GetCostPriceConvertedOk returns a tuple with the CostPriceConverted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequestPurchasesInner) GetCostPriceConvertedOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPriceConverted) {
		return nil, false
	}
	return o.CostPriceConverted, true
}

// HasCostPriceConverted returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasCostPriceConverted() bool {
	if o != nil && !IsNil(o.CostPriceConverted) {
		return true
	}

	return false
}

// SetCostPriceConverted gets a reference to the given float32 and assigns it to the CostPriceConverted field.
func (o *ProductInsightsRequestPurchasesInner) SetCostPriceConverted(v float32) {
	o.CostPriceConverted = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequestPurchasesInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequestPurchasesInner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *ProductInsightsRequestPurchasesInner) SetCurrency(v string) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *ProductInsightsRequestPurchasesInner) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *ProductInsightsRequestPurchasesInner) UnsetCurrency() {
	o.Currency.Unset()
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequestPurchasesInner) GetSupplierId() string {
	if o == nil || IsNil(o.SupplierId.Get()) {
		var ret string
		return ret
	}
	return *o.SupplierId.Get()
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequestPurchasesInner) GetSupplierIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupplierId.Get(), o.SupplierId.IsSet()
}

// HasSupplierId returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasSupplierId() bool {
	if o != nil && o.SupplierId.IsSet() {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given NullableString and assigns it to the SupplierId field.
func (o *ProductInsightsRequestPurchasesInner) SetSupplierId(v string) {
	o.SupplierId.Set(&v)
}
// SetSupplierIdNil sets the value for SupplierId to be an explicit nil
func (o *ProductInsightsRequestPurchasesInner) SetSupplierIdNil() {
	o.SupplierId.Set(nil)
}

// UnsetSupplierId ensures that no value is present for SupplierId, not even an explicit nil
func (o *ProductInsightsRequestPurchasesInner) UnsetSupplierId() {
	o.SupplierId.Unset()
}

// GetPurchaseOrderDate returns the PurchaseOrderDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequestPurchasesInner) GetPurchaseOrderDate() string {
	if o == nil || IsNil(o.PurchaseOrderDate.Get()) {
		var ret string
		return ret
	}
	return *o.PurchaseOrderDate.Get()
}

// GetPurchaseOrderDateOk returns a tuple with the PurchaseOrderDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequestPurchasesInner) GetPurchaseOrderDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchaseOrderDate.Get(), o.PurchaseOrderDate.IsSet()
}

// HasPurchaseOrderDate returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasPurchaseOrderDate() bool {
	if o != nil && o.PurchaseOrderDate.IsSet() {
		return true
	}

	return false
}

// SetPurchaseOrderDate gets a reference to the given NullableString and assigns it to the PurchaseOrderDate field.
func (o *ProductInsightsRequestPurchasesInner) SetPurchaseOrderDate(v string) {
	o.PurchaseOrderDate.Set(&v)
}
// SetPurchaseOrderDateNil sets the value for PurchaseOrderDate to be an explicit nil
func (o *ProductInsightsRequestPurchasesInner) SetPurchaseOrderDateNil() {
	o.PurchaseOrderDate.Set(nil)
}

// UnsetPurchaseOrderDate ensures that no value is present for PurchaseOrderDate, not even an explicit nil
func (o *ProductInsightsRequestPurchasesInner) UnsetPurchaseOrderDate() {
	o.PurchaseOrderDate.Unset()
}

// GetExpectedDeliveryDate returns the ExpectedDeliveryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequestPurchasesInner) GetExpectedDeliveryDate() string {
	if o == nil || IsNil(o.ExpectedDeliveryDate.Get()) {
		var ret string
		return ret
	}
	return *o.ExpectedDeliveryDate.Get()
}

// GetExpectedDeliveryDateOk returns a tuple with the ExpectedDeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequestPurchasesInner) GetExpectedDeliveryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedDeliveryDate.Get(), o.ExpectedDeliveryDate.IsSet()
}

// HasExpectedDeliveryDate returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasExpectedDeliveryDate() bool {
	if o != nil && o.ExpectedDeliveryDate.IsSet() {
		return true
	}

	return false
}

// SetExpectedDeliveryDate gets a reference to the given NullableString and assigns it to the ExpectedDeliveryDate field.
func (o *ProductInsightsRequestPurchasesInner) SetExpectedDeliveryDate(v string) {
	o.ExpectedDeliveryDate.Set(&v)
}
// SetExpectedDeliveryDateNil sets the value for ExpectedDeliveryDate to be an explicit nil
func (o *ProductInsightsRequestPurchasesInner) SetExpectedDeliveryDateNil() {
	o.ExpectedDeliveryDate.Set(nil)
}

// UnsetExpectedDeliveryDate ensures that no value is present for ExpectedDeliveryDate, not even an explicit nil
func (o *ProductInsightsRequestPurchasesInner) UnsetExpectedDeliveryDate() {
	o.ExpectedDeliveryDate.Unset()
}

// GetActualDeliveryDate returns the ActualDeliveryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequestPurchasesInner) GetActualDeliveryDate() string {
	if o == nil || IsNil(o.ActualDeliveryDate.Get()) {
		var ret string
		return ret
	}
	return *o.ActualDeliveryDate.Get()
}

// GetActualDeliveryDateOk returns a tuple with the ActualDeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequestPurchasesInner) GetActualDeliveryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActualDeliveryDate.Get(), o.ActualDeliveryDate.IsSet()
}

// HasActualDeliveryDate returns a boolean if a field has been set.
func (o *ProductInsightsRequestPurchasesInner) HasActualDeliveryDate() bool {
	if o != nil && o.ActualDeliveryDate.IsSet() {
		return true
	}

	return false
}

// SetActualDeliveryDate gets a reference to the given NullableString and assigns it to the ActualDeliveryDate field.
func (o *ProductInsightsRequestPurchasesInner) SetActualDeliveryDate(v string) {
	o.ActualDeliveryDate.Set(&v)
}
// SetActualDeliveryDateNil sets the value for ActualDeliveryDate to be an explicit nil
func (o *ProductInsightsRequestPurchasesInner) SetActualDeliveryDateNil() {
	o.ActualDeliveryDate.Set(nil)
}

// UnsetActualDeliveryDate ensures that no value is present for ActualDeliveryDate, not even an explicit nil
func (o *ProductInsightsRequestPurchasesInner) UnsetActualDeliveryDate() {
	o.ActualDeliveryDate.Unset()
}

func (o ProductInsightsRequestPurchasesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsRequestPurchasesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["quantity_purchased"] = o.QuantityPurchased
	toSerialize["cost_price"] = o.CostPrice
	if !IsNil(o.CostPriceConverted) {
		toSerialize["cost_price_converted"] = o.CostPriceConverted
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.SupplierId.IsSet() {
		toSerialize["supplier_id"] = o.SupplierId.Get()
	}
	if o.PurchaseOrderDate.IsSet() {
		toSerialize["purchase_order_date"] = o.PurchaseOrderDate.Get()
	}
	if o.ExpectedDeliveryDate.IsSet() {
		toSerialize["expected_delivery_date"] = o.ExpectedDeliveryDate.Get()
	}
	if o.ActualDeliveryDate.IsSet() {
		toSerialize["actual_delivery_date"] = o.ActualDeliveryDate.Get()
	}
	return toSerialize, nil
}

func (o *ProductInsightsRequestPurchasesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"quantity_purchased",
		"cost_price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductInsightsRequestPurchasesInner := _ProductInsightsRequestPurchasesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductInsightsRequestPurchasesInner)

	if err != nil {
		return err
	}

	*o = ProductInsightsRequestPurchasesInner(varProductInsightsRequestPurchasesInner)

	return err
}

type NullableProductInsightsRequestPurchasesInner struct {
	value *ProductInsightsRequestPurchasesInner
	isSet bool
}

func (v NullableProductInsightsRequestPurchasesInner) Get() *ProductInsightsRequestPurchasesInner {
	return v.value
}

func (v *NullableProductInsightsRequestPurchasesInner) Set(val *ProductInsightsRequestPurchasesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsRequestPurchasesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsRequestPurchasesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsRequestPurchasesInner(val *ProductInsightsRequestPurchasesInner) *NullableProductInsightsRequestPurchasesInner {
	return &NullableProductInsightsRequestPurchasesInner{value: val, isSet: true}
}

func (v NullableProductInsightsRequestPurchasesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsRequestPurchasesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


