/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the GroupedForecastNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedForecastNode{}

// GroupedForecastNode struct for GroupedForecastNode
type GroupedForecastNode struct {
	// The measure — the same for every node
	Identifier *string `json:"identifier,omitempty"`
	// The dimension values this node covers — empty for the total, all declared dimensions for a leaf
	Segment map[string]interface{} `json:"segment,omitempty"`
	// Depth in the tree; 0 is the total
	Level *int32 `json:"level,omitempty"`
	IsLeaf *bool `json:"is_leaf,omitempty"`
	// Segment key of the parent node; null for the total
	Parent NullableString `json:"parent,omitempty"`
	// Segment keys of the children; empty for leaves
	Children []string `json:"children,omitempty"`
	// The reconciled path — this is what is stored and accuracy-tracked per node
	Forecasts []ForecastPeriod `json:"forecasts,omitempty"`
	// Method and reconciliation details for this node. With min_trace, the node's unreconciled path is reported under `reconciliation.base_forecast`. When an aggregate band cannot be built honestly (a child's band coverage is unknown), the band is omitted and `reconciliation.interval_reason` states why. 
	ModelInfo map[string]interface{} `json:"model_info,omitempty"`
}

// NewGroupedForecastNode instantiates a new GroupedForecastNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedForecastNode() *GroupedForecastNode {
	this := GroupedForecastNode{}
	return &this
}

// NewGroupedForecastNodeWithDefaults instantiates a new GroupedForecastNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedForecastNodeWithDefaults() *GroupedForecastNode {
	this := GroupedForecastNode{}
	return &this
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *GroupedForecastNode) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetSegment returns the Segment field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetSegment() map[string]interface{} {
	if o == nil || IsNil(o.Segment) {
		var ret map[string]interface{}
		return ret
	}
	return o.Segment
}

// GetSegmentOk returns a tuple with the Segment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetSegmentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Segment) {
		return map[string]interface{}{}, false
	}
	return o.Segment, true
}

// HasSegment returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasSegment() bool {
	if o != nil && !IsNil(o.Segment) {
		return true
	}

	return false
}

// SetSegment gets a reference to the given map[string]interface{} and assigns it to the Segment field.
func (o *GroupedForecastNode) SetSegment(v map[string]interface{}) {
	o.Segment = v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *GroupedForecastNode) SetLevel(v int32) {
	o.Level = &v
}

// GetIsLeaf returns the IsLeaf field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetIsLeaf() bool {
	if o == nil || IsNil(o.IsLeaf) {
		var ret bool
		return ret
	}
	return *o.IsLeaf
}

// GetIsLeafOk returns a tuple with the IsLeaf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetIsLeafOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLeaf) {
		return nil, false
	}
	return o.IsLeaf, true
}

// HasIsLeaf returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasIsLeaf() bool {
	if o != nil && !IsNil(o.IsLeaf) {
		return true
	}

	return false
}

// SetIsLeaf gets a reference to the given bool and assigns it to the IsLeaf field.
func (o *GroupedForecastNode) SetIsLeaf(v bool) {
	o.IsLeaf = &v
}

// GetParent returns the Parent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupedForecastNode) GetParent() string {
	if o == nil || IsNil(o.Parent.Get()) {
		var ret string
		return ret
	}
	return *o.Parent.Get()
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupedForecastNode) GetParentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Parent.Get(), o.Parent.IsSet()
}

// HasParent returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasParent() bool {
	if o != nil && o.Parent.IsSet() {
		return true
	}

	return false
}

// SetParent gets a reference to the given NullableString and assigns it to the Parent field.
func (o *GroupedForecastNode) SetParent(v string) {
	o.Parent.Set(&v)
}
// SetParentNil sets the value for Parent to be an explicit nil
func (o *GroupedForecastNode) SetParentNil() {
	o.Parent.Set(nil)
}

// UnsetParent ensures that no value is present for Parent, not even an explicit nil
func (o *GroupedForecastNode) UnsetParent() {
	o.Parent.Unset()
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetChildren() []string {
	if o == nil || IsNil(o.Children) {
		var ret []string
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetChildrenOk() ([]string, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []string and assigns it to the Children field.
func (o *GroupedForecastNode) SetChildren(v []string) {
	o.Children = v
}

// GetForecasts returns the Forecasts field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetForecasts() []ForecastPeriod {
	if o == nil || IsNil(o.Forecasts) {
		var ret []ForecastPeriod
		return ret
	}
	return o.Forecasts
}

// GetForecastsOk returns a tuple with the Forecasts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetForecastsOk() ([]ForecastPeriod, bool) {
	if o == nil || IsNil(o.Forecasts) {
		return nil, false
	}
	return o.Forecasts, true
}

// HasForecasts returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasForecasts() bool {
	if o != nil && !IsNil(o.Forecasts) {
		return true
	}

	return false
}

// SetForecasts gets a reference to the given []ForecastPeriod and assigns it to the Forecasts field.
func (o *GroupedForecastNode) SetForecasts(v []ForecastPeriod) {
	o.Forecasts = v
}

// GetModelInfo returns the ModelInfo field value if set, zero value otherwise.
func (o *GroupedForecastNode) GetModelInfo() map[string]interface{} {
	if o == nil || IsNil(o.ModelInfo) {
		var ret map[string]interface{}
		return ret
	}
	return o.ModelInfo
}

// GetModelInfoOk returns a tuple with the ModelInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedForecastNode) GetModelInfoOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ModelInfo) {
		return map[string]interface{}{}, false
	}
	return o.ModelInfo, true
}

// HasModelInfo returns a boolean if a field has been set.
func (o *GroupedForecastNode) HasModelInfo() bool {
	if o != nil && !IsNil(o.ModelInfo) {
		return true
	}

	return false
}

// SetModelInfo gets a reference to the given map[string]interface{} and assigns it to the ModelInfo field.
func (o *GroupedForecastNode) SetModelInfo(v map[string]interface{}) {
	o.ModelInfo = v
}

func (o GroupedForecastNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedForecastNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.Segment) {
		toSerialize["segment"] = o.Segment
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.IsLeaf) {
		toSerialize["is_leaf"] = o.IsLeaf
	}
	if o.Parent.IsSet() {
		toSerialize["parent"] = o.Parent.Get()
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	if !IsNil(o.Forecasts) {
		toSerialize["forecasts"] = o.Forecasts
	}
	if !IsNil(o.ModelInfo) {
		toSerialize["model_info"] = o.ModelInfo
	}
	return toSerialize, nil
}

type NullableGroupedForecastNode struct {
	value *GroupedForecastNode
	isSet bool
}

func (v NullableGroupedForecastNode) Get() *GroupedForecastNode {
	return v.value
}

func (v *NullableGroupedForecastNode) Set(val *GroupedForecastNode) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedForecastNode) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedForecastNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedForecastNode(val *GroupedForecastNode) *NullableGroupedForecastNode {
	return &NullableGroupedForecastNode{value: val, isSet: true}
}

func (v NullableGroupedForecastNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedForecastNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


