/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the InventoryPlanningResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryPlanningResponse{}

// InventoryPlanningResponse struct for InventoryPlanningResponse
type InventoryPlanningResponse struct {
	Result *InventoryPlanningResponseResult `json:"result,omitempty"`
	Meta *InventoryPlanningResponseMeta `json:"meta,omitempty"`
}

// NewInventoryPlanningResponse instantiates a new InventoryPlanningResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryPlanningResponse() *InventoryPlanningResponse {
	this := InventoryPlanningResponse{}
	return &this
}

// NewInventoryPlanningResponseWithDefaults instantiates a new InventoryPlanningResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryPlanningResponseWithDefaults() *InventoryPlanningResponse {
	this := InventoryPlanningResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *InventoryPlanningResponse) GetResult() InventoryPlanningResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret InventoryPlanningResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryPlanningResponse) GetResultOk() (*InventoryPlanningResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *InventoryPlanningResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given InventoryPlanningResponseResult and assigns it to the Result field.
func (o *InventoryPlanningResponse) SetResult(v InventoryPlanningResponseResult) {
	o.Result = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *InventoryPlanningResponse) GetMeta() InventoryPlanningResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret InventoryPlanningResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryPlanningResponse) GetMetaOk() (*InventoryPlanningResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *InventoryPlanningResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given InventoryPlanningResponseMeta and assigns it to the Meta field.
func (o *InventoryPlanningResponse) SetMeta(v InventoryPlanningResponseMeta) {
	o.Meta = &v
}

func (o InventoryPlanningResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryPlanningResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableInventoryPlanningResponse struct {
	value *InventoryPlanningResponse
	isSet bool
}

func (v NullableInventoryPlanningResponse) Get() *InventoryPlanningResponse {
	return v.value
}

func (v *NullableInventoryPlanningResponse) Set(val *InventoryPlanningResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryPlanningResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryPlanningResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryPlanningResponse(val *InventoryPlanningResponse) *NullableInventoryPlanningResponse {
	return &NullableInventoryPlanningResponse{value: val, isSet: true}
}

func (v NullableInventoryPlanningResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryPlanningResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


