/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ProductInsight type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsight{}

// ProductInsight struct for ProductInsight
type ProductInsight struct {
	// Insight family (e.g. margin, sales, cost, lead_time)
	Class *string `json:"class,omitempty"`
	Type *string `json:"type,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	// The numbers behind the insight
	Metrics map[string]interface{} `json:"metrics,omitempty"`
	Recommendation *ProductInsightRecommendation `json:"recommendation,omitempty"`
	Confidence *string `json:"confidence,omitempty"`
	Date *string `json:"date,omitempty"`
	// How this insight compares to the previous analysis of the same product — every insight is \"new\" on the first analysis
	ChangeStatus *string `json:"change_status,omitempty"`
}

// NewProductInsight instantiates a new ProductInsight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsight() *ProductInsight {
	this := ProductInsight{}
	return &this
}

// NewProductInsightWithDefaults instantiates a new ProductInsight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightWithDefaults() *ProductInsight {
	this := ProductInsight{}
	return &this
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *ProductInsight) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *ProductInsight) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *ProductInsight) SetClass(v string) {
	o.Class = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProductInsight) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProductInsight) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProductInsight) SetType(v string) {
	o.Type = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *ProductInsight) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *ProductInsight) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *ProductInsight) SetSeverity(v string) {
	o.Severity = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ProductInsight) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ProductInsight) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ProductInsight) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProductInsight) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProductInsight) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProductInsight) SetDescription(v string) {
	o.Description = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *ProductInsight) GetMetrics() map[string]interface{} {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetMetricsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metrics) {
		return map[string]interface{}{}, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *ProductInsight) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]interface{} and assigns it to the Metrics field.
func (o *ProductInsight) SetMetrics(v map[string]interface{}) {
	o.Metrics = v
}

// GetRecommendation returns the Recommendation field value if set, zero value otherwise.
func (o *ProductInsight) GetRecommendation() ProductInsightRecommendation {
	if o == nil || IsNil(o.Recommendation) {
		var ret ProductInsightRecommendation
		return ret
	}
	return *o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetRecommendationOk() (*ProductInsightRecommendation, bool) {
	if o == nil || IsNil(o.Recommendation) {
		return nil, false
	}
	return o.Recommendation, true
}

// HasRecommendation returns a boolean if a field has been set.
func (o *ProductInsight) HasRecommendation() bool {
	if o != nil && !IsNil(o.Recommendation) {
		return true
	}

	return false
}

// SetRecommendation gets a reference to the given ProductInsightRecommendation and assigns it to the Recommendation field.
func (o *ProductInsight) SetRecommendation(v ProductInsightRecommendation) {
	o.Recommendation = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *ProductInsight) GetConfidence() string {
	if o == nil || IsNil(o.Confidence) {
		var ret string
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetConfidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *ProductInsight) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given string and assigns it to the Confidence field.
func (o *ProductInsight) SetConfidence(v string) {
	o.Confidence = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ProductInsight) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ProductInsight) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ProductInsight) SetDate(v string) {
	o.Date = &v
}

// GetChangeStatus returns the ChangeStatus field value if set, zero value otherwise.
func (o *ProductInsight) GetChangeStatus() string {
	if o == nil || IsNil(o.ChangeStatus) {
		var ret string
		return ret
	}
	return *o.ChangeStatus
}

// GetChangeStatusOk returns a tuple with the ChangeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsight) GetChangeStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeStatus) {
		return nil, false
	}
	return o.ChangeStatus, true
}

// HasChangeStatus returns a boolean if a field has been set.
func (o *ProductInsight) HasChangeStatus() bool {
	if o != nil && !IsNil(o.ChangeStatus) {
		return true
	}

	return false
}

// SetChangeStatus gets a reference to the given string and assigns it to the ChangeStatus field.
func (o *ProductInsight) SetChangeStatus(v string) {
	o.ChangeStatus = &v
}

func (o ProductInsight) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsight) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.Recommendation) {
		toSerialize["recommendation"] = o.Recommendation
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.ChangeStatus) {
		toSerialize["change_status"] = o.ChangeStatus
	}
	return toSerialize, nil
}

type NullableProductInsight struct {
	value *ProductInsight
	isSet bool
}

func (v NullableProductInsight) Get() *ProductInsight {
	return v.value
}

func (v *NullableProductInsight) Set(val *ProductInsight) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsight) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsight(val *ProductInsight) *NullableProductInsight {
	return &NullableProductInsight{value: val, isSet: true}
}

func (v NullableProductInsight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


