/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the DeprecatedV1404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeprecatedV1404Response{}

// DeprecatedV1404Response struct for DeprecatedV1404Response
type DeprecatedV1404Response struct {
	Error *string `json:"error,omitempty"`
}

// NewDeprecatedV1404Response instantiates a new DeprecatedV1404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedV1404Response() *DeprecatedV1404Response {
	this := DeprecatedV1404Response{}
	return &this
}

// NewDeprecatedV1404ResponseWithDefaults instantiates a new DeprecatedV1404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedV1404ResponseWithDefaults() *DeprecatedV1404Response {
	this := DeprecatedV1404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *DeprecatedV1404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedV1404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *DeprecatedV1404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *DeprecatedV1404Response) SetError(v string) {
	o.Error = &v
}

func (o DeprecatedV1404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeprecatedV1404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableDeprecatedV1404Response struct {
	value *DeprecatedV1404Response
	isSet bool
}

func (v NullableDeprecatedV1404Response) Get() *DeprecatedV1404Response {
	return v.value
}

func (v *NullableDeprecatedV1404Response) Set(val *DeprecatedV1404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedV1404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedV1404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedV1404Response(val *DeprecatedV1404Response) *NullableDeprecatedV1404Response {
	return &NullableDeprecatedV1404Response{value: val, isSet: true}
}

func (v NullableDeprecatedV1404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedV1404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


