/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AnomalyDetectionResponseMetaTiming type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnomalyDetectionResponseMetaTiming{}

// AnomalyDetectionResponseMetaTiming struct for AnomalyDetectionResponseMetaTiming
type AnomalyDetectionResponseMetaTiming struct {
	Validation *float32 `json:"validation,omitempty"`
	Detection *float32 `json:"detection,omitempty"`
	Total *float32 `json:"total,omitempty"`
}

// NewAnomalyDetectionResponseMetaTiming instantiates a new AnomalyDetectionResponseMetaTiming object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnomalyDetectionResponseMetaTiming() *AnomalyDetectionResponseMetaTiming {
	this := AnomalyDetectionResponseMetaTiming{}
	return &this
}

// NewAnomalyDetectionResponseMetaTimingWithDefaults instantiates a new AnomalyDetectionResponseMetaTiming object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnomalyDetectionResponseMetaTimingWithDefaults() *AnomalyDetectionResponseMetaTiming {
	this := AnomalyDetectionResponseMetaTiming{}
	return &this
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *AnomalyDetectionResponseMetaTiming) GetValidation() float32 {
	if o == nil || IsNil(o.Validation) {
		var ret float32
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionResponseMetaTiming) GetValidationOk() (*float32, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *AnomalyDetectionResponseMetaTiming) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given float32 and assigns it to the Validation field.
func (o *AnomalyDetectionResponseMetaTiming) SetValidation(v float32) {
	o.Validation = &v
}

// GetDetection returns the Detection field value if set, zero value otherwise.
func (o *AnomalyDetectionResponseMetaTiming) GetDetection() float32 {
	if o == nil || IsNil(o.Detection) {
		var ret float32
		return ret
	}
	return *o.Detection
}

// GetDetectionOk returns a tuple with the Detection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionResponseMetaTiming) GetDetectionOk() (*float32, bool) {
	if o == nil || IsNil(o.Detection) {
		return nil, false
	}
	return o.Detection, true
}

// HasDetection returns a boolean if a field has been set.
func (o *AnomalyDetectionResponseMetaTiming) HasDetection() bool {
	if o != nil && !IsNil(o.Detection) {
		return true
	}

	return false
}

// SetDetection gets a reference to the given float32 and assigns it to the Detection field.
func (o *AnomalyDetectionResponseMetaTiming) SetDetection(v float32) {
	o.Detection = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AnomalyDetectionResponseMetaTiming) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionResponseMetaTiming) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AnomalyDetectionResponseMetaTiming) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *AnomalyDetectionResponseMetaTiming) SetTotal(v float32) {
	o.Total = &v
}

func (o AnomalyDetectionResponseMetaTiming) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnomalyDetectionResponseMetaTiming) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Detection) {
		toSerialize["detection"] = o.Detection
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAnomalyDetectionResponseMetaTiming struct {
	value *AnomalyDetectionResponseMetaTiming
	isSet bool
}

func (v NullableAnomalyDetectionResponseMetaTiming) Get() *AnomalyDetectionResponseMetaTiming {
	return v.value
}

func (v *NullableAnomalyDetectionResponseMetaTiming) Set(val *AnomalyDetectionResponseMetaTiming) {
	v.value = val
	v.isSet = true
}

func (v NullableAnomalyDetectionResponseMetaTiming) IsSet() bool {
	return v.isSet
}

func (v *NullableAnomalyDetectionResponseMetaTiming) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnomalyDetectionResponseMetaTiming(val *AnomalyDetectionResponseMetaTiming) *NullableAnomalyDetectionResponseMetaTiming {
	return &NullableAnomalyDetectionResponseMetaTiming{value: val, isSet: true}
}

func (v NullableAnomalyDetectionResponseMetaTiming) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnomalyDetectionResponseMetaTiming) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


