/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the TrafficForecastingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficForecastingResponse{}

// TrafficForecastingResponse struct for TrafficForecastingResponse
type TrafficForecastingResponse struct {
	Result *TrafficForecastingResponseResult `json:"result,omitempty"`
	Meta *TrafficForecastingResponseMeta `json:"meta,omitempty"`
}

// NewTrafficForecastingResponse instantiates a new TrafficForecastingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficForecastingResponse() *TrafficForecastingResponse {
	this := TrafficForecastingResponse{}
	return &this
}

// NewTrafficForecastingResponseWithDefaults instantiates a new TrafficForecastingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficForecastingResponseWithDefaults() *TrafficForecastingResponse {
	this := TrafficForecastingResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TrafficForecastingResponse) GetResult() TrafficForecastingResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret TrafficForecastingResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficForecastingResponse) GetResultOk() (*TrafficForecastingResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TrafficForecastingResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given TrafficForecastingResponseResult and assigns it to the Result field.
func (o *TrafficForecastingResponse) SetResult(v TrafficForecastingResponseResult) {
	o.Result = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *TrafficForecastingResponse) GetMeta() TrafficForecastingResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret TrafficForecastingResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficForecastingResponse) GetMetaOk() (*TrafficForecastingResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *TrafficForecastingResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given TrafficForecastingResponseMeta and assigns it to the Meta field.
func (o *TrafficForecastingResponse) SetMeta(v TrafficForecastingResponseMeta) {
	o.Meta = &v
}

func (o TrafficForecastingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficForecastingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableTrafficForecastingResponse struct {
	value *TrafficForecastingResponse
	isSet bool
}

func (v NullableTrafficForecastingResponse) Get() *TrafficForecastingResponse {
	return v.value
}

func (v *NullableTrafficForecastingResponse) Set(val *TrafficForecastingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficForecastingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficForecastingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficForecastingResponse(val *TrafficForecastingResponse) *NullableTrafficForecastingResponse {
	return &NullableTrafficForecastingResponse{value: val, isSet: true}
}

func (v NullableTrafficForecastingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficForecastingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


