/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the CreateForecast502Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateForecast502Response{}

// CreateForecast502Response struct for CreateForecast502Response
type CreateForecast502Response struct {
	Error *string `json:"error,omitempty"`
	TimeTakenMs *float32 `json:"time_taken_ms,omitempty"`
}

// NewCreateForecast502Response instantiates a new CreateForecast502Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateForecast502Response() *CreateForecast502Response {
	this := CreateForecast502Response{}
	return &this
}

// NewCreateForecast502ResponseWithDefaults instantiates a new CreateForecast502Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateForecast502ResponseWithDefaults() *CreateForecast502Response {
	this := CreateForecast502Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateForecast502Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateForecast502Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateForecast502Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateForecast502Response) SetError(v string) {
	o.Error = &v
}

// GetTimeTakenMs returns the TimeTakenMs field value if set, zero value otherwise.
func (o *CreateForecast502Response) GetTimeTakenMs() float32 {
	if o == nil || IsNil(o.TimeTakenMs) {
		var ret float32
		return ret
	}
	return *o.TimeTakenMs
}

// GetTimeTakenMsOk returns a tuple with the TimeTakenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateForecast502Response) GetTimeTakenMsOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeTakenMs) {
		return nil, false
	}
	return o.TimeTakenMs, true
}

// HasTimeTakenMs returns a boolean if a field has been set.
func (o *CreateForecast502Response) HasTimeTakenMs() bool {
	if o != nil && !IsNil(o.TimeTakenMs) {
		return true
	}

	return false
}

// SetTimeTakenMs gets a reference to the given float32 and assigns it to the TimeTakenMs field.
func (o *CreateForecast502Response) SetTimeTakenMs(v float32) {
	o.TimeTakenMs = &v
}

func (o CreateForecast502Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateForecast502Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.TimeTakenMs) {
		toSerialize["time_taken_ms"] = o.TimeTakenMs
	}
	return toSerialize, nil
}

type NullableCreateForecast502Response struct {
	value *CreateForecast502Response
	isSet bool
}

func (v NullableCreateForecast502Response) Get() *CreateForecast502Response {
	return v.value
}

func (v *NullableCreateForecast502Response) Set(val *CreateForecast502Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateForecast502Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateForecast502Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateForecast502Response(val *CreateForecast502Response) *NullableCreateForecast502Response {
	return &NullableCreateForecast502Response{value: val, isSet: true}
}

func (v NullableCreateForecast502Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateForecast502Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


