/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.1.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InventoryPlanningRequestInventorySettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryPlanningRequestInventorySettings{}

// InventoryPlanningRequestInventorySettings Current inventory status and supplier information
type InventoryPlanningRequestInventorySettings struct {
	// Current quantity in stock
	CurrentStock float32 `json:"current_stock"`
	// Minimum stock level to maintain
	MinimumStock float32 `json:"minimum_stock"`
	// Target service level (probability of not stocking out)
	ServiceLevel float32 `json:"service_level"`
	// Available suppliers with their characteristics
	Suppliers []InventoryPlanningRequestInventorySettingsSuppliersInner `json:"suppliers"`
}

type _InventoryPlanningRequestInventorySettings InventoryPlanningRequestInventorySettings

// NewInventoryPlanningRequestInventorySettings instantiates a new InventoryPlanningRequestInventorySettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryPlanningRequestInventorySettings(currentStock float32, minimumStock float32, serviceLevel float32, suppliers []InventoryPlanningRequestInventorySettingsSuppliersInner) *InventoryPlanningRequestInventorySettings {
	this := InventoryPlanningRequestInventorySettings{}
	this.CurrentStock = currentStock
	this.MinimumStock = minimumStock
	this.ServiceLevel = serviceLevel
	this.Suppliers = suppliers
	return &this
}

// NewInventoryPlanningRequestInventorySettingsWithDefaults instantiates a new InventoryPlanningRequestInventorySettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryPlanningRequestInventorySettingsWithDefaults() *InventoryPlanningRequestInventorySettings {
	this := InventoryPlanningRequestInventorySettings{}
	return &this
}

// GetCurrentStock returns the CurrentStock field value
func (o *InventoryPlanningRequestInventorySettings) GetCurrentStock() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentStock
}

// GetCurrentStockOk returns a tuple with the CurrentStock field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequestInventorySettings) GetCurrentStockOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentStock, true
}

// SetCurrentStock sets field value
func (o *InventoryPlanningRequestInventorySettings) SetCurrentStock(v float32) {
	o.CurrentStock = v
}

// GetMinimumStock returns the MinimumStock field value
func (o *InventoryPlanningRequestInventorySettings) GetMinimumStock() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MinimumStock
}

// GetMinimumStockOk returns a tuple with the MinimumStock field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequestInventorySettings) GetMinimumStockOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumStock, true
}

// SetMinimumStock sets field value
func (o *InventoryPlanningRequestInventorySettings) SetMinimumStock(v float32) {
	o.MinimumStock = v
}

// GetServiceLevel returns the ServiceLevel field value
func (o *InventoryPlanningRequestInventorySettings) GetServiceLevel() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ServiceLevel
}

// GetServiceLevelOk returns a tuple with the ServiceLevel field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequestInventorySettings) GetServiceLevelOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceLevel, true
}

// SetServiceLevel sets field value
func (o *InventoryPlanningRequestInventorySettings) SetServiceLevel(v float32) {
	o.ServiceLevel = v
}

// GetSuppliers returns the Suppliers field value
func (o *InventoryPlanningRequestInventorySettings) GetSuppliers() []InventoryPlanningRequestInventorySettingsSuppliersInner {
	if o == nil {
		var ret []InventoryPlanningRequestInventorySettingsSuppliersInner
		return ret
	}

	return o.Suppliers
}

// GetSuppliersOk returns a tuple with the Suppliers field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequestInventorySettings) GetSuppliersOk() ([]InventoryPlanningRequestInventorySettingsSuppliersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Suppliers, true
}

// SetSuppliers sets field value
func (o *InventoryPlanningRequestInventorySettings) SetSuppliers(v []InventoryPlanningRequestInventorySettingsSuppliersInner) {
	o.Suppliers = v
}

func (o InventoryPlanningRequestInventorySettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryPlanningRequestInventorySettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current_stock"] = o.CurrentStock
	toSerialize["minimum_stock"] = o.MinimumStock
	toSerialize["service_level"] = o.ServiceLevel
	toSerialize["suppliers"] = o.Suppliers
	return toSerialize, nil
}

func (o *InventoryPlanningRequestInventorySettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current_stock",
		"minimum_stock",
		"service_level",
		"suppliers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInventoryPlanningRequestInventorySettings := _InventoryPlanningRequestInventorySettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInventoryPlanningRequestInventorySettings)

	if err != nil {
		return err
	}

	*o = InventoryPlanningRequestInventorySettings(varInventoryPlanningRequestInventorySettings)

	return err
}

type NullableInventoryPlanningRequestInventorySettings struct {
	value *InventoryPlanningRequestInventorySettings
	isSet bool
}

func (v NullableInventoryPlanningRequestInventorySettings) Get() *InventoryPlanningRequestInventorySettings {
	return v.value
}

func (v *NullableInventoryPlanningRequestInventorySettings) Set(val *InventoryPlanningRequestInventorySettings) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryPlanningRequestInventorySettings) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryPlanningRequestInventorySettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryPlanningRequestInventorySettings(val *InventoryPlanningRequestInventorySettings) *NullableInventoryPlanningRequestInventorySettings {
	return &NullableInventoryPlanningRequestInventorySettings{value: val, isSet: true}
}

func (v NullableInventoryPlanningRequestInventorySettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryPlanningRequestInventorySettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


