/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"time"
)

// checks if the ProductInsightsBatchStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsBatchStatusResponse{}

// ProductInsightsBatchStatusResponse struct for ProductInsightsBatchStatusResponse
type ProductInsightsBatchStatusResponse struct {
	// The batch id
	Identifier *string `json:"identifier,omitempty"`
	Status *string `json:"status,omitempty"`
	BatchParts NullableInt32 `json:"batch_parts,omitempty"`
	// Summary and per-product analysis results as parts complete
	Results map[string]interface{} `json:"results,omitempty"`
	// Per-part progress, each carrying its analyses once processed
	Parts []map[string]interface{} `json:"parts,omitempty"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewProductInsightsBatchStatusResponse instantiates a new ProductInsightsBatchStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsBatchStatusResponse() *ProductInsightsBatchStatusResponse {
	this := ProductInsightsBatchStatusResponse{}
	return &this
}

// NewProductInsightsBatchStatusResponseWithDefaults instantiates a new ProductInsightsBatchStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsBatchStatusResponseWithDefaults() *ProductInsightsBatchStatusResponse {
	this := ProductInsightsBatchStatusResponse{}
	return &this
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *ProductInsightsBatchStatusResponse) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchStatusResponse) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *ProductInsightsBatchStatusResponse) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProductInsightsBatchStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProductInsightsBatchStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetBatchParts returns the BatchParts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsBatchStatusResponse) GetBatchParts() int32 {
	if o == nil || IsNil(o.BatchParts.Get()) {
		var ret int32
		return ret
	}
	return *o.BatchParts.Get()
}

// GetBatchPartsOk returns a tuple with the BatchParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsBatchStatusResponse) GetBatchPartsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatchParts.Get(), o.BatchParts.IsSet()
}

// HasBatchParts returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasBatchParts() bool {
	if o != nil && o.BatchParts.IsSet() {
		return true
	}

	return false
}

// SetBatchParts gets a reference to the given NullableInt32 and assigns it to the BatchParts field.
func (o *ProductInsightsBatchStatusResponse) SetBatchParts(v int32) {
	o.BatchParts.Set(&v)
}
// SetBatchPartsNil sets the value for BatchParts to be an explicit nil
func (o *ProductInsightsBatchStatusResponse) SetBatchPartsNil() {
	o.BatchParts.Set(nil)
}

// UnsetBatchParts ensures that no value is present for BatchParts, not even an explicit nil
func (o *ProductInsightsBatchStatusResponse) UnsetBatchParts() {
	o.BatchParts.Unset()
}

// GetResults returns the Results field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsBatchStatusResponse) GetResults() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsBatchStatusResponse) GetResultsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Results) {
		return map[string]interface{}{}, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]interface{} and assigns it to the Results field.
func (o *ProductInsightsBatchStatusResponse) SetResults(v map[string]interface{}) {
	o.Results = v
}

// GetParts returns the Parts field value if set, zero value otherwise.
func (o *ProductInsightsBatchStatusResponse) GetParts() []map[string]interface{} {
	if o == nil || IsNil(o.Parts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Parts
}

// GetPartsOk returns a tuple with the Parts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchStatusResponse) GetPartsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parts) {
		return nil, false
	}
	return o.Parts, true
}

// HasParts returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasParts() bool {
	if o != nil && !IsNil(o.Parts) {
		return true
	}

	return false
}

// SetParts gets a reference to the given []map[string]interface{} and assigns it to the Parts field.
func (o *ProductInsightsBatchStatusResponse) SetParts(v []map[string]interface{}) {
	o.Parts = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsBatchStatusResponse) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsBatchStatusResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *ProductInsightsBatchStatusResponse) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *ProductInsightsBatchStatusResponse) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *ProductInsightsBatchStatusResponse) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsBatchStatusResponse) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsBatchStatusResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *ProductInsightsBatchStatusResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *ProductInsightsBatchStatusResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *ProductInsightsBatchStatusResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProductInsightsBatchStatusResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchStatusResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ProductInsightsBatchStatusResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProductInsightsBatchStatusResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsBatchStatusResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProductInsightsBatchStatusResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProductInsightsBatchStatusResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o ProductInsightsBatchStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsBatchStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.BatchParts.IsSet() {
		toSerialize["batch_parts"] = o.BatchParts.Get()
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Parts) {
		toSerialize["parts"] = o.Parts
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableProductInsightsBatchStatusResponse struct {
	value *ProductInsightsBatchStatusResponse
	isSet bool
}

func (v NullableProductInsightsBatchStatusResponse) Get() *ProductInsightsBatchStatusResponse {
	return v.value
}

func (v *NullableProductInsightsBatchStatusResponse) Set(val *ProductInsightsBatchStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsBatchStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsBatchStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsBatchStatusResponse(val *ProductInsightsBatchStatusResponse) *NullableProductInsightsBatchStatusResponse {
	return &NullableProductInsightsBatchStatusResponse{value: val, isSet: true}
}

func (v NullableProductInsightsBatchStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsBatchStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


