/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForecastRequestDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastRequestDataInner{}

// ForecastRequestDataInner struct for ForecastRequestDataInner
type ForecastRequestDataInner struct {
	// Date of the data point
	Date string `json:"date"`
	// Numeric value for the data point
	Value float32 `json:"value"`
}

type _ForecastRequestDataInner ForecastRequestDataInner

// NewForecastRequestDataInner instantiates a new ForecastRequestDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastRequestDataInner(date string, value float32) *ForecastRequestDataInner {
	this := ForecastRequestDataInner{}
	this.Date = date
	this.Value = value
	return &this
}

// NewForecastRequestDataInnerWithDefaults instantiates a new ForecastRequestDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastRequestDataInnerWithDefaults() *ForecastRequestDataInner {
	this := ForecastRequestDataInner{}
	return &this
}

// GetDate returns the Date field value
func (o *ForecastRequestDataInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestDataInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *ForecastRequestDataInner) SetDate(v string) {
	o.Date = v
}

// GetValue returns the Value field value
func (o *ForecastRequestDataInner) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestDataInner) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ForecastRequestDataInner) SetValue(v float32) {
	o.Value = v
}

func (o ForecastRequestDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastRequestDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ForecastRequestDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForecastRequestDataInner := _ForecastRequestDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForecastRequestDataInner)

	if err != nil {
		return err
	}

	*o = ForecastRequestDataInner(varForecastRequestDataInner)

	return err
}

type NullableForecastRequestDataInner struct {
	value *ForecastRequestDataInner
	isSet bool
}

func (v NullableForecastRequestDataInner) Get() *ForecastRequestDataInner {
	return v.value
}

func (v *NullableForecastRequestDataInner) Set(val *ForecastRequestDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastRequestDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastRequestDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastRequestDataInner(val *ForecastRequestDataInner) *NullableForecastRequestDataInner {
	return &NullableForecastRequestDataInner{value: val, isSet: true}
}

func (v NullableForecastRequestDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastRequestDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


