/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AnalysisResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisResponse{}

// AnalysisResponse struct for AnalysisResponse
type AnalysisResponse struct {
	Result *AnalysisResponseResult `json:"result,omitempty"`
	Meta *AnalysisResponseMeta `json:"meta,omitempty"`
}

// NewAnalysisResponse instantiates a new AnalysisResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisResponse() *AnalysisResponse {
	this := AnalysisResponse{}
	return &this
}

// NewAnalysisResponseWithDefaults instantiates a new AnalysisResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisResponseWithDefaults() *AnalysisResponse {
	this := AnalysisResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *AnalysisResponse) GetResult() AnalysisResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret AnalysisResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponse) GetResultOk() (*AnalysisResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *AnalysisResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given AnalysisResponseResult and assigns it to the Result field.
func (o *AnalysisResponse) SetResult(v AnalysisResponseResult) {
	o.Result = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AnalysisResponse) GetMeta() AnalysisResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret AnalysisResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisResponse) GetMetaOk() (*AnalysisResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AnalysisResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given AnalysisResponseMeta and assigns it to the Meta field.
func (o *AnalysisResponse) SetMeta(v AnalysisResponseMeta) {
	o.Meta = &v
}

func (o AnalysisResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableAnalysisResponse struct {
	value *AnalysisResponse
	isSet bool
}

func (v NullableAnalysisResponse) Get() *AnalysisResponse {
	return v.value
}

func (v *NullableAnalysisResponse) Set(val *AnalysisResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisResponse(val *AnalysisResponse) *NullableAnalysisResponse {
	return &NullableAnalysisResponse{value: val, isSet: true}
}

func (v NullableAnalysisResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


