/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ForecastResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastResponseMeta{}

// ForecastResponseMeta struct for ForecastResponseMeta
type ForecastResponseMeta struct {
	// The back-testing metric that actually chose the winning model
	SelectionMetric *string `json:"selection_metric,omitempty"`
	Timing *ForecastResponseMetaTiming `json:"timing,omitempty"`
}

// NewForecastResponseMeta instantiates a new ForecastResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastResponseMeta() *ForecastResponseMeta {
	this := ForecastResponseMeta{}
	return &this
}

// NewForecastResponseMetaWithDefaults instantiates a new ForecastResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastResponseMetaWithDefaults() *ForecastResponseMeta {
	this := ForecastResponseMeta{}
	return &this
}

// GetSelectionMetric returns the SelectionMetric field value if set, zero value otherwise.
func (o *ForecastResponseMeta) GetSelectionMetric() string {
	if o == nil || IsNil(o.SelectionMetric) {
		var ret string
		return ret
	}
	return *o.SelectionMetric
}

// GetSelectionMetricOk returns a tuple with the SelectionMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMeta) GetSelectionMetricOk() (*string, bool) {
	if o == nil || IsNil(o.SelectionMetric) {
		return nil, false
	}
	return o.SelectionMetric, true
}

// HasSelectionMetric returns a boolean if a field has been set.
func (o *ForecastResponseMeta) HasSelectionMetric() bool {
	if o != nil && !IsNil(o.SelectionMetric) {
		return true
	}

	return false
}

// SetSelectionMetric gets a reference to the given string and assigns it to the SelectionMetric field.
func (o *ForecastResponseMeta) SetSelectionMetric(v string) {
	o.SelectionMetric = &v
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *ForecastResponseMeta) GetTiming() ForecastResponseMetaTiming {
	if o == nil || IsNil(o.Timing) {
		var ret ForecastResponseMetaTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastResponseMeta) GetTimingOk() (*ForecastResponseMetaTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *ForecastResponseMeta) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given ForecastResponseMetaTiming and assigns it to the Timing field.
func (o *ForecastResponseMeta) SetTiming(v ForecastResponseMetaTiming) {
	o.Timing = &v
}

func (o ForecastResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SelectionMetric) {
		toSerialize["selection_metric"] = o.SelectionMetric
	}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	return toSerialize, nil
}

type NullableForecastResponseMeta struct {
	value *ForecastResponseMeta
	isSet bool
}

func (v NullableForecastResponseMeta) Get() *ForecastResponseMeta {
	return v.value
}

func (v *NullableForecastResponseMeta) Set(val *ForecastResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastResponseMeta(val *ForecastResponseMeta) *NullableForecastResponseMeta {
	return &NullableForecastResponseMeta{value: val, isSet: true}
}

func (v NullableForecastResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


