/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the BatchPresignResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchPresignResponse{}

// BatchPresignResponse struct for BatchPresignResponse
type BatchPresignResponse struct {
	// Presigned URL — HTTP PUT the JSON file here, including any returned headers
	UploadUrl *string `json:"upload_url,omitempty"`
	// Headers that must be sent with the upload request
	Headers *map[string]string `json:"headers,omitempty"`
	// Pass this as `file_key` to POST /v2/batch/forecast after uploading
	FileKey *string `json:"file_key,omitempty"`
	// Seconds the upload URL stays valid
	ExpiresIn *int32 `json:"expires_in,omitempty"`
}

// NewBatchPresignResponse instantiates a new BatchPresignResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchPresignResponse() *BatchPresignResponse {
	this := BatchPresignResponse{}
	return &this
}

// NewBatchPresignResponseWithDefaults instantiates a new BatchPresignResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchPresignResponseWithDefaults() *BatchPresignResponse {
	this := BatchPresignResponse{}
	return &this
}

// GetUploadUrl returns the UploadUrl field value if set, zero value otherwise.
func (o *BatchPresignResponse) GetUploadUrl() string {
	if o == nil || IsNil(o.UploadUrl) {
		var ret string
		return ret
	}
	return *o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchPresignResponse) GetUploadUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UploadUrl) {
		return nil, false
	}
	return o.UploadUrl, true
}

// HasUploadUrl returns a boolean if a field has been set.
func (o *BatchPresignResponse) HasUploadUrl() bool {
	if o != nil && !IsNil(o.UploadUrl) {
		return true
	}

	return false
}

// SetUploadUrl gets a reference to the given string and assigns it to the UploadUrl field.
func (o *BatchPresignResponse) SetUploadUrl(v string) {
	o.UploadUrl = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *BatchPresignResponse) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchPresignResponse) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *BatchPresignResponse) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *BatchPresignResponse) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetFileKey returns the FileKey field value if set, zero value otherwise.
func (o *BatchPresignResponse) GetFileKey() string {
	if o == nil || IsNil(o.FileKey) {
		var ret string
		return ret
	}
	return *o.FileKey
}

// GetFileKeyOk returns a tuple with the FileKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchPresignResponse) GetFileKeyOk() (*string, bool) {
	if o == nil || IsNil(o.FileKey) {
		return nil, false
	}
	return o.FileKey, true
}

// HasFileKey returns a boolean if a field has been set.
func (o *BatchPresignResponse) HasFileKey() bool {
	if o != nil && !IsNil(o.FileKey) {
		return true
	}

	return false
}

// SetFileKey gets a reference to the given string and assigns it to the FileKey field.
func (o *BatchPresignResponse) SetFileKey(v string) {
	o.FileKey = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *BatchPresignResponse) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchPresignResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *BatchPresignResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *BatchPresignResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

func (o BatchPresignResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchPresignResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UploadUrl) {
		toSerialize["upload_url"] = o.UploadUrl
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.FileKey) {
		toSerialize["file_key"] = o.FileKey
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableBatchPresignResponse struct {
	value *BatchPresignResponse
	isSet bool
}

func (v NullableBatchPresignResponse) Get() *BatchPresignResponse {
	return v.value
}

func (v *NullableBatchPresignResponse) Set(val *BatchPresignResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchPresignResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchPresignResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchPresignResponse(val *BatchPresignResponse) *NullableBatchPresignResponse {
	return &NullableBatchPresignResponse{value: val, isSet: true}
}

func (v NullableBatchPresignResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchPresignResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


