/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.4
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnomalyDetectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnomalyDetectionRequest{}

// AnomalyDetectionRequest struct for AnomalyDetectionRequest
type AnomalyDetectionRequest struct {
	// SKU, Product ID, or other identifier for the data series
	Identifier string `json:"identifier"`
	// Optional segmentation dimension. A series is identified by the pair identifier + tenant_context, so \"mrr\" on \"plan-pro\" and \"mrr\" on \"plan-free\" are two independent series, each with its own history and accuracy tracking. Despite the name it isn't only for multi-tenancy — use it for any slice: plan, region, store, channel, cohort, device type. 
	TenantContext NullableString `json:"tenant_context,omitempty"`
	// Data frequency: - H: Hourly - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
	Frequency string `json:"frequency"`
	// Optional start date for the forecast
	StartDate NullableString `json:"start_date,omitempty"`
	// Type of data (e.g., sales, demand, inventory, web_traffic)
	DataType string `json:"data_type"`
	// Number of periods to forecast
	Periods int32 `json:"periods"`
	// Which forecasting engine to use. The advanced variants and ensemble provide higher accuracy at a higher usage cost than standard. 
	Model *string `json:"model,omitempty"`
	// Confidence level for the prediction interval. Note that 0.80 is the widest band the foundation models (advanced-quantized, advanced-patched, ensemble) produce natively — for genuinely distinct levels beyond that, request a quantile fan via `quantiles` instead of repeating the call at several confidence levels. 
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Quantiles []float32 `json:"quantiles,omitempty"`
	ValueBounds *ValueBounds `json:"value_bounds,omitempty"`
	// What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. 
	Adjustments []AdjustmentsInner `json:"adjustments,omitempty"`
	Accumulate *AccumulateOptions `json:"accumulate,omitempty"`
	// Which back-testing error metric decides the winning model when candidates are compared: - auto: combined for demand/sales/inventory, sMAPE otherwise (default) - combined: 0.6·MASE + 0.4·sMAPE — balances accuracy and trend capture - mase: Mean Absolute Scaled Error — accuracy relative to a naive forecast - smape: Symmetric Mean Absolute Percentage Error 
	SelectionMetric NullableString `json:"selection_metric,omitempty"`
	// Historical time series data
	Data []ForecastRequestDataInner `json:"data"`
	AnomalySettings NullableAnomalyDetectionRequestAllOfAnomalySettings `json:"anomaly_settings,omitempty"`
}

type _AnomalyDetectionRequest AnomalyDetectionRequest

// NewAnomalyDetectionRequest instantiates a new AnomalyDetectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnomalyDetectionRequest(identifier string, frequency string, dataType string, periods int32, data []ForecastRequestDataInner) *AnomalyDetectionRequest {
	this := AnomalyDetectionRequest{}
	this.Identifier = identifier
	this.Frequency = frequency
	this.DataType = dataType
	this.Periods = periods
	var model string = "standard"
	this.Model = &model
	var confidenceLevel float32 = 0.8
	this.ConfidenceLevel = &confidenceLevel
	this.Data = data
	return &this
}

// NewAnomalyDetectionRequestWithDefaults instantiates a new AnomalyDetectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnomalyDetectionRequestWithDefaults() *AnomalyDetectionRequest {
	this := AnomalyDetectionRequest{}
	var model string = "standard"
	this.Model = &model
	var confidenceLevel float32 = 0.8
	this.ConfidenceLevel = &confidenceLevel
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *AnomalyDetectionRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *AnomalyDetectionRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTenantContext returns the TenantContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyDetectionRequest) GetTenantContext() string {
	if o == nil || IsNil(o.TenantContext.Get()) {
		var ret string
		return ret
	}
	return *o.TenantContext.Get()
}

// GetTenantContextOk returns a tuple with the TenantContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyDetectionRequest) GetTenantContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantContext.Get(), o.TenantContext.IsSet()
}

// HasTenantContext returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasTenantContext() bool {
	if o != nil && o.TenantContext.IsSet() {
		return true
	}

	return false
}

// SetTenantContext gets a reference to the given NullableString and assigns it to the TenantContext field.
func (o *AnomalyDetectionRequest) SetTenantContext(v string) {
	o.TenantContext.Set(&v)
}
// SetTenantContextNil sets the value for TenantContext to be an explicit nil
func (o *AnomalyDetectionRequest) SetTenantContextNil() {
	o.TenantContext.Set(nil)
}

// UnsetTenantContext ensures that no value is present for TenantContext, not even an explicit nil
func (o *AnomalyDetectionRequest) UnsetTenantContext() {
	o.TenantContext.Unset()
}

// GetFrequency returns the Frequency field value
func (o *AnomalyDetectionRequest) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *AnomalyDetectionRequest) SetFrequency(v string) {
	o.Frequency = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyDetectionRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyDetectionRequest) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *AnomalyDetectionRequest) SetStartDate(v string) {
	o.StartDate.Set(&v)
}
// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *AnomalyDetectionRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *AnomalyDetectionRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetDataType returns the DataType field value
func (o *AnomalyDetectionRequest) GetDataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataType, true
}

// SetDataType sets field value
func (o *AnomalyDetectionRequest) SetDataType(v string) {
	o.DataType = v
}

// GetPeriods returns the Periods field value
func (o *AnomalyDetectionRequest) GetPeriods() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetPeriodsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Periods, true
}

// SetPeriods sets field value
func (o *AnomalyDetectionRequest) SetPeriods(v int32) {
	o.Periods = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *AnomalyDetectionRequest) SetModel(v string) {
	o.Model = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *AnomalyDetectionRequest) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetQuantiles returns the Quantiles field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetQuantiles() []float32 {
	if o == nil || IsNil(o.Quantiles) {
		var ret []float32
		return ret
	}
	return o.Quantiles
}

// GetQuantilesOk returns a tuple with the Quantiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetQuantilesOk() ([]float32, bool) {
	if o == nil || IsNil(o.Quantiles) {
		return nil, false
	}
	return o.Quantiles, true
}

// HasQuantiles returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasQuantiles() bool {
	if o != nil && !IsNil(o.Quantiles) {
		return true
	}

	return false
}

// SetQuantiles gets a reference to the given []float32 and assigns it to the Quantiles field.
func (o *AnomalyDetectionRequest) SetQuantiles(v []float32) {
	o.Quantiles = v
}

// GetValueBounds returns the ValueBounds field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetValueBounds() ValueBounds {
	if o == nil || IsNil(o.ValueBounds) {
		var ret ValueBounds
		return ret
	}
	return *o.ValueBounds
}

// GetValueBoundsOk returns a tuple with the ValueBounds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetValueBoundsOk() (*ValueBounds, bool) {
	if o == nil || IsNil(o.ValueBounds) {
		return nil, false
	}
	return o.ValueBounds, true
}

// HasValueBounds returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasValueBounds() bool {
	if o != nil && !IsNil(o.ValueBounds) {
		return true
	}

	return false
}

// SetValueBounds gets a reference to the given ValueBounds and assigns it to the ValueBounds field.
func (o *AnomalyDetectionRequest) SetValueBounds(v ValueBounds) {
	o.ValueBounds = &v
}

// GetAdjustments returns the Adjustments field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetAdjustments() []AdjustmentsInner {
	if o == nil || IsNil(o.Adjustments) {
		var ret []AdjustmentsInner
		return ret
	}
	return o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetAdjustmentsOk() ([]AdjustmentsInner, bool) {
	if o == nil || IsNil(o.Adjustments) {
		return nil, false
	}
	return o.Adjustments, true
}

// HasAdjustments returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasAdjustments() bool {
	if o != nil && !IsNil(o.Adjustments) {
		return true
	}

	return false
}

// SetAdjustments gets a reference to the given []AdjustmentsInner and assigns it to the Adjustments field.
func (o *AnomalyDetectionRequest) SetAdjustments(v []AdjustmentsInner) {
	o.Adjustments = v
}

// GetAccumulate returns the Accumulate field value if set, zero value otherwise.
func (o *AnomalyDetectionRequest) GetAccumulate() AccumulateOptions {
	if o == nil || IsNil(o.Accumulate) {
		var ret AccumulateOptions
		return ret
	}
	return *o.Accumulate
}

// GetAccumulateOk returns a tuple with the Accumulate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetAccumulateOk() (*AccumulateOptions, bool) {
	if o == nil || IsNil(o.Accumulate) {
		return nil, false
	}
	return o.Accumulate, true
}

// HasAccumulate returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasAccumulate() bool {
	if o != nil && !IsNil(o.Accumulate) {
		return true
	}

	return false
}

// SetAccumulate gets a reference to the given AccumulateOptions and assigns it to the Accumulate field.
func (o *AnomalyDetectionRequest) SetAccumulate(v AccumulateOptions) {
	o.Accumulate = &v
}

// GetSelectionMetric returns the SelectionMetric field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyDetectionRequest) GetSelectionMetric() string {
	if o == nil || IsNil(o.SelectionMetric.Get()) {
		var ret string
		return ret
	}
	return *o.SelectionMetric.Get()
}

// GetSelectionMetricOk returns a tuple with the SelectionMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyDetectionRequest) GetSelectionMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectionMetric.Get(), o.SelectionMetric.IsSet()
}

// HasSelectionMetric returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasSelectionMetric() bool {
	if o != nil && o.SelectionMetric.IsSet() {
		return true
	}

	return false
}

// SetSelectionMetric gets a reference to the given NullableString and assigns it to the SelectionMetric field.
func (o *AnomalyDetectionRequest) SetSelectionMetric(v string) {
	o.SelectionMetric.Set(&v)
}
// SetSelectionMetricNil sets the value for SelectionMetric to be an explicit nil
func (o *AnomalyDetectionRequest) SetSelectionMetricNil() {
	o.SelectionMetric.Set(nil)
}

// UnsetSelectionMetric ensures that no value is present for SelectionMetric, not even an explicit nil
func (o *AnomalyDetectionRequest) UnsetSelectionMetric() {
	o.SelectionMetric.Unset()
}

// GetData returns the Data field value
func (o *AnomalyDetectionRequest) GetData() []ForecastRequestDataInner {
	if o == nil {
		var ret []ForecastRequestDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AnomalyDetectionRequest) GetDataOk() ([]ForecastRequestDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AnomalyDetectionRequest) SetData(v []ForecastRequestDataInner) {
	o.Data = v
}

// GetAnomalySettings returns the AnomalySettings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyDetectionRequest) GetAnomalySettings() AnomalyDetectionRequestAllOfAnomalySettings {
	if o == nil || IsNil(o.AnomalySettings.Get()) {
		var ret AnomalyDetectionRequestAllOfAnomalySettings
		return ret
	}
	return *o.AnomalySettings.Get()
}

// GetAnomalySettingsOk returns a tuple with the AnomalySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyDetectionRequest) GetAnomalySettingsOk() (*AnomalyDetectionRequestAllOfAnomalySettings, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnomalySettings.Get(), o.AnomalySettings.IsSet()
}

// HasAnomalySettings returns a boolean if a field has been set.
func (o *AnomalyDetectionRequest) HasAnomalySettings() bool {
	if o != nil && o.AnomalySettings.IsSet() {
		return true
	}

	return false
}

// SetAnomalySettings gets a reference to the given NullableAnomalyDetectionRequestAllOfAnomalySettings and assigns it to the AnomalySettings field.
func (o *AnomalyDetectionRequest) SetAnomalySettings(v AnomalyDetectionRequestAllOfAnomalySettings) {
	o.AnomalySettings.Set(&v)
}
// SetAnomalySettingsNil sets the value for AnomalySettings to be an explicit nil
func (o *AnomalyDetectionRequest) SetAnomalySettingsNil() {
	o.AnomalySettings.Set(nil)
}

// UnsetAnomalySettings ensures that no value is present for AnomalySettings, not even an explicit nil
func (o *AnomalyDetectionRequest) UnsetAnomalySettings() {
	o.AnomalySettings.Unset()
}

func (o AnomalyDetectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnomalyDetectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	if o.TenantContext.IsSet() {
		toSerialize["tenant_context"] = o.TenantContext.Get()
	}
	toSerialize["frequency"] = o.Frequency
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	toSerialize["data_type"] = o.DataType
	toSerialize["periods"] = o.Periods
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	if !IsNil(o.Quantiles) {
		toSerialize["quantiles"] = o.Quantiles
	}
	if !IsNil(o.ValueBounds) {
		toSerialize["value_bounds"] = o.ValueBounds
	}
	if !IsNil(o.Adjustments) {
		toSerialize["adjustments"] = o.Adjustments
	}
	if !IsNil(o.Accumulate) {
		toSerialize["accumulate"] = o.Accumulate
	}
	if o.SelectionMetric.IsSet() {
		toSerialize["selection_metric"] = o.SelectionMetric.Get()
	}
	toSerialize["data"] = o.Data
	if o.AnomalySettings.IsSet() {
		toSerialize["anomaly_settings"] = o.AnomalySettings.Get()
	}
	return toSerialize, nil
}

func (o *AnomalyDetectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"frequency",
		"data_type",
		"periods",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnomalyDetectionRequest := _AnomalyDetectionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnomalyDetectionRequest)

	if err != nil {
		return err
	}

	*o = AnomalyDetectionRequest(varAnomalyDetectionRequest)

	return err
}

type NullableAnomalyDetectionRequest struct {
	value *AnomalyDetectionRequest
	isSet bool
}

func (v NullableAnomalyDetectionRequest) Get() *AnomalyDetectionRequest {
	return v.value
}

func (v *NullableAnomalyDetectionRequest) Set(val *AnomalyDetectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnomalyDetectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnomalyDetectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnomalyDetectionRequest(val *AnomalyDetectionRequest) *NullableAnomalyDetectionRequest {
	return &NullableAnomalyDetectionRequest{value: val, isSet: true}
}

func (v NullableAnomalyDetectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnomalyDetectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


