/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the TrafficForecastingResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficForecastingResponseMeta{}

// TrafficForecastingResponseMeta struct for TrafficForecastingResponseMeta
type TrafficForecastingResponseMeta struct {
	Timing *TrafficForecastingResponseMetaTiming `json:"timing,omitempty"`
}

// NewTrafficForecastingResponseMeta instantiates a new TrafficForecastingResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficForecastingResponseMeta() *TrafficForecastingResponseMeta {
	this := TrafficForecastingResponseMeta{}
	return &this
}

// NewTrafficForecastingResponseMetaWithDefaults instantiates a new TrafficForecastingResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficForecastingResponseMetaWithDefaults() *TrafficForecastingResponseMeta {
	this := TrafficForecastingResponseMeta{}
	return &this
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *TrafficForecastingResponseMeta) GetTiming() TrafficForecastingResponseMetaTiming {
	if o == nil || IsNil(o.Timing) {
		var ret TrafficForecastingResponseMetaTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficForecastingResponseMeta) GetTimingOk() (*TrafficForecastingResponseMetaTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *TrafficForecastingResponseMeta) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given TrafficForecastingResponseMetaTiming and assigns it to the Timing field.
func (o *TrafficForecastingResponseMeta) SetTiming(v TrafficForecastingResponseMetaTiming) {
	o.Timing = &v
}

func (o TrafficForecastingResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficForecastingResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	return toSerialize, nil
}

type NullableTrafficForecastingResponseMeta struct {
	value *TrafficForecastingResponseMeta
	isSet bool
}

func (v NullableTrafficForecastingResponseMeta) Get() *TrafficForecastingResponseMeta {
	return v.value
}

func (v *NullableTrafficForecastingResponseMeta) Set(val *TrafficForecastingResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficForecastingResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficForecastingResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficForecastingResponseMeta(val *TrafficForecastingResponseMeta) *NullableTrafficForecastingResponseMeta {
	return &NullableTrafficForecastingResponseMeta{value: val, isSet: true}
}

func (v NullableTrafficForecastingResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficForecastingResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


