/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ProductInsightsResponseMetaTiming type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsResponseMetaTiming{}

// ProductInsightsResponseMetaTiming struct for ProductInsightsResponseMetaTiming
type ProductInsightsResponseMetaTiming struct {
	Validation *float32 `json:"validation,omitempty"`
	Analysis *float32 `json:"analysis,omitempty"`
	Total *float32 `json:"total,omitempty"`
}

// NewProductInsightsResponseMetaTiming instantiates a new ProductInsightsResponseMetaTiming object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsResponseMetaTiming() *ProductInsightsResponseMetaTiming {
	this := ProductInsightsResponseMetaTiming{}
	return &this
}

// NewProductInsightsResponseMetaTimingWithDefaults instantiates a new ProductInsightsResponseMetaTiming object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsResponseMetaTimingWithDefaults() *ProductInsightsResponseMetaTiming {
	this := ProductInsightsResponseMetaTiming{}
	return &this
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *ProductInsightsResponseMetaTiming) GetValidation() float32 {
	if o == nil || IsNil(o.Validation) {
		var ret float32
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsResponseMetaTiming) GetValidationOk() (*float32, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *ProductInsightsResponseMetaTiming) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given float32 and assigns it to the Validation field.
func (o *ProductInsightsResponseMetaTiming) SetValidation(v float32) {
	o.Validation = &v
}

// GetAnalysis returns the Analysis field value if set, zero value otherwise.
func (o *ProductInsightsResponseMetaTiming) GetAnalysis() float32 {
	if o == nil || IsNil(o.Analysis) {
		var ret float32
		return ret
	}
	return *o.Analysis
}

// GetAnalysisOk returns a tuple with the Analysis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsResponseMetaTiming) GetAnalysisOk() (*float32, bool) {
	if o == nil || IsNil(o.Analysis) {
		return nil, false
	}
	return o.Analysis, true
}

// HasAnalysis returns a boolean if a field has been set.
func (o *ProductInsightsResponseMetaTiming) HasAnalysis() bool {
	if o != nil && !IsNil(o.Analysis) {
		return true
	}

	return false
}

// SetAnalysis gets a reference to the given float32 and assigns it to the Analysis field.
func (o *ProductInsightsResponseMetaTiming) SetAnalysis(v float32) {
	o.Analysis = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ProductInsightsResponseMetaTiming) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsResponseMetaTiming) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ProductInsightsResponseMetaTiming) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *ProductInsightsResponseMetaTiming) SetTotal(v float32) {
	o.Total = &v
}

func (o ProductInsightsResponseMetaTiming) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsResponseMetaTiming) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Analysis) {
		toSerialize["analysis"] = o.Analysis
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableProductInsightsResponseMetaTiming struct {
	value *ProductInsightsResponseMetaTiming
	isSet bool
}

func (v NullableProductInsightsResponseMetaTiming) Get() *ProductInsightsResponseMetaTiming {
	return v.value
}

func (v *NullableProductInsightsResponseMetaTiming) Set(val *ProductInsightsResponseMetaTiming) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsResponseMetaTiming) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsResponseMetaTiming) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsResponseMetaTiming(val *ProductInsightsResponseMetaTiming) *NullableProductInsightsResponseMetaTiming {
	return &NullableProductInsightsResponseMetaTiming{value: val, isSet: true}
}

func (v NullableProductInsightsResponseMetaTiming) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsResponseMetaTiming) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


