/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the ProductInsightsResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsResponseMeta{}

// ProductInsightsResponseMeta struct for ProductInsightsResponseMeta
type ProductInsightsResponseMeta struct {
	Timing *ProductInsightsResponseMetaTiming `json:"timing,omitempty"`
	DataQuality *ProductInsightsResponseMetaDataQuality `json:"data_quality,omitempty"`
}

// NewProductInsightsResponseMeta instantiates a new ProductInsightsResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsResponseMeta() *ProductInsightsResponseMeta {
	this := ProductInsightsResponseMeta{}
	return &this
}

// NewProductInsightsResponseMetaWithDefaults instantiates a new ProductInsightsResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsResponseMetaWithDefaults() *ProductInsightsResponseMeta {
	this := ProductInsightsResponseMeta{}
	return &this
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *ProductInsightsResponseMeta) GetTiming() ProductInsightsResponseMetaTiming {
	if o == nil || IsNil(o.Timing) {
		var ret ProductInsightsResponseMetaTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsResponseMeta) GetTimingOk() (*ProductInsightsResponseMetaTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *ProductInsightsResponseMeta) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given ProductInsightsResponseMetaTiming and assigns it to the Timing field.
func (o *ProductInsightsResponseMeta) SetTiming(v ProductInsightsResponseMetaTiming) {
	o.Timing = &v
}

// GetDataQuality returns the DataQuality field value if set, zero value otherwise.
func (o *ProductInsightsResponseMeta) GetDataQuality() ProductInsightsResponseMetaDataQuality {
	if o == nil || IsNil(o.DataQuality) {
		var ret ProductInsightsResponseMetaDataQuality
		return ret
	}
	return *o.DataQuality
}

// GetDataQualityOk returns a tuple with the DataQuality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsResponseMeta) GetDataQualityOk() (*ProductInsightsResponseMetaDataQuality, bool) {
	if o == nil || IsNil(o.DataQuality) {
		return nil, false
	}
	return o.DataQuality, true
}

// HasDataQuality returns a boolean if a field has been set.
func (o *ProductInsightsResponseMeta) HasDataQuality() bool {
	if o != nil && !IsNil(o.DataQuality) {
		return true
	}

	return false
}

// SetDataQuality gets a reference to the given ProductInsightsResponseMetaDataQuality and assigns it to the DataQuality field.
func (o *ProductInsightsResponseMeta) SetDataQuality(v ProductInsightsResponseMetaDataQuality) {
	o.DataQuality = &v
}

func (o ProductInsightsResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	if !IsNil(o.DataQuality) {
		toSerialize["data_quality"] = o.DataQuality
	}
	return toSerialize, nil
}

type NullableProductInsightsResponseMeta struct {
	value *ProductInsightsResponseMeta
	isSet bool
}

func (v NullableProductInsightsResponseMeta) Get() *ProductInsightsResponseMeta {
	return v.value
}

func (v *NullableProductInsightsResponseMeta) Set(val *ProductInsightsResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsResponseMeta(val *ProductInsightsResponseMeta) *NullableProductInsightsResponseMeta {
	return &NullableProductInsightsResponseMeta{value: val, isSet: true}
}

func (v NullableProductInsightsResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


