/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.3
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InventoryPlanningRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryPlanningRequest{}

// InventoryPlanningRequest struct for InventoryPlanningRequest
type InventoryPlanningRequest struct {
	// SKU, Product ID, or other identifier for the inventory item
	Identifier string `json:"identifier"`
	// Data frequency for forecasting: - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly 
	Frequency string `json:"frequency"`
	// Optional start date for the forecast period
	StartDate NullableString `json:"start_date,omitempty"`
	// Number of periods to forecast ahead
	Periods int32 `json:"periods"`
	// Enable intelligent data aggregation for improved forecasting
	EnableIntelligentAggregation *bool `json:"enable_intelligent_aggregation,omitempty"`
	// Confidence level for forecast intervals (default 0.95)
	ConfidenceLevel *float32 `json:"confidence_level,omitempty"`
	// Historical demand/sales data for forecasting
	Data []InventoryPlanningRequestDataInner `json:"data"`
	InventorySettings InventoryPlanningRequestInventorySettings `json:"inventory_settings"`
}

type _InventoryPlanningRequest InventoryPlanningRequest

// NewInventoryPlanningRequest instantiates a new InventoryPlanningRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryPlanningRequest(identifier string, frequency string, periods int32, data []InventoryPlanningRequestDataInner, inventorySettings InventoryPlanningRequestInventorySettings) *InventoryPlanningRequest {
	this := InventoryPlanningRequest{}
	this.Identifier = identifier
	this.Frequency = frequency
	this.Periods = periods
	this.Data = data
	this.InventorySettings = inventorySettings
	return &this
}

// NewInventoryPlanningRequestWithDefaults instantiates a new InventoryPlanningRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryPlanningRequestWithDefaults() *InventoryPlanningRequest {
	this := InventoryPlanningRequest{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *InventoryPlanningRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *InventoryPlanningRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetFrequency returns the Frequency field value
func (o *InventoryPlanningRequest) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *InventoryPlanningRequest) SetFrequency(v string) {
	o.Frequency = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InventoryPlanningRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InventoryPlanningRequest) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *InventoryPlanningRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *InventoryPlanningRequest) SetStartDate(v string) {
	o.StartDate.Set(&v)
}
// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *InventoryPlanningRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *InventoryPlanningRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetPeriods returns the Periods field value
func (o *InventoryPlanningRequest) GetPeriods() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetPeriodsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Periods, true
}

// SetPeriods sets field value
func (o *InventoryPlanningRequest) SetPeriods(v int32) {
	o.Periods = v
}

// GetEnableIntelligentAggregation returns the EnableIntelligentAggregation field value if set, zero value otherwise.
func (o *InventoryPlanningRequest) GetEnableIntelligentAggregation() bool {
	if o == nil || IsNil(o.EnableIntelligentAggregation) {
		var ret bool
		return ret
	}
	return *o.EnableIntelligentAggregation
}

// GetEnableIntelligentAggregationOk returns a tuple with the EnableIntelligentAggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetEnableIntelligentAggregationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableIntelligentAggregation) {
		return nil, false
	}
	return o.EnableIntelligentAggregation, true
}

// HasEnableIntelligentAggregation returns a boolean if a field has been set.
func (o *InventoryPlanningRequest) HasEnableIntelligentAggregation() bool {
	if o != nil && !IsNil(o.EnableIntelligentAggregation) {
		return true
	}

	return false
}

// SetEnableIntelligentAggregation gets a reference to the given bool and assigns it to the EnableIntelligentAggregation field.
func (o *InventoryPlanningRequest) SetEnableIntelligentAggregation(v bool) {
	o.EnableIntelligentAggregation = &v
}

// GetConfidenceLevel returns the ConfidenceLevel field value if set, zero value otherwise.
func (o *InventoryPlanningRequest) GetConfidenceLevel() float32 {
	if o == nil || IsNil(o.ConfidenceLevel) {
		var ret float32
		return ret
	}
	return *o.ConfidenceLevel
}

// GetConfidenceLevelOk returns a tuple with the ConfidenceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetConfidenceLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConfidenceLevel) {
		return nil, false
	}
	return o.ConfidenceLevel, true
}

// HasConfidenceLevel returns a boolean if a field has been set.
func (o *InventoryPlanningRequest) HasConfidenceLevel() bool {
	if o != nil && !IsNil(o.ConfidenceLevel) {
		return true
	}

	return false
}

// SetConfidenceLevel gets a reference to the given float32 and assigns it to the ConfidenceLevel field.
func (o *InventoryPlanningRequest) SetConfidenceLevel(v float32) {
	o.ConfidenceLevel = &v
}

// GetData returns the Data field value
func (o *InventoryPlanningRequest) GetData() []InventoryPlanningRequestDataInner {
	if o == nil {
		var ret []InventoryPlanningRequestDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetDataOk() ([]InventoryPlanningRequestDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *InventoryPlanningRequest) SetData(v []InventoryPlanningRequestDataInner) {
	o.Data = v
}

// GetInventorySettings returns the InventorySettings field value
func (o *InventoryPlanningRequest) GetInventorySettings() InventoryPlanningRequestInventorySettings {
	if o == nil {
		var ret InventoryPlanningRequestInventorySettings
		return ret
	}

	return o.InventorySettings
}

// GetInventorySettingsOk returns a tuple with the InventorySettings field value
// and a boolean to check if the value has been set.
func (o *InventoryPlanningRequest) GetInventorySettingsOk() (*InventoryPlanningRequestInventorySettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InventorySettings, true
}

// SetInventorySettings sets field value
func (o *InventoryPlanningRequest) SetInventorySettings(v InventoryPlanningRequestInventorySettings) {
	o.InventorySettings = v
}

func (o InventoryPlanningRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryPlanningRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["frequency"] = o.Frequency
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	toSerialize["periods"] = o.Periods
	if !IsNil(o.EnableIntelligentAggregation) {
		toSerialize["enable_intelligent_aggregation"] = o.EnableIntelligentAggregation
	}
	if !IsNil(o.ConfidenceLevel) {
		toSerialize["confidence_level"] = o.ConfidenceLevel
	}
	toSerialize["data"] = o.Data
	toSerialize["inventory_settings"] = o.InventorySettings
	return toSerialize, nil
}

func (o *InventoryPlanningRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"frequency",
		"periods",
		"data",
		"inventory_settings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInventoryPlanningRequest := _InventoryPlanningRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInventoryPlanningRequest)

	if err != nil {
		return err
	}

	*o = InventoryPlanningRequest(varInventoryPlanningRequest)

	return err
}

type NullableInventoryPlanningRequest struct {
	value *InventoryPlanningRequest
	isSet bool
}

func (v NullableInventoryPlanningRequest) Get() *InventoryPlanningRequest {
	return v.value
}

func (v *NullableInventoryPlanningRequest) Set(val *InventoryPlanningRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryPlanningRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryPlanningRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryPlanningRequest(val *InventoryPlanningRequest) *NullableInventoryPlanningRequest {
	return &NullableInventoryPlanningRequest{value: val, isSet: true}
}

func (v NullableInventoryPlanningRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryPlanningRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


