/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"time"
)

// checks if the BatchForecastStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchForecastStatusResponse{}

// BatchForecastStatusResponse struct for BatchForecastStatusResponse
type BatchForecastStatusResponse struct {
	// The batch id
	Identifier *string `json:"identifier,omitempty"`
	Status *string `json:"status,omitempty"`
	// Number of parts the batch was split into for processing
	BatchParts NullableInt32 `json:"batch_parts,omitempty"`
	Results *BatchForecastStatusResponseResults `json:"results,omitempty"`
	// Per-part progress metadata (the forecasts themselves live under results.data)
	Parts []BatchForecastStatusResponsePartsInner `json:"parts,omitempty"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewBatchForecastStatusResponse instantiates a new BatchForecastStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchForecastStatusResponse() *BatchForecastStatusResponse {
	this := BatchForecastStatusResponse{}
	return &this
}

// NewBatchForecastStatusResponseWithDefaults instantiates a new BatchForecastStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchForecastStatusResponseWithDefaults() *BatchForecastStatusResponse {
	this := BatchForecastStatusResponse{}
	return &this
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *BatchForecastStatusResponse) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BatchForecastStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetBatchParts returns the BatchParts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastStatusResponse) GetBatchParts() int32 {
	if o == nil || IsNil(o.BatchParts.Get()) {
		var ret int32
		return ret
	}
	return *o.BatchParts.Get()
}

// GetBatchPartsOk returns a tuple with the BatchParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastStatusResponse) GetBatchPartsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatchParts.Get(), o.BatchParts.IsSet()
}

// HasBatchParts returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasBatchParts() bool {
	if o != nil && o.BatchParts.IsSet() {
		return true
	}

	return false
}

// SetBatchParts gets a reference to the given NullableInt32 and assigns it to the BatchParts field.
func (o *BatchForecastStatusResponse) SetBatchParts(v int32) {
	o.BatchParts.Set(&v)
}
// SetBatchPartsNil sets the value for BatchParts to be an explicit nil
func (o *BatchForecastStatusResponse) SetBatchPartsNil() {
	o.BatchParts.Set(nil)
}

// UnsetBatchParts ensures that no value is present for BatchParts, not even an explicit nil
func (o *BatchForecastStatusResponse) UnsetBatchParts() {
	o.BatchParts.Unset()
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetResults() BatchForecastStatusResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret BatchForecastStatusResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetResultsOk() (*BatchForecastStatusResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given BatchForecastStatusResponseResults and assigns it to the Results field.
func (o *BatchForecastStatusResponse) SetResults(v BatchForecastStatusResponseResults) {
	o.Results = &v
}

// GetParts returns the Parts field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetParts() []BatchForecastStatusResponsePartsInner {
	if o == nil || IsNil(o.Parts) {
		var ret []BatchForecastStatusResponsePartsInner
		return ret
	}
	return o.Parts
}

// GetPartsOk returns a tuple with the Parts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetPartsOk() ([]BatchForecastStatusResponsePartsInner, bool) {
	if o == nil || IsNil(o.Parts) {
		return nil, false
	}
	return o.Parts, true
}

// HasParts returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasParts() bool {
	if o != nil && !IsNil(o.Parts) {
		return true
	}

	return false
}

// SetParts gets a reference to the given []BatchForecastStatusResponsePartsInner and assigns it to the Parts field.
func (o *BatchForecastStatusResponse) SetParts(v []BatchForecastStatusResponsePartsInner) {
	o.Parts = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastStatusResponse) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastStatusResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *BatchForecastStatusResponse) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *BatchForecastStatusResponse) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *BatchForecastStatusResponse) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchForecastStatusResponse) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchForecastStatusResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *BatchForecastStatusResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *BatchForecastStatusResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *BatchForecastStatusResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *BatchForecastStatusResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *BatchForecastStatusResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchForecastStatusResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BatchForecastStatusResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *BatchForecastStatusResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o BatchForecastStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchForecastStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.BatchParts.IsSet() {
		toSerialize["batch_parts"] = o.BatchParts.Get()
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Parts) {
		toSerialize["parts"] = o.Parts
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableBatchForecastStatusResponse struct {
	value *BatchForecastStatusResponse
	isSet bool
}

func (v NullableBatchForecastStatusResponse) Get() *BatchForecastStatusResponse {
	return v.value
}

func (v *NullableBatchForecastStatusResponse) Set(val *BatchForecastStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchForecastStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchForecastStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchForecastStatusResponse(val *BatchForecastStatusResponse) *NullableBatchForecastStatusResponse {
	return &NullableBatchForecastStatusResponse{value: val, isSet: true}
}

func (v NullableBatchForecastStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchForecastStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


