/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the AutoSelection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoSelection{}

// AutoSelection Present only when `model: auto` was requested — which model actually answered, and why. On /v2/forecast and batch results it appears inside `model_info`; on /v2/inventory-planning and /v2/traffic-forecasting it appears under `meta`. 
type AutoSelection struct {
	Requested *string `json:"requested,omitempty"`
	// The model that produced this response
	Selected *string `json:"selected,omitempty"`
	// Why this model was selected. `scored_winner` means one model beat every alternative by a clear margin on realized accuracy for this identifier; everything else means the evidence-gathering default was served. 
	Reason *string `json:"reason,omitempty"`
	// Per-model realized-accuracy scorecard for this identifier, when one exists
	Scores map[string]AutoSelectionScoresValue `json:"scores,omitempty"`
}

// NewAutoSelection instantiates a new AutoSelection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoSelection() *AutoSelection {
	this := AutoSelection{}
	return &this
}

// NewAutoSelectionWithDefaults instantiates a new AutoSelection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoSelectionWithDefaults() *AutoSelection {
	this := AutoSelection{}
	return &this
}

// GetRequested returns the Requested field value if set, zero value otherwise.
func (o *AutoSelection) GetRequested() string {
	if o == nil || IsNil(o.Requested) {
		var ret string
		return ret
	}
	return *o.Requested
}

// GetRequestedOk returns a tuple with the Requested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoSelection) GetRequestedOk() (*string, bool) {
	if o == nil || IsNil(o.Requested) {
		return nil, false
	}
	return o.Requested, true
}

// HasRequested returns a boolean if a field has been set.
func (o *AutoSelection) HasRequested() bool {
	if o != nil && !IsNil(o.Requested) {
		return true
	}

	return false
}

// SetRequested gets a reference to the given string and assigns it to the Requested field.
func (o *AutoSelection) SetRequested(v string) {
	o.Requested = &v
}

// GetSelected returns the Selected field value if set, zero value otherwise.
func (o *AutoSelection) GetSelected() string {
	if o == nil || IsNil(o.Selected) {
		var ret string
		return ret
	}
	return *o.Selected
}

// GetSelectedOk returns a tuple with the Selected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoSelection) GetSelectedOk() (*string, bool) {
	if o == nil || IsNil(o.Selected) {
		return nil, false
	}
	return o.Selected, true
}

// HasSelected returns a boolean if a field has been set.
func (o *AutoSelection) HasSelected() bool {
	if o != nil && !IsNil(o.Selected) {
		return true
	}

	return false
}

// SetSelected gets a reference to the given string and assigns it to the Selected field.
func (o *AutoSelection) SetSelected(v string) {
	o.Selected = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AutoSelection) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoSelection) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AutoSelection) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AutoSelection) SetReason(v string) {
	o.Reason = &v
}

// GetScores returns the Scores field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoSelection) GetScores() map[string]AutoSelectionScoresValue {
	if o == nil {
		var ret map[string]AutoSelectionScoresValue
		return ret
	}
	return o.Scores
}

// GetScoresOk returns a tuple with the Scores field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoSelection) GetScoresOk() (*map[string]AutoSelectionScoresValue, bool) {
	if o == nil || IsNil(o.Scores) {
		return nil, false
	}
	return &o.Scores, true
}

// HasScores returns a boolean if a field has been set.
func (o *AutoSelection) HasScores() bool {
	if o != nil && !IsNil(o.Scores) {
		return true
	}

	return false
}

// SetScores gets a reference to the given map[string]AutoSelectionScoresValue and assigns it to the Scores field.
func (o *AutoSelection) SetScores(v map[string]AutoSelectionScoresValue) {
	o.Scores = v
}

func (o AutoSelection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoSelection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requested) {
		toSerialize["requested"] = o.Requested
	}
	if !IsNil(o.Selected) {
		toSerialize["selected"] = o.Selected
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if o.Scores != nil {
		toSerialize["scores"] = o.Scores
	}
	return toSerialize, nil
}

type NullableAutoSelection struct {
	value *AutoSelection
	isSet bool
}

func (v NullableAutoSelection) Get() *AutoSelection {
	return v.value
}

func (v *NullableAutoSelection) Set(val *AutoSelection) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoSelection) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoSelection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoSelection(val *AutoSelection) *NullableAutoSelection {
	return &NullableAutoSelection{value: val, isSet: true}
}

func (v NullableAutoSelection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoSelection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


