/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdjustmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdjustmentsInner{}

// AdjustmentsInner struct for AdjustmentsInner
type AdjustmentsInner struct {
	// multiplier scales the value; level_shift adds a constant
	Type string `json:"type"`
	// The factor or the offset. A multiplier must be zero or greater.
	Value float32 `json:"value"`
	// Optional 1-based inclusive start of the window; omit to start at period 1
	FromPeriod *int32 `json:"from_period,omitempty"`
	// Optional 1-based inclusive end of the window; omit to run to the horizon. Must fall within `periods`.
	ToPeriod *int32 `json:"to_period,omitempty"`
}

type _AdjustmentsInner AdjustmentsInner

// NewAdjustmentsInner instantiates a new AdjustmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdjustmentsInner(type_ string, value float32) *AdjustmentsInner {
	this := AdjustmentsInner{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewAdjustmentsInnerWithDefaults instantiates a new AdjustmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdjustmentsInnerWithDefaults() *AdjustmentsInner {
	this := AdjustmentsInner{}
	return &this
}

// GetType returns the Type field value
func (o *AdjustmentsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdjustmentsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdjustmentsInner) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *AdjustmentsInner) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AdjustmentsInner) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AdjustmentsInner) SetValue(v float32) {
	o.Value = v
}

// GetFromPeriod returns the FromPeriod field value if set, zero value otherwise.
func (o *AdjustmentsInner) GetFromPeriod() int32 {
	if o == nil || IsNil(o.FromPeriod) {
		var ret int32
		return ret
	}
	return *o.FromPeriod
}

// GetFromPeriodOk returns a tuple with the FromPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdjustmentsInner) GetFromPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.FromPeriod) {
		return nil, false
	}
	return o.FromPeriod, true
}

// HasFromPeriod returns a boolean if a field has been set.
func (o *AdjustmentsInner) HasFromPeriod() bool {
	if o != nil && !IsNil(o.FromPeriod) {
		return true
	}

	return false
}

// SetFromPeriod gets a reference to the given int32 and assigns it to the FromPeriod field.
func (o *AdjustmentsInner) SetFromPeriod(v int32) {
	o.FromPeriod = &v
}

// GetToPeriod returns the ToPeriod field value if set, zero value otherwise.
func (o *AdjustmentsInner) GetToPeriod() int32 {
	if o == nil || IsNil(o.ToPeriod) {
		var ret int32
		return ret
	}
	return *o.ToPeriod
}

// GetToPeriodOk returns a tuple with the ToPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdjustmentsInner) GetToPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.ToPeriod) {
		return nil, false
	}
	return o.ToPeriod, true
}

// HasToPeriod returns a boolean if a field has been set.
func (o *AdjustmentsInner) HasToPeriod() bool {
	if o != nil && !IsNil(o.ToPeriod) {
		return true
	}

	return false
}

// SetToPeriod gets a reference to the given int32 and assigns it to the ToPeriod field.
func (o *AdjustmentsInner) SetToPeriod(v int32) {
	o.ToPeriod = &v
}

func (o AdjustmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdjustmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	if !IsNil(o.FromPeriod) {
		toSerialize["from_period"] = o.FromPeriod
	}
	if !IsNil(o.ToPeriod) {
		toSerialize["to_period"] = o.ToPeriod
	}
	return toSerialize, nil
}

func (o *AdjustmentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdjustmentsInner := _AdjustmentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdjustmentsInner)

	if err != nil {
		return err
	}

	*o = AdjustmentsInner(varAdjustmentsInner)

	return err
}

type NullableAdjustmentsInner struct {
	value *AdjustmentsInner
	isSet bool
}

func (v NullableAdjustmentsInner) Get() *AdjustmentsInner {
	return v.value
}

func (v *NullableAdjustmentsInner) Set(val *AdjustmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAdjustmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAdjustmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdjustmentsInner(val *AdjustmentsInner) *NullableAdjustmentsInner {
	return &NullableAdjustmentsInner{value: val, isSet: true}
}

func (v NullableAdjustmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdjustmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


