/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.2.0
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductInsightsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInsightsRequest{}

// ProductInsightsRequest At least one of `sales`, `purchases` or `cost_history` must be provided.
type ProductInsightsRequest struct {
	// Product identifier
	Identifier string `json:"identifier"`
	TenantContext NullableString `json:"tenant_context,omitempty"`
	ProductName NullableString `json:"product_name,omitempty"`
	ProductGroupId NullableString `json:"product_group_id,omitempty"`
	// ISO 4217 currency the analysis reports in
	BaseCurrency NullableString `json:"base_currency,omitempty"`
	BaselinePeriodDays *ProductInsightsRequestBaselinePeriodDays `json:"baseline_period_days,omitempty"`
	// Locale for insight texts
	Locale *string `json:"locale,omitempty"`
	Sales []ProductInsightsRequestSalesInner `json:"sales,omitempty"`
	Purchases []ProductInsightsRequestPurchasesInner `json:"purchases,omitempty"`
	CostHistory []ProductInsightsRequestCostHistoryInner `json:"cost_history,omitempty"`
	InsightSettings NullableProductInsightsRequestInsightSettings `json:"insight_settings,omitempty"`
}

type _ProductInsightsRequest ProductInsightsRequest

// NewProductInsightsRequest instantiates a new ProductInsightsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInsightsRequest(identifier string) *ProductInsightsRequest {
	this := ProductInsightsRequest{}
	this.Identifier = identifier
	var baselinePeriodDays ProductInsightsRequestBaselinePeriodDays = auto
	this.BaselinePeriodDays = &baselinePeriodDays
	var locale string = "en"
	this.Locale = &locale
	return &this
}

// NewProductInsightsRequestWithDefaults instantiates a new ProductInsightsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInsightsRequestWithDefaults() *ProductInsightsRequest {
	this := ProductInsightsRequest{}
	var baselinePeriodDays ProductInsightsRequestBaselinePeriodDays = auto
	this.BaselinePeriodDays = &baselinePeriodDays
	var locale string = "en"
	this.Locale = &locale
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *ProductInsightsRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ProductInsightsRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTenantContext returns the TenantContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetTenantContext() string {
	if o == nil || IsNil(o.TenantContext.Get()) {
		var ret string
		return ret
	}
	return *o.TenantContext.Get()
}

// GetTenantContextOk returns a tuple with the TenantContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetTenantContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantContext.Get(), o.TenantContext.IsSet()
}

// HasTenantContext returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasTenantContext() bool {
	if o != nil && o.TenantContext.IsSet() {
		return true
	}

	return false
}

// SetTenantContext gets a reference to the given NullableString and assigns it to the TenantContext field.
func (o *ProductInsightsRequest) SetTenantContext(v string) {
	o.TenantContext.Set(&v)
}
// SetTenantContextNil sets the value for TenantContext to be an explicit nil
func (o *ProductInsightsRequest) SetTenantContextNil() {
	o.TenantContext.Set(nil)
}

// UnsetTenantContext ensures that no value is present for TenantContext, not even an explicit nil
func (o *ProductInsightsRequest) UnsetTenantContext() {
	o.TenantContext.Unset()
}

// GetProductName returns the ProductName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetProductName() string {
	if o == nil || IsNil(o.ProductName.Get()) {
		var ret string
		return ret
	}
	return *o.ProductName.Get()
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductName.Get(), o.ProductName.IsSet()
}

// HasProductName returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasProductName() bool {
	if o != nil && o.ProductName.IsSet() {
		return true
	}

	return false
}

// SetProductName gets a reference to the given NullableString and assigns it to the ProductName field.
func (o *ProductInsightsRequest) SetProductName(v string) {
	o.ProductName.Set(&v)
}
// SetProductNameNil sets the value for ProductName to be an explicit nil
func (o *ProductInsightsRequest) SetProductNameNil() {
	o.ProductName.Set(nil)
}

// UnsetProductName ensures that no value is present for ProductName, not even an explicit nil
func (o *ProductInsightsRequest) UnsetProductName() {
	o.ProductName.Unset()
}

// GetProductGroupId returns the ProductGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetProductGroupId() string {
	if o == nil || IsNil(o.ProductGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.ProductGroupId.Get()
}

// GetProductGroupIdOk returns a tuple with the ProductGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetProductGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductGroupId.Get(), o.ProductGroupId.IsSet()
}

// HasProductGroupId returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasProductGroupId() bool {
	if o != nil && o.ProductGroupId.IsSet() {
		return true
	}

	return false
}

// SetProductGroupId gets a reference to the given NullableString and assigns it to the ProductGroupId field.
func (o *ProductInsightsRequest) SetProductGroupId(v string) {
	o.ProductGroupId.Set(&v)
}
// SetProductGroupIdNil sets the value for ProductGroupId to be an explicit nil
func (o *ProductInsightsRequest) SetProductGroupIdNil() {
	o.ProductGroupId.Set(nil)
}

// UnsetProductGroupId ensures that no value is present for ProductGroupId, not even an explicit nil
func (o *ProductInsightsRequest) UnsetProductGroupId() {
	o.ProductGroupId.Unset()
}

// GetBaseCurrency returns the BaseCurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetBaseCurrency() string {
	if o == nil || IsNil(o.BaseCurrency.Get()) {
		var ret string
		return ret
	}
	return *o.BaseCurrency.Get()
}

// GetBaseCurrencyOk returns a tuple with the BaseCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetBaseCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseCurrency.Get(), o.BaseCurrency.IsSet()
}

// HasBaseCurrency returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasBaseCurrency() bool {
	if o != nil && o.BaseCurrency.IsSet() {
		return true
	}

	return false
}

// SetBaseCurrency gets a reference to the given NullableString and assigns it to the BaseCurrency field.
func (o *ProductInsightsRequest) SetBaseCurrency(v string) {
	o.BaseCurrency.Set(&v)
}
// SetBaseCurrencyNil sets the value for BaseCurrency to be an explicit nil
func (o *ProductInsightsRequest) SetBaseCurrencyNil() {
	o.BaseCurrency.Set(nil)
}

// UnsetBaseCurrency ensures that no value is present for BaseCurrency, not even an explicit nil
func (o *ProductInsightsRequest) UnsetBaseCurrency() {
	o.BaseCurrency.Unset()
}

// GetBaselinePeriodDays returns the BaselinePeriodDays field value if set, zero value otherwise.
func (o *ProductInsightsRequest) GetBaselinePeriodDays() ProductInsightsRequestBaselinePeriodDays {
	if o == nil || IsNil(o.BaselinePeriodDays) {
		var ret ProductInsightsRequestBaselinePeriodDays
		return ret
	}
	return *o.BaselinePeriodDays
}

// GetBaselinePeriodDaysOk returns a tuple with the BaselinePeriodDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequest) GetBaselinePeriodDaysOk() (*ProductInsightsRequestBaselinePeriodDays, bool) {
	if o == nil || IsNil(o.BaselinePeriodDays) {
		return nil, false
	}
	return o.BaselinePeriodDays, true
}

// HasBaselinePeriodDays returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasBaselinePeriodDays() bool {
	if o != nil && !IsNil(o.BaselinePeriodDays) {
		return true
	}

	return false
}

// SetBaselinePeriodDays gets a reference to the given ProductInsightsRequestBaselinePeriodDays and assigns it to the BaselinePeriodDays field.
func (o *ProductInsightsRequest) SetBaselinePeriodDays(v ProductInsightsRequestBaselinePeriodDays) {
	o.BaselinePeriodDays = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *ProductInsightsRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInsightsRequest) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *ProductInsightsRequest) SetLocale(v string) {
	o.Locale = &v
}

// GetSales returns the Sales field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetSales() []ProductInsightsRequestSalesInner {
	if o == nil {
		var ret []ProductInsightsRequestSalesInner
		return ret
	}
	return o.Sales
}

// GetSalesOk returns a tuple with the Sales field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetSalesOk() ([]ProductInsightsRequestSalesInner, bool) {
	if o == nil || IsNil(o.Sales) {
		return nil, false
	}
	return o.Sales, true
}

// HasSales returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasSales() bool {
	if o != nil && !IsNil(o.Sales) {
		return true
	}

	return false
}

// SetSales gets a reference to the given []ProductInsightsRequestSalesInner and assigns it to the Sales field.
func (o *ProductInsightsRequest) SetSales(v []ProductInsightsRequestSalesInner) {
	o.Sales = v
}

// GetPurchases returns the Purchases field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetPurchases() []ProductInsightsRequestPurchasesInner {
	if o == nil {
		var ret []ProductInsightsRequestPurchasesInner
		return ret
	}
	return o.Purchases
}

// GetPurchasesOk returns a tuple with the Purchases field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetPurchasesOk() ([]ProductInsightsRequestPurchasesInner, bool) {
	if o == nil || IsNil(o.Purchases) {
		return nil, false
	}
	return o.Purchases, true
}

// HasPurchases returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasPurchases() bool {
	if o != nil && !IsNil(o.Purchases) {
		return true
	}

	return false
}

// SetPurchases gets a reference to the given []ProductInsightsRequestPurchasesInner and assigns it to the Purchases field.
func (o *ProductInsightsRequest) SetPurchases(v []ProductInsightsRequestPurchasesInner) {
	o.Purchases = v
}

// GetCostHistory returns the CostHistory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetCostHistory() []ProductInsightsRequestCostHistoryInner {
	if o == nil {
		var ret []ProductInsightsRequestCostHistoryInner
		return ret
	}
	return o.CostHistory
}

// GetCostHistoryOk returns a tuple with the CostHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetCostHistoryOk() ([]ProductInsightsRequestCostHistoryInner, bool) {
	if o == nil || IsNil(o.CostHistory) {
		return nil, false
	}
	return o.CostHistory, true
}

// HasCostHistory returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasCostHistory() bool {
	if o != nil && !IsNil(o.CostHistory) {
		return true
	}

	return false
}

// SetCostHistory gets a reference to the given []ProductInsightsRequestCostHistoryInner and assigns it to the CostHistory field.
func (o *ProductInsightsRequest) SetCostHistory(v []ProductInsightsRequestCostHistoryInner) {
	o.CostHistory = v
}

// GetInsightSettings returns the InsightSettings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductInsightsRequest) GetInsightSettings() ProductInsightsRequestInsightSettings {
	if o == nil || IsNil(o.InsightSettings.Get()) {
		var ret ProductInsightsRequestInsightSettings
		return ret
	}
	return *o.InsightSettings.Get()
}

// GetInsightSettingsOk returns a tuple with the InsightSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductInsightsRequest) GetInsightSettingsOk() (*ProductInsightsRequestInsightSettings, bool) {
	if o == nil {
		return nil, false
	}
	return o.InsightSettings.Get(), o.InsightSettings.IsSet()
}

// HasInsightSettings returns a boolean if a field has been set.
func (o *ProductInsightsRequest) HasInsightSettings() bool {
	if o != nil && o.InsightSettings.IsSet() {
		return true
	}

	return false
}

// SetInsightSettings gets a reference to the given NullableProductInsightsRequestInsightSettings and assigns it to the InsightSettings field.
func (o *ProductInsightsRequest) SetInsightSettings(v ProductInsightsRequestInsightSettings) {
	o.InsightSettings.Set(&v)
}
// SetInsightSettingsNil sets the value for InsightSettings to be an explicit nil
func (o *ProductInsightsRequest) SetInsightSettingsNil() {
	o.InsightSettings.Set(nil)
}

// UnsetInsightSettings ensures that no value is present for InsightSettings, not even an explicit nil
func (o *ProductInsightsRequest) UnsetInsightSettings() {
	o.InsightSettings.Unset()
}

func (o ProductInsightsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInsightsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	if o.TenantContext.IsSet() {
		toSerialize["tenant_context"] = o.TenantContext.Get()
	}
	if o.ProductName.IsSet() {
		toSerialize["product_name"] = o.ProductName.Get()
	}
	if o.ProductGroupId.IsSet() {
		toSerialize["product_group_id"] = o.ProductGroupId.Get()
	}
	if o.BaseCurrency.IsSet() {
		toSerialize["base_currency"] = o.BaseCurrency.Get()
	}
	if !IsNil(o.BaselinePeriodDays) {
		toSerialize["baseline_period_days"] = o.BaselinePeriodDays
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if o.Sales != nil {
		toSerialize["sales"] = o.Sales
	}
	if o.Purchases != nil {
		toSerialize["purchases"] = o.Purchases
	}
	if o.CostHistory != nil {
		toSerialize["cost_history"] = o.CostHistory
	}
	if o.InsightSettings.IsSet() {
		toSerialize["insight_settings"] = o.InsightSettings.Get()
	}
	return toSerialize, nil
}

func (o *ProductInsightsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductInsightsRequest := _ProductInsightsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductInsightsRequest)

	if err != nil {
		return err
	}

	*o = ProductInsightsRequest(varProductInsightsRequest)

	return err
}

type NullableProductInsightsRequest struct {
	value *ProductInsightsRequest
	isSet bool
}

func (v NullableProductInsightsRequest) Get() *ProductInsightsRequest {
	return v.value
}

func (v *NullableProductInsightsRequest) Set(val *ProductInsightsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInsightsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInsightsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInsightsRequest(val *ProductInsightsRequest) *NullableProductInsightsRequest {
	return &NullableProductInsightsRequest{value: val, isSet: true}
}

func (v NullableProductInsightsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInsightsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


