/*
ForecastAPI

Time series forecasting service with multiple algorithms and automatic method selection

API version: 2.0.2
Contact: support@forecastapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forecastapi

import (
	"encoding/json"
)

// checks if the CreateProductInsights400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductInsights400Response{}

// CreateProductInsights400Response struct for CreateProductInsights400Response
type CreateProductInsights400Response struct {
	Error *string `json:"error,omitempty"`
	TimeTakenMs *float32 `json:"time_taken_ms,omitempty"`
}

// NewCreateProductInsights400Response instantiates a new CreateProductInsights400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductInsights400Response() *CreateProductInsights400Response {
	this := CreateProductInsights400Response{}
	return &this
}

// NewCreateProductInsights400ResponseWithDefaults instantiates a new CreateProductInsights400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductInsights400ResponseWithDefaults() *CreateProductInsights400Response {
	this := CreateProductInsights400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateProductInsights400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductInsights400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateProductInsights400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateProductInsights400Response) SetError(v string) {
	o.Error = &v
}

// GetTimeTakenMs returns the TimeTakenMs field value if set, zero value otherwise.
func (o *CreateProductInsights400Response) GetTimeTakenMs() float32 {
	if o == nil || IsNil(o.TimeTakenMs) {
		var ret float32
		return ret
	}
	return *o.TimeTakenMs
}

// GetTimeTakenMsOk returns a tuple with the TimeTakenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductInsights400Response) GetTimeTakenMsOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeTakenMs) {
		return nil, false
	}
	return o.TimeTakenMs, true
}

// HasTimeTakenMs returns a boolean if a field has been set.
func (o *CreateProductInsights400Response) HasTimeTakenMs() bool {
	if o != nil && !IsNil(o.TimeTakenMs) {
		return true
	}

	return false
}

// SetTimeTakenMs gets a reference to the given float32 and assigns it to the TimeTakenMs field.
func (o *CreateProductInsights400Response) SetTimeTakenMs(v float32) {
	o.TimeTakenMs = &v
}

func (o CreateProductInsights400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductInsights400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.TimeTakenMs) {
		toSerialize["time_taken_ms"] = o.TimeTakenMs
	}
	return toSerialize, nil
}

type NullableCreateProductInsights400Response struct {
	value *CreateProductInsights400Response
	isSet bool
}

func (v NullableCreateProductInsights400Response) Get() *CreateProductInsights400Response {
	return v.value
}

func (v *NullableCreateProductInsights400Response) Set(val *CreateProductInsights400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductInsights400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductInsights400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductInsights400Response(val *CreateProductInsights400Response) *NullableCreateProductInsights400Response {
	return &NullableCreateProductInsights400Response{value: val, isSet: true}
}

func (v NullableCreateProductInsights400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductInsights400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


